import { LanguageConfig, LanguageId } from './types';

export const SUPPORTED_LANGUAGES: Record<LanguageId, LanguageConfig> = {
  java: {
    id: 'java',
    name: 'Java 21',
    version: '21.0.1',
    fileExtension: 'java',
    judge0LanguageId: 62,
    pistonLanguage: 'java',
    compileCommand: 'javac Solution.java',
    runCommand: 'java Solution',
    timeoutSeconds: 4,
    memoryLimitMb: 256,
  },
  python: {
    id: 'python',
    name: 'Python 3.12',
    version: '3.12.0',
    fileExtension: 'py',
    judge0LanguageId: 71,
    pistonLanguage: 'python',
    runCommand: 'python3 solution.py',
    timeoutSeconds: 5,
    memoryLimitMb: 128,
  },
  cpp: {
    id: 'cpp',
    name: 'C++17',
    version: '17.0.0',
    fileExtension: 'cpp',
    judge0LanguageId: 54,
    pistonLanguage: 'cpp',
    compileCommand: 'g++ -O3 solution.cpp -o solution',
    runCommand: './solution',
    timeoutSeconds: 2,
    memoryLimitMb: 128,
  },
  javascript: {
    id: 'javascript',
    name: 'JavaScript (Node 20)',
    version: '20.10.0',
    fileExtension: 'js',
    judge0LanguageId: 63,
    pistonLanguage: 'javascript',
    runCommand: 'node solution.js',
    timeoutSeconds: 3,
    memoryLimitMb: 128,
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript 5.3',
    version: '5.3.3',
    fileExtension: 'ts',
    judge0LanguageId: 74,
    pistonLanguage: 'typescript',
    runCommand: 'npx ts-node solution.ts',
    timeoutSeconds: 4,
    memoryLimitMb: 256,
  },
  go: {
    id: 'go',
    name: 'Go 1.21',
    version: '1.21.5',
    fileExtension: 'go',
    judge0LanguageId: 60,
    pistonLanguage: 'go',
    runCommand: 'go run solution.go',
    timeoutSeconds: 3,
    memoryLimitMb: 128,
  },
  rust: {
    id: 'rust',
    name: 'Rust 2021',
    version: '1.75.0',
    fileExtension: 'rs',
    judge0LanguageId: 73,
    pistonLanguage: 'rust',
    compileCommand: 'rustc -O solution.rs',
    runCommand: './solution',
    timeoutSeconds: 3,
    memoryLimitMb: 128,
  },
  csharp: {
    id: 'csharp',
    name: 'C# 11',
    version: '11.0.0',
    fileExtension: 'cs',
    judge0LanguageId: 51,
    pistonLanguage: 'csharp',
    compileCommand: 'dotnet build',
    runCommand: 'dotnet run',
    timeoutSeconds: 4,
    memoryLimitMb: 256,
  },
  kotlin: {
    id: 'kotlin',
    name: 'Kotlin 1.9',
    version: '1.9.20',
    fileExtension: 'kt',
    judge0LanguageId: 78,
    pistonLanguage: 'kotlin',
    compileCommand: 'kotlinc solution.kt -include-runtime -d solution.jar',
    runCommand: 'java -jar solution.jar',
    timeoutSeconds: 4,
    memoryLimitMb: 256,
  },
};
