import { ProblemModel } from '../../types';

export const ADVANCED_ALGORITHMS_PROBLEMS: ProblemModel[] = [
  // 1. Advanced String Matching (KMP & Manacher)
  {
    id: 'lc-214-adv',
    slug: 'shortest-palindrome-kmp',
    leetcodeNumber: 214,
    title: 'Shortest Palindrome (KMP Table)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 33.0,
    isPremium: false,
    topics: ['String', 'Rolling Hash', 'String Matching', 'Hash Function'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/shortest-palindrome/',
    notes: 'KMP prefix table (LPS) on s + "#" + reverse(s) to find longest palindromic prefix.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.advanced-string-matching',
    patternSlug: 'advanced-string-matching',
    patternTitle: 'Advanced String Matching (KMP & Manacher)',
    questTitle: 'Quest: The Lexical Master',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-5-adv',
    slug: 'longest-palindromic-substring-manacher',
    leetcodeNumber: 5,
    title: 'Longest Palindromic Substring (Manacher Algorithm)',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 100,
    acceptanceRate: 33.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/longest-palindromic-substring/',
    notes: 'Manacher Algorithm finding longest palindromic substring in linear O(N) time.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.advanced-string-matching',
    patternSlug: 'advanced-string-matching',
    patternTitle: 'Advanced String Matching (KMP & Manacher)',
    questTitle: 'Quest: The Lexical Master',
    kingdomTitle: 'The Citadel of Masters',
  },

  // 2. Segment Trees & Binary Indexed Trees (Fenwick)
  {
    id: 'lc-307',
    slug: 'range-sum-query-mutable',
    leetcodeNumber: 307,
    title: 'Range Sum Query - Mutable',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'Design', 'Binary Indexed Tree', 'Segment Tree'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/range-sum-query-mutable/',
    notes: 'Fenwick Tree (BIT) or Segment Tree point update and range sum query.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-315',
    slug: 'count-of-smaller-numbers-after-self',
    leetcodeNumber: 315,
    title: 'Count of Smaller Numbers After Self',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Merge Sort', 'Ordered Set'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/',
    notes: 'BIT with coordinate compression or Merge Sort index tracking.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-493-adv',
    slug: 'reverse-pairs',
    leetcodeNumber: 493,
    title: 'Reverse Pairs',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Merge Sort', 'Ordered Set'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/reverse-pairs/',
    notes: 'Merge Sort divide-and-conquer counting nums[i] > 2 * nums[j] pairs.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },

  // 3. Network Flow & Matching
  {
    id: 'lc-1349',
    slug: 'maximum-students-taking-exam',
    leetcodeNumber: 1349,
    title: 'Maximum Students Taking Exam',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Bit Manipulation', 'Matrix', 'Bitmask'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-students-taking-exam/',
    notes: 'Max Bipartite Matching / Max Flow or Bitmask DP state transitions.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.network-flow-matching',
    patternSlug: 'network-flow-matching',
    patternTitle: 'Network Flow & Matching',
    questTitle: 'Quest: The Flow Nexus',
    kingdomTitle: 'The Citadel of Masters',
  },

  // 4. Line Sweep & Geometry Algorithms
  {
    id: 'lc-218-adv',
    slug: 'the-skyline-problem-sweep',
    leetcodeNumber: 218,
    title: 'The Skyline Problem (Line Sweep)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Line Sweep', 'Heap', 'Ordered Set'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/the-skyline-problem/',
    notes: 'Line Sweep over building critical points tracking height multiset changes.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.line-sweep-geometry',
    patternSlug: 'line-sweep-geometry',
    patternTitle: 'Line Sweep & Geometry Algorithms',
    questTitle: 'Quest: The Horizon Sweep',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-850',
    slug: 'rectangle-area-ii',
    leetcodeNumber: 850,
    title: 'Rectangle Area II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Segment Tree', 'Line Sweep'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/rectangle-area-ii/',
    notes: '2D Line Sweep with 1D Segment Tree tracking total active y-interval length.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.line-sweep-geometry',
    patternSlug: 'line-sweep-geometry',
    patternTitle: 'Line Sweep & Geometry Algorithms',
    questTitle: 'Quest: The Horizon Sweep',
    kingdomTitle: 'The Citadel of Masters',
  },

  // 5. Heavy-Light Decomposition & Advanced Trees
  {
    id: 'lc-2322',
    slug: 'minimum-score-after-removals-on-a-tree',
    leetcodeNumber: 2322,
    title: 'Minimum Score After Removals on a Tree',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation', 'Tree', 'Depth-First Search'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-score-after-removals-on-a-tree/',
    notes: 'Tree XOR subtree values + ancestral relationship check in O(N^2).',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.heavy-light-advanced-trees',
    patternSlug: 'heavy-light-advanced-trees',
    patternTitle: 'Heavy-Light Decomposition & Advanced Trees',
    questTitle: 'Quest: The Master Oracle',
    kingdomTitle: 'The Citadel of Masters',
  },

  {
    id: 'lc-327',
    slug: 'count-of-range-sum',
    leetcodeNumber: 327,
    title: 'Count of Range Sum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Merge Sort', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/count-of-range-sum/',
    notes: 'Prefix sum array + Merge Sort divide-and-conquer counting lower <= pref[j] - pref[i] <= upper.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-699',
    slug: 'falling-squares',
    leetcodeNumber: 699,
    title: 'Falling Squares',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Segment Tree', 'Ordered Set'],
    companies: ['Uber', 'Google'],
    url: 'https://leetcode.com/problems/falling-squares/',
    notes: 'Segment Tree with lazy propagation or interval coordinate updates.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-715-adv',
    slug: 'range-module',
    leetcodeNumber: 715,
    title: 'Range Module',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Design', 'Segment Tree', 'Ordered Set'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/range-module/',
    notes: 'Dynamic Segment Tree or TreeMap interval merging/splitting.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-732-adv',
    slug: 'my-calendar-iii',
    leetcodeNumber: 732,
    title: 'My Calendar III',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Binary Search', 'Design', 'Segment Tree', 'Ordered Set', 'Prefix Sum'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/my-calendar-iii/',
    notes: 'Sweep line boundary map count accumulation or Dynamic Segment Tree with lazy updates.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.line-sweep-geometry',
    patternSlug: 'line-sweep-geometry',
    patternTitle: 'Line Sweep & Geometry Algorithms',
    questTitle: 'Quest: The Horizon Sweep',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-843',
    slug: 'guess-the-word',
    leetcodeNumber: 843,
    title: 'Guess the Word',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Math', 'String', 'Game Theory', 'Interactive'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/guess-the-word/',
    notes: 'Minimax heuristic word selection filtering candidate list by exact match overlap count.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.heavy-light-advanced-trees',
    patternSlug: 'heavy-light-advanced-trees',
    patternTitle: 'Heavy-Light Decomposition & Advanced Trees',
    questTitle: 'Quest: The Master Oracle',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-1157',
    slug: 'online-majority-element-in-subarray',
    leetcodeNumber: 1157,
    title: 'Online Majority Element In Subarray',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Design', 'Binary Indexed Tree', 'Segment Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/online-majority-element-in-subarray/',
    notes: 'Boyer-Moore Majority Voting inside Segment Tree + Binary Search on element index vectors.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-1649',
    slug: 'create-sorted-array-through-instructions',
    leetcodeNumber: 1649,
    title: 'Create Sorted Array through Instructions',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Merge Sort', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/create-sorted-array-through-instructions/',
    notes: 'BIT sum queries cost min(query(< val), query(> val)).',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-1825-adv',
    slug: 'finding-mk-average',
    leetcodeNumber: 1825,
    title: 'Finding MK Average',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Design', 'Queue', 'Heap', 'Ordered Set', 'Data Stream'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/finding-mk-average/',
    notes: 'Three ordered multisets / Fenwick Tree tracking lower K, middle M-2K, and upper K elements in data stream.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2035',
    slug: 'partition-array-into-two-arrays-to-minimize-sum-difference',
    leetcodeNumber: 2035,
    title: 'Partition Array Into Two Arrays to Minimize Sum Difference',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 20.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Dynamic Programming', 'Bit Manipulation', 'Ordered Set', 'Bitmask'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/',
    notes: 'Meet-in-the-Middle split N into two halves of N/2 elements, generating subset sums by size and binary searching target.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.heavy-light-advanced-trees',
    patternSlug: 'heavy-light-advanced-trees',
    patternTitle: 'Heavy-Light Decomposition & Advanced Trees',
    questTitle: 'Quest: The Master Oracle',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2179',
    slug: 'count-good-triplets-in-an-array',
    leetcodeNumber: 2179,
    title: 'Count Good Triplets in an Array',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Merge Sort', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/count-good-triplets-in-an-array/',
    notes: 'Map nums2 indices to nums1 values + Fenwick Tree tracking elements smaller before and elements larger after.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2286',
    slug: 'booking-concert-tickets-in-groups',
    leetcodeNumber: 2286,
    title: 'Booking Concert Tickets in Groups',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 21.0,
    isPremium: false,
    topics: ['Binary Search', 'Design', 'Binary Indexed Tree', 'Segment Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/booking-concert-tickets-in-groups/',
    notes: 'Segment Tree storing max available seats in row and total sum of available seats in subtree.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2407',
    slug: 'longest-increasing-subsequence-ii',
    leetcodeNumber: 2407,
    title: 'Longest Increasing Subsequence II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 26.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Dynamic Programming', 'Binary Indexed Tree', 'Segment Tree', 'Queue', 'Monotonic Queue'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/longest-increasing-subsequence-ii/',
    notes: 'DP + Segment Tree over values 1..100000 querying max LIS length in range [num - k, num - 1].',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2421',
    slug: 'number-of-good-paths',
    leetcodeNumber: 2421,
    title: 'Number of Good Paths',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Array', 'Tree', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/number-of-good-paths/',
    notes: 'Sort nodes by value and incrementally Union-Find active edges, counting connected components of matching max values.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.heavy-light-advanced-trees',
    patternSlug: 'heavy-light-advanced-trees',
    patternTitle: 'Heavy-Light Decomposition & Advanced Trees',
    questTitle: 'Quest: The Master Oracle',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2569',
    slug: 'handling-sum-queries-after-update',
    leetcodeNumber: 2569,
    title: 'Handling Sum Queries After Update',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 35.0,
    isPremium: false,
    topics: ['Array', 'Segment Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/handling-sum-queries-after-update/',
    notes: 'Segment Tree over nums1 with bit-flip lazy propagation.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-2940',
    slug: 'find-building-where-alice-and-bob-can-meet',
    leetcodeNumber: 2940,
    title: 'Find Building Where Alice and Bob Can Meet',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Stack', 'Binary Indexed Tree', 'Segment Tree', 'Monotonic Stack', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-building-where-alice-and-bob-can-meet/',
    notes: 'Segment Tree over heights range maximum query + binary search for leftmost building > target height.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-3072',
    slug: 'distribute-elements-into-two-arrays-ii',
    leetcodeNumber: 3072,
    title: 'Distribute Elements Into Two Arrays II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 35.0,
    isPremium: false,
    topics: ['Array', 'Binary Indexed Tree', 'Segment Tree', 'Simulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/distribute-elements-into-two-arrays-ii/',
    notes: 'Coordinate compression + 2 Fenwick Trees querying count of strictly greater elements.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-3165',
    slug: 'maximum-sum-of-subsequence-with-non-adjacent-elements',
    leetcodeNumber: 3165,
    title: 'Maximum Sum of Subsequence With Non-adjacent Elements',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 30.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Dynamic Programming', 'Segment Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-sum-of-subsequence-with-non-adjacent-elements/',
    notes: 'Segment Tree node carrying 4 DP values (take/skip first/last element) for dynamic point updates.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.segment-fenwick-trees',
    patternSlug: 'segment-fenwick-trees',
    patternTitle: 'Segment Trees & Binary Indexed Trees (Fenwick)',
    questTitle: 'Quest: The Segment Lattice',
    kingdomTitle: 'The Citadel of Masters',
  },
  {
    id: 'lc-3213',
    slug: 'construct-string-with-minimum-cost',
    leetcodeNumber: 3213,
    title: 'Construct String with Minimum Cost',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 25.0,
    isPremium: false,
    topics: ['Array', 'String', 'Dynamic Programming', 'Suffix Array', 'Trie'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/construct-string-with-minimum-cost/',
    notes: 'Aho-Corasick Automaton / Trie with suffix fail links + 1D DP.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    patternId: 'pattern.advanced-string-matching',
    patternSlug: 'advanced-string-matching',
    patternTitle: 'Advanced String Matching (KMP & Manacher)',
    questTitle: 'Quest: The Lexical Master',
    kingdomTitle: 'The Citadel of Masters',
  },
];
