import { ProblemModel } from '../../types';

export const BACKTRACKING_PROBLEMS: ProblemModel[] = [
  // 1. Subsets & Combinations
  {
    id: 'lc-78',
    slug: 'subsets',
    leetcodeNumber: 78,
    title: 'Subsets',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 76.0,
    isPremium: false,
    topics: ['Array', 'Backtracking', 'Bit Manipulation'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/subsets/',
    notes: 'Power set generation via DFS choice tree (include/exclude).',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.subsets-combinations',
    patternSlug: 'subsets-combinations',
    patternTitle: 'Subsets & Combinations',
    questTitle: 'Quest: The Power Set',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-90',
    slug: 'subsets-ii',
    leetcodeNumber: 90,
    title: 'Subsets II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Backtracking', 'Bit Manipulation'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/subsets-ii/',
    notes: 'Sort array and skip duplicate elements at same depth level.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.subsets-combinations',
    patternSlug: 'subsets-combinations',
    patternTitle: 'Subsets & Combinations',
    questTitle: 'Quest: The Power Set',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-77',
    slug: 'combinations',
    leetcodeNumber: 77,
    title: 'Combinations',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Backtracking'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/combinations/',
    notes: 'Backtracking choosing k numbers out of 1..n.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.subsets-combinations',
    patternSlug: 'subsets-combinations',
    patternTitle: 'Subsets & Combinations',
    questTitle: 'Quest: The Power Set',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-39',
    slug: 'combination-sum',
    leetcodeNumber: 39,
    title: 'Combination Sum',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Array', 'Backtracking'],
    companies: ['Amazon', 'Meta', 'Airbnb'],
    url: 'https://leetcode.com/problems/combination-sum/',
    notes: 'Unbounded element choices reducing target sum.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.subsets-combinations',
    patternSlug: 'subsets-combinations',
    patternTitle: 'Subsets & Combinations',
    questTitle: 'Quest: The Power Set',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-40',
    slug: 'combination-sum-ii',
    leetcodeNumber: 40,
    title: 'Combination Sum II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Backtracking'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/combination-sum-ii/',
    notes: 'Sort candidates and skip duplicate elements at current recursion depth.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.subsets-combinations',
    patternSlug: 'subsets-combinations',
    patternTitle: 'Subsets & Combinations',
    questTitle: 'Quest: The Power Set',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-216',
    slug: 'combination-sum-iii',
    leetcodeNumber: 216,
    title: 'Combination Sum III',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Backtracking'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/combination-sum-iii/',
    notes: 'Choose K distinct numbers from 1..9 summing to N.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.subsets-combinations',
    patternSlug: 'subsets-combinations',
    patternTitle: 'Subsets & Combinations',
    questTitle: 'Quest: The Power Set',
    kingdomTitle: 'The Maze of Choices',
  },

  // 2. Permutations
  {
    id: 'lc-46',
    slug: 'permutations',
    leetcodeNumber: 46,
    title: 'Permutations',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 77.0,
    isPremium: false,
    topics: ['Array', 'Backtracking'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/permutations/',
    notes: 'N! all arrangements via visited boolean array or element swapping.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.permutations',
    patternSlug: 'permutations',
    patternTitle: 'Permutations',
    questTitle: 'Quest: The Permutation Web',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-47',
    slug: 'permutations-ii',
    leetcodeNumber: 47,
    title: 'Permutations II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Backtracking'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/permutations-ii/',
    notes: 'Sort array and skip nums[i] == nums[i-1] when previous identical element unused.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.permutations',
    patternSlug: 'permutations',
    patternTitle: 'Permutations',
    questTitle: 'Quest: The Permutation Web',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-60',
    slug: 'permutation-sequence',
    leetcodeNumber: 60,
    title: 'Permutation Sequence',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Math', 'Recursion'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/permutation-sequence/',
    notes: 'Mathematical factorial representation finding Kth permutation directly.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.permutations',
    patternSlug: 'permutations',
    patternTitle: 'Permutations',
    questTitle: 'Quest: The Permutation Web',
    kingdomTitle: 'The Maze of Choices',
  },

  // 3. Grid & Constraint Backtracking
  {
    id: 'lc-79',
    slug: 'word-search',
    leetcodeNumber: 79,
    title: 'Word Search',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Array', 'String', 'Backtracking', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/word-search/',
    notes: '2D grid character matching DFS with in-place cell visit marking.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.constraint-satisfaction',
    patternSlug: 'constraint-satisfaction',
    patternTitle: 'Grid & Constraint Backtracking',
    questTitle: 'Quest: The Grid Solitaire',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-51',
    slug: 'n-queens',
    leetcodeNumber: 51,
    title: 'N-Queens',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Array', 'Backtracking'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/n-queens/',
    notes: 'Column, main diagonal (r-c), and anti-diagonal (r+c) sets for N-Queens placement.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.constraint-satisfaction',
    patternSlug: 'constraint-satisfaction',
    patternTitle: 'Grid & Constraint Backtracking',
    questTitle: 'Quest: The Grid Solitaire',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-52',
    slug: 'n-queens-ii',
    leetcodeNumber: 52,
    title: 'N-Queens II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 200,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Backtracking'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/n-queens-ii/',
    notes: 'Count valid N-Queens configurations using bitmask / set tracking.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.constraint-satisfaction',
    patternSlug: 'constraint-satisfaction',
    patternTitle: 'Grid & Constraint Backtracking',
    questTitle: 'Quest: The Grid Solitaire',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-37',
    slug: 'sudoku-solver',
    leetcodeNumber: 37,
    title: 'Sudoku Solver',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Backtracking', 'Matrix'],
    companies: ['Uber', 'Google'],
    url: 'https://leetcode.com/problems/sudoku-solver/',
    notes: '9x9 Sudoku constraint satisfaction using row, col, and 3x3 box validity checks.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.constraint-satisfaction',
    patternSlug: 'constraint-satisfaction',
    patternTitle: 'Grid & Constraint Backtracking',
    questTitle: 'Quest: The Grid Solitaire',
    kingdomTitle: 'The Maze of Choices',
  },

  // 4. Partitioning & String Backtracking
  {
    id: 'lc-131',
    slug: 'palindrome-partitioning',
    leetcodeNumber: 131,
    title: 'Palindrome Partitioning',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming', 'Backtracking'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/palindrome-partitioning/',
    notes: 'Backtracking string cuts checking if prefix isPalindrome.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.partitioning-path-backtracking',
    patternSlug: 'partitioning-path-backtracking',
    patternTitle: 'Partitioning & String Backtracking',
    questTitle: 'Quest: The Palindromic Cuts',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-93',
    slug: 'restore-ip-addresses',
    leetcodeNumber: 93,
    title: 'Restore IP Addresses',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['String', 'Backtracking'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/restore-ip-addresses/',
    notes: '4-part string partitioning checking valid octet range 0..255 with no leading zeroes.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.partitioning-path-backtracking',
    patternSlug: 'partitioning-path-backtracking',
    patternTitle: 'Partitioning & String Backtracking',
    questTitle: 'Quest: The Palindromic Cuts',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-17',
    slug: 'letter-combinations-of-a-phone-number',
    leetcodeNumber: 17,
    title: 'Letter Combinations of a Phone Number',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Backtracking'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
    notes: 'Phone digit to letters mapping combination backtracking.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.partitioning-path-backtracking',
    patternSlug: 'partitioning-path-backtracking',
    patternTitle: 'Partitioning & String Backtracking',
    questTitle: 'Quest: The Palindromic Cuts',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-22',
    slug: 'generate-parentheses',
    leetcodeNumber: 22,
    title: 'Generate Parentheses',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming', 'Backtracking'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/generate-parentheses/',
    notes: 'Track open and close count (open < N, close < open).',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.partitioning-path-backtracking',
    patternSlug: 'partitioning-path-backtracking',
    patternTitle: 'Partitioning & String Backtracking',
    questTitle: 'Quest: The Palindromic Cuts',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-212',
    slug: 'word-search-ii',
    leetcodeNumber: 212,
    title: 'Word Search II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Array', 'String', 'Backtracking', 'Trie', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/word-search-ii/',
    notes: 'Combine Trie prefix tree with 2D grid DFS backtracking for multi-word search.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.partitioning-path-backtracking',
    patternSlug: 'partitioning-path-backtracking',
    patternTitle: 'Partitioning & String Backtracking',
    questTitle: 'Quest: The Palindromic Cuts',
    kingdomTitle: 'The Maze of Choices',
  },

  // 5. Advanced Backtracking Puzzles
  {
    id: 'lc-282',
    slug: 'expression-add-operators',
    leetcodeNumber: 282,
    title: 'Expression Add Operators',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['Math', 'String', 'Backtracking'],
    companies: ['Meta', 'Google'],
    url: 'https://leetcode.com/problems/expression-add-operators/',
    notes: 'Backtracking math operators (+, -, *) tracking prevOperand for multiplication precedence.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-301',
    slug: 'remove-invalid-parentheses',
    leetcodeNumber: 301,
    title: 'Remove Invalid Parentheses',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['String', 'Backtracking', 'Breadth-First Search'],
    companies: ['Meta', 'Google'],
    url: 'https://leetcode.com/problems/remove-invalid-parentheses/',
    notes: 'BFS level generation or min removals calculated first + Backtracking.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-473',
    slug: 'matchsticks-to-square',
    leetcodeNumber: 473,
    title: 'Matchsticks to Square',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Backtracking', 'Bit Manipulation', 'Bitmask'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/matchsticks-to-square/',
    notes: 'Sort matchsticks descending + 4-side sum backtracking pruning.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-698',
    slug: 'partition-to-k-equal-sum-subsets',
    leetcodeNumber: 698,
    title: 'Partition to K Equal Sum Subsets',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 42,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Backtracking', 'Bit Manipulation', 'Memoization', 'Bitmask'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/partition-to-k-equal-sum-subsets/',
    notes: 'Generalization of matchsticks to square using K subset sum targets.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-842',
    slug: 'split-array-into-fibonacci-sequence',
    leetcodeNumber: 842,
    title: 'Split Array into Fibonacci Sequence',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['String', 'Backtracking'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/split-array-into-fibonacci-sequence/',
    notes: 'Backtracking string partition verifying num[i] + num[i+1] == num[i+2].',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-306',
    slug: 'additive-number',
    leetcodeNumber: 306,
    title: 'Additive Number',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['String', 'Backtracking'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/additive-number/',
    notes: 'Identical additive sequence check with string big integer addition.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-526',
    slug: 'beautiful-arrangement',
    leetcodeNumber: 526,
    title: 'Beautiful Arrangement',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Backtracking', 'Bit Manipulation', 'Bitmask'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/beautiful-arrangement/',
    notes: 'Permutation backtracking checking pos % val == 0 or val % pos == 0.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-1239',
    slug: 'maximum-length-of-a-concatenated-string-with-unique-characters',
    leetcodeNumber: 1239,
    title: 'Maximum Length of a Concatenated String with Unique Characters',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'String', 'Backtracking', 'Bit Manipulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-length-of-a-concatenated-string-with-unique-characters/',
    notes: 'Bitmask backtracking storing character availability bitmask.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-1255',
    slug: 'maximum-score-words-formed-by-letters',
    leetcodeNumber: 1255,
    title: 'Maximum Score Words Formed by Letters',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array', 'String', 'Backtracking', 'Bit Manipulation', 'Bitmask'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-score-words-formed-by-letters/',
    notes: 'Subset backtracking with character count availability vector.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-1774',
    slug: 'closest-dessert-cost',
    leetcodeNumber: 1774,
    title: 'Closest Dessert Cost',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Backtracking', 'Dynamic Programming'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/closest-dessert-cost/',
    notes: 'Base selection + topping choices (0, 1, or 2 count per topping) DFS.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-1947',
    slug: 'maximum-compatibility-score-sum',
    leetcodeNumber: 1947,
    title: 'Maximum Compatibility Score Sum',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Backtracking', 'Bit Manipulation', 'Bitmask'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-compatibility-score-sum/',
    notes: 'Permutation matching students with mentors to maximize dot product sum.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-2305',
    slug: 'fair-distribution-of-cookies',
    leetcodeNumber: 2305,
    title: 'Fair Distribution of Cookies',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Backtracking', 'Bit Manipulation', 'Bitmask'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/fair-distribution-of-cookies/',
    notes: 'Distribute N cookies to K children minimizing maximum child total.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
  {
    id: 'lc-980',
    slug: 'unique-paths-iii',
    leetcodeNumber: 980,
    title: 'Unique Paths III',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 80.0,
    isPremium: false,
    topics: ['Array', 'Backtracking', 'Bit Manipulation', 'Matrix'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/unique-paths-iii/',
    notes: 'Grid DFS visiting every non-obstacle cell exactly once to reach destination 2.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    patternId: 'pattern.advanced-backtracking-puzzles',
    patternSlug: 'advanced-backtracking-puzzles',
    patternTitle: 'Advanced Backtracking Puzzles',
    questTitle: 'Quest: The Oracle of Subsets',
    kingdomTitle: 'The Maze of Choices',
  },
];
