import { ProblemModel } from '../../types';

export const BASIC_ARRAYS_PROBLEMS: ProblemModel[] = [
  // 1. Array Fundamentals
  {
    id: 'lc-1',
    slug: 'two-sum',
    leetcodeNumber: 1,
    title: 'Two Sum',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 57.6,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Adobe', 'LinkedIn', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/two-sum/',
    notes: 'Classic pair lookup using hash map complement.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-217',
    slug: 'contains-duplicate',
    leetcodeNumber: 217,
    title: 'Contains Duplicate',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 19,
    xp: 50,
    acceptanceRate: 60.6,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['LinkedIn', 'Adobe', 'Salesforce'],
    url: 'https://leetcode.com/problems/contains-duplicate/',
    notes: 'HashSet set lookup for duplicate detection in O(N).',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-448',
    slug: 'find-all-numbers-disappeared-in-an-array',
    leetcodeNumber: 448,
    title: 'Find All Numbers Disappeared in an Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 17,
    xp: 50,
    acceptanceRate: 71.9,
    isPremium: false,
    topics: ['Array'],
    companies: ['Netflix', 'Meta', 'Amazon', 'Adobe'],
    url: 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/',
    notes: 'In-place negation marking for numbers in 1..N.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-485',
    slug: 'max-consecutive-ones',
    leetcodeNumber: 485,
    title: 'Max Consecutive Ones',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['LinkedIn', 'Salesforce', 'Meta'],
    url: 'https://leetcode.com/problems/max-consecutive-ones/',
    notes: 'Track maximum 1-streak counter in single pass.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-66',
    slug: 'plus-one',
    leetcodeNumber: 66,
    title: 'Plus One',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 23,
    xp: 50,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Array', 'Math'],
    companies: ['LinkedIn', 'Bloomberg', 'Apple'],
    url: 'https://leetcode.com/problems/plus-one/',
    notes: 'Simulate digit carry from right to left.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-1929',
    slug: 'concatenation-of-array',
    leetcodeNumber: 1929,
    title: 'Concatenation of Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 21,
    xp: 50,
    acceptanceRate: 55.7,
    isPremium: false,
    topics: ['Array'],
    companies: ['Apple', 'LinkedIn', 'Bloomberg', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/concatenation-of-array/',
    notes: 'Construct 2N array by repeating elements.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-283',
    slug: 'move-zeroes',
    leetcodeNumber: 283,
    title: 'Move Zeroes',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Meta', 'Netflix'],
    url: 'https://leetcode.com/problems/move-zeroes/',
    notes: 'Two-pointer write pointer shift for non-zero items.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-26',
    slug: 'remove-duplicates-from-sorted-array',
    leetcodeNumber: 26,
    title: 'Remove Duplicates from Sorted Array',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 23,
    xp: 50,
    acceptanceRate: 59.6,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Goldman Sachs', 'Salesforce'],
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
    notes: 'Maintain slow pointer for unique in-place writes.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-27',
    slug: 'remove-element',
    leetcodeNumber: 27,
    title: 'Remove Element',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 65.3,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Google', 'Apple', 'Adobe'],
    url: 'https://leetcode.com/problems/remove-element/',
    notes: 'In-place write pointer element filtering.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-88',
    slug: 'merge-sorted-array',
    leetcodeNumber: 88,
    title: 'Merge Sorted Array',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 72.5,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Bloomberg', 'Goldman Sachs', 'LinkedIn'],
    url: 'https://leetcode.com/problems/merge-sorted-array/',
    notes: 'Merge backwards from end of array to avoid overwrites.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-941',
    slug: 'valid-mountain-array',
    leetcodeNumber: 941,
    title: 'Valid Mountain Array',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 21,
    xp: 50,
    acceptanceRate: 62.8,
    isPremium: false,
    topics: ['Array'],
    companies: ['Salesforce', 'Bloomberg', 'Atlassian'],
    url: 'https://leetcode.com/problems/valid-mountain-array/',
    notes: 'Climb up then climb down to validate mountain peak.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-189',
    slug: 'rotate-array',
    leetcodeNumber: 189,
    title: 'Rotate Array',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 31,
    xp: 100,
    acceptanceRate: 56.9,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Oracle', 'Netflix', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/rotate-array/',
    notes: 'Triple array reversal technique for O(1) space rotation.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-380',
    slug: 'insert-delete-getrandom-o1',
    leetcodeNumber: 380,
    title: 'Insert Delete GetRandom O(1)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 34.4,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Design'],
    companies: ['Meta', 'Adobe', 'Uber', 'LinkedIn'],
    url: 'https://leetcode.com/problems/insert-delete-getrandom-o1/',
    notes: 'Combine ArrayList with HashMap for O(1) random deletes.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-287',
    slug: 'find-the-duplicate-number',
    leetcodeNumber: 287,
    title: 'Find the Duplicate Number',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search'],
    companies: ['Meta', 'Atlassian', 'Adobe'],
    url: 'https://leetcode.com/problems/find-the-duplicate-number/',
    notes: 'Floyds Tortoise & Hare cycle detection on array values.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-442',
    slug: 'find-all-duplicates-in-an-array',
    leetcodeNumber: 442,
    title: 'Find All Duplicates in an Array',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 33,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['Microsoft', 'Adobe', 'Salesforce'],
    url: 'https://leetcode.com/problems/find-all-duplicates-in-an-array/',
    notes: 'In-place index sign flipping technique.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-41',
    slug: 'first-missing-positive',
    leetcodeNumber: 41,
    title: 'First Missing Positive',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 54,
    xp: 200,
    acceptanceRate: 29.8,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Microsoft', 'Adobe', 'Google'],
    url: 'https://leetcode.com/problems/first-missing-positive/',
    notes: 'Cyclic sort / index mapping to achieve O(N) time and O(1) space.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-fundamentals',
    patternSlug: 'array-fundamentals',
    patternTitle: 'Array Fundamentals',
    questTitle: 'Quest: The First Steps',
    kingdomTitle: 'Kingdom of Beginnings',
  },

  // 2. Kadane's Algorithm
  {
    id: 'lc-53',
    slug: 'maximum-subarray',
    leetcodeNumber: 53,
    title: 'Maximum Subarray',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 67.7,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Bloomberg', 'Salesforce', 'Microsoft'],
    url: 'https://leetcode.com/problems/maximum-subarray/',
    notes: 'Classic Kadanes local vs global maximum recurrence.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-628',
    slug: 'maximum-product-of-three-numbers',
    leetcodeNumber: 628,
    title: 'Maximum Product of Three Numbers',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 69.2,
    isPremium: false,
    topics: ['Array', 'Math', 'Sorting'],
    companies: ['Microsoft', 'Salesforce'],
    url: 'https://leetcode.com/problems/maximum-product-of-three-numbers/',
    notes: 'Compare product of 3 largest vs 2 smallest negatives * largest positive.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-152',
    slug: 'maximum-product-subarray',
    leetcodeNumber: 152,
    title: 'Maximum Product Subarray',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 31,
    xp: 100,
    acceptanceRate: 50.3,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Atlassian', 'Goldman Sachs', 'Adobe'],
    url: 'https://leetcode.com/problems/maximum-product-subarray/',
    notes: 'Track minProduct and maxProduct simultaneously to handle negative flips.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-918',
    slug: 'maximum-sum-circular-subarray',
    leetcodeNumber: 918,
    title: 'Maximum Sum Circular Subarray',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 52.1,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Queue'],
    companies: ['Oracle', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/maximum-sum-circular-subarray/',
    notes: 'Max circular sum = totalSum - minSubarraySum (handle all-negative edge case).',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-42',
    slug: 'trapping-rain-water',
    leetcodeNumber: 42,
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 47,
    xp: 200,
    acceptanceRate: 37.1,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Stack', 'Dynamic Programming'],
    companies: ['Uber', 'Adobe', 'Bloomberg'],
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    notes: 'Two-pointer inward max-height tracking for O(1) space.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-135',
    slug: 'candy',
    leetcodeNumber: 135,
    title: 'Candy',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 48,
    xp: 200,
    acceptanceRate: 28.0,
    isPremium: false,
    topics: ['Array', 'Greedy'],
    companies: ['Goldman Sachs', 'Apple', 'Meta', 'Salesforce'],
    url: 'https://leetcode.com/problems/candy/',
    notes: 'Two-pass left and right neighbor rating comparisons.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-84',
    slug: 'largest-rectangle-in-histogram',
    leetcodeNumber: 84,
    title: 'Largest Rectangle in Histogram',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 26.1,
    isPremium: false,
    topics: ['Array', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon', 'Microsoft', 'Bloomberg', 'Oracle'],
    url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    notes: 'Monotonic stack boundary expansion.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.kadanes-algorithm',
    patternSlug: 'kadanes-algorithm',
    patternTitle: "Kadane's Algorithm",
    questTitle: 'Quest: The Golden Streak',
    kingdomTitle: 'Kingdom of Beginnings',
  },

  // 3. Array Rearrangement
  {
    id: 'lc-344',
    slug: 'reverse-string',
    leetcodeNumber: 344,
    title: 'Reverse String',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 61.1,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'String'],
    companies: ['Meta', 'Amazon', 'Apple', 'LinkedIn'],
    url: 'https://leetcode.com/problems/reverse-string/',
    notes: 'In-place char array swap pointers.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-rearrangement',
    patternSlug: 'array-rearrangement',
    patternTitle: 'Array Rearrangement',
    questTitle: 'Quest: The Shuffle',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-561',
    slug: 'array-partition',
    leetcodeNumber: 561,
    title: 'Array Partition',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 69.9,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting'],
    companies: ['Microsoft', 'Atlassian', 'LinkedIn'],
    url: 'https://leetcode.com/problems/array-partition/',
    notes: 'Sort and sum alternate elements for max pair minimums.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-rearrangement',
    patternSlug: 'array-rearrangement',
    patternTitle: 'Array Rearrangement',
    questTitle: 'Quest: The Shuffle',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-31',
    slug: 'next-permutation',
    leetcodeNumber: 31,
    title: 'Next Permutation',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 45.9,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['LinkedIn', 'Adobe', 'Oracle'],
    url: 'https://leetcode.com/problems/next-permutation/',
    notes: 'Find pivot, swap next greater, reverse right suffix.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-rearrangement',
    patternSlug: 'array-rearrangement',
    patternTitle: 'Array Rearrangement',
    questTitle: 'Quest: The Shuffle',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-556',
    slug: 'next-greater-element-iii',
    leetcodeNumber: 556,
    title: 'Next Greater Element III',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Math', 'Two Pointers', 'String'],
    companies: ['Bloomberg', 'Oracle', 'Netflix', 'Atlassian'],
    url: 'https://leetcode.com/problems/next-greater-element-iii/',
    notes: 'Digit array permutation algorithm with 32-bit int overflow check.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-rearrangement',
    patternSlug: 'array-rearrangement',
    patternTitle: 'Array Rearrangement',
    questTitle: 'Quest: The Shuffle',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-4',
    slug: 'median-of-two-sorted-arrays',
    leetcodeNumber: 4,
    title: 'Median of Two Sorted Arrays',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 33.1,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer'],
    companies: ['Oracle', 'Amazon', 'Atlassian', 'Apple'],
    url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    notes: 'Binary search partition on smaller array for O(log(min(M,N))).',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-rearrangement',
    patternSlug: 'array-rearrangement',
    patternTitle: 'Array Rearrangement',
    questTitle: 'Quest: The Shuffle',
    kingdomTitle: 'Kingdom of Beginnings',
  },

  // 4. Array Simulation & Design
  {
    id: 'lc-1512',
    slug: 'number-of-good-pairs',
    leetcodeNumber: 1512,
    title: 'Number of Good Pairs',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Math'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/number-of-good-pairs/',
    notes: 'Frequency count combination formula n*(n-1)/2.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-1913',
    slug: 'maximum-product-difference-between-two-pairs',
    leetcodeNumber: 1913,
    title: 'Maximum Product Difference Between Two Pairs',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Sorting'],
    companies: ['Meta', 'Microsoft', 'Adobe'],
    url: 'https://leetcode.com/problems/maximum-product-difference-between-two-pairs/',
    notes: 'Track two largest and two smallest elements.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-1470',
    slug: 'shuffle-the-array',
    leetcodeNumber: 1470,
    title: 'Shuffle the Array',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['Adobe', 'Uber', 'Goldman Sachs', 'Apple'],
    url: 'https://leetcode.com/problems/shuffle-the-array/',
    notes: 'Interleave [x1, x2..] and [y1, y2..] elements.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-1295',
    slug: 'find-numbers-with-even-number-of-digits',
    leetcodeNumber: 1295,
    title: 'Find Numbers with Even Number of Digits',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 24,
    xp: 50,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['Goldman Sachs', 'Apple'],
    url: 'https://leetcode.com/problems/find-numbers-with-even-number-of-digits/',
    notes: 'Count digit length via log10 or string length.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-896',
    slug: 'monotonic-array',
    leetcodeNumber: 896,
    title: 'Monotonic Array',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 50,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['Netflix', 'Bloomberg', 'Atlassian'],
    url: 'https://leetcode.com/problems/monotonic-array/',
    notes: 'Single pass checking non-increasing or non-decreasing flag.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-645',
    slug: 'set-mismatch',
    leetcodeNumber: 645,
    title: 'Set Mismatch',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 69.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Bit Manipulation', 'Sorting'],
    companies: ['Atlassian', 'LinkedIn', 'Salesforce', 'Oracle'],
    url: 'https://leetcode.com/problems/set-mismatch/',
    notes: 'Identify duplicate and missing number in range 1..N.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-1150',
    slug: 'check-if-a-number-is-majority-element-in-a-sorted-array',
    leetcodeNumber: 1150,
    title: 'Check If a Number Is Majority Element in a Sorted Array',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Low',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 56.0,
    isPremium: true,
    topics: ['Array', 'Binary Search'],
    companies: ['Salesforce', 'Oracle'],
    url: 'https://leetcode.com/problems/check-if-a-number-is-majority-element-in-a-sorted-array/',
    notes: 'Binary search first occurrence and check index + N/2 value.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-769',
    slug: 'max-chunks-to-make-sorted',
    leetcodeNumber: 769,
    title: 'Max Chunks To Make Sorted',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Greedy', 'Sorting', 'Monotonic Stack'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/max-chunks-to-make-sorted/',
    notes: 'Track max maxSoFar == index for partition boundary.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-915',
    slug: 'partition-array-into-disjoint-intervals',
    leetcodeNumber: 915,
    title: 'Partition Array into Disjoint Intervals',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['Meta', 'Microsoft', 'Adobe', 'Uber'],
    url: 'https://leetcode.com/problems/partition-array-into-disjoint-intervals/',
    notes: 'Single pass prefix max tracking for disjoint left partition.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-926',
    slug: 'flip-string-to-monotone-increasing',
    leetcodeNumber: 926,
    title: 'Flip String to Monotone Increasing',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Adobe', 'Uber'],
    url: 'https://leetcode.com/problems/flip-string-to-monotone-increasing/',
    notes: 'Dynamic count of ones vs flip operations.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-611',
    slug: 'valid-triangle-number',
    leetcodeNumber: 611,
    title: 'Valid Triangle Number',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Greedy', 'Sorting'],
    companies: ['Goldman Sachs', 'Apple', 'Netflix'],
    url: 'https://leetcode.com/problems/valid-triangle-number/',
    notes: 'Sort array and apply two-pointer reverse scan for a+b > c.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-945',
    slug: 'minimum-increment-to-make-array-unique',
    leetcodeNumber: 945,
    title: 'Minimum Increment to Make Array Unique',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting', 'Counting'],
    companies: ['Netflix', 'Bloomberg', 'Atlassian', 'LinkedIn'],
    url: 'https://leetcode.com/problems/minimum-increment-to-make-array-unique/',
    notes: 'Sort array and greedily increment elements to max(curr, prev + 1).',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-670',
    slug: 'maximum-swap',
    leetcodeNumber: 670,
    title: 'Maximum Swap',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Math', 'Greedy'],
    companies: ['Atlassian', 'LinkedIn'],
    url: 'https://leetcode.com/problems/maximum-swap/',
    notes: 'Track last occurrences of digits 0-9 to swap max available digit.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
  {
    id: 'lc-768',
    slug: 'max-chunks-to-make-sorted-ii',
    leetcodeNumber: 768,
    title: 'Max Chunks To Make Sorted II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 54,
    xp: 200,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Greedy', 'Sorting', 'Monotonic Stack'],
    companies: ['Salesforce', 'Oracle', 'Google'],
    url: 'https://leetcode.com/problems/max-chunks-to-make-sorted-ii/',
    notes: 'Prefix max array vs suffix min array comparison.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Basic Arrays',
    patternId: 'pattern.array-simulation-design',
    patternSlug: 'array-simulation-design',
    patternTitle: 'Array Simulation & Design',
    questTitle: 'Quest: The Living Grid',
    kingdomTitle: 'Kingdom of Beginnings',
  },
];
