import { ProblemModel } from '../../types';

export const BINARY_SEARCH_TREES_PROBLEMS: ProblemModel[] = [
  // 1. BST Fundamentals & Validation
  {
    id: 'lc-700',
    slug: 'search-in-a-binary-search-tree',
    leetcodeNumber: 700,
    title: 'Search in a Binary Search Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 77.0,
    isPremium: false,
    topics: ['Tree', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/search-in-a-binary-search-tree/',
    notes: 'Compare val with node.val to move left or right in log(N) average time.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-fundamentals',
    patternSlug: 'bst-fundamentals',
    patternTitle: 'BST Fundamentals & Validation',
    questTitle: 'Quest: The Inorder Order',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-98',
    slug: 'validate-binary-search-tree',
    leetcodeNumber: 98,
    title: 'Validate Binary Search Tree',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 32.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/validate-binary-search-tree/',
    notes: 'DFS carrying valid range min < val < max bound constraints.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-fundamentals',
    patternSlug: 'bst-fundamentals',
    patternTitle: 'BST Fundamentals & Validation',
    questTitle: 'Quest: The Inorder Order',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-701',
    slug: 'insert-into-a-binary-search-tree',
    leetcodeNumber: 701,
    title: 'Insert into a Binary Search Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['Tree', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/',
    notes: 'Navigate to appropriate null leaf position and attach new TreeNode(val).',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-fundamentals',
    patternSlug: 'bst-fundamentals',
    patternTitle: 'BST Fundamentals & Validation',
    questTitle: 'Quest: The Inorder Order',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-450',
    slug: 'delete-node-in-a-bst',
    leetcodeNumber: 450,
    title: 'Delete Node in a BST',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Tree', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/delete-node-in-a-bst/',
    notes: 'Handle 0, 1, and 2 children cases using inorder successor / predecessor substitution.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-fundamentals',
    patternSlug: 'bst-fundamentals',
    patternTitle: 'BST Fundamentals & Validation',
    questTitle: 'Quest: The Inorder Order',
    kingdomTitle: 'The Ordered Grove',
  },

  // 2. BST Traversal & Order Statistics
  {
    id: 'lc-230',
    slug: 'kth-smallest-element-in-a-bst',
    leetcodeNumber: 230,
    title: 'Kth Smallest Element in a BST',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Uber'],
    url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
    notes: 'Inorder traversal decrementing K to zero.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-traversal-order',
    patternSlug: 'bst-traversal-order',
    patternTitle: 'BST Traversal & Order Statistics',
    questTitle: 'Quest: The Sorted Canopy',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-501',
    slug: 'find-mode-in-binary-search-tree',
    leetcodeNumber: 501,
    title: 'Find Mode in Binary Search Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-mode-in-binary-search-tree/',
    notes: 'Inorder traversal tracking current count and max count for O(1) extra space.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-traversal-order',
    patternSlug: 'bst-traversal-order',
    patternTitle: 'BST Traversal & Order Statistics',
    questTitle: 'Quest: The Sorted Canopy',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-530',
    slug: 'minimum-absolute-difference-in-bst',
    leetcodeNumber: 530,
    title: 'Minimum Absolute Difference in BST',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-absolute-difference-in-bst/',
    notes: 'Inorder traversal tracking min difference between adjacent node values.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-traversal-order',
    patternSlug: 'bst-traversal-order',
    patternTitle: 'BST Traversal & Order Statistics',
    questTitle: 'Quest: The Sorted Canopy',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-783',
    slug: 'minimum-distance-between-bst-nodes',
    leetcodeNumber: 783,
    title: 'Minimum Distance Between BST Nodes',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-distance-between-bst-nodes/',
    notes: 'Identical logic to 530 using inorder node comparison.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-traversal-order',
    patternSlug: 'bst-traversal-order',
    patternTitle: 'BST Traversal & Order Statistics',
    questTitle: 'Quest: The Sorted Canopy',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-173',
    slug: 'binary-search-tree-iterator',
    leetcodeNumber: 173,
    title: 'Binary Search Tree Iterator',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Stack', 'Tree', 'Design', 'Binary Search Tree', 'Binary Tree', 'Iterator'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/binary-search-tree-iterator/',
    notes: 'Controlled stack inorder traversal for O(h) memory next() and hasNext().',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-traversal-order',
    patternSlug: 'bst-traversal-order',
    patternTitle: 'BST Traversal & Order Statistics',
    questTitle: 'Quest: The Sorted Canopy',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-285',
    slug: 'inorder-successor-in-bst',
    leetcodeNumber: 285,
    title: 'Inorder Successor in BST',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 48.0,
    isPremium: true,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/inorder-successor-in-bst/',
    notes: 'If node.right exists find min in right subtree; else track candidate during root search.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-traversal-order',
    patternSlug: 'bst-traversal-order',
    patternTitle: 'BST Traversal & Order Statistics',
    questTitle: 'Quest: The Sorted Canopy',
    kingdomTitle: 'The Ordered Grove',
  },

  // 3. LCA & Structural BST
  {
    id: 'lc-235',
    slug: 'lowest-common-ancestor-of-a-binary-search-tree',
    leetcodeNumber: 235,
    title: 'Lowest Common Ancestor of a Binary Search Tree',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    notes: 'If both p and q < root go left; if both > root go right; else root is LCA.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.lca-structural-bst',
    patternSlug: 'lca-structural-bst',
    patternTitle: 'LCA & Structural BST',
    questTitle: 'Quest: The Rooted Ancestor',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-108',
    slug: 'convert-sorted-array-to-binary-search-tree',
    leetcodeNumber: 108,
    title: 'Convert Sorted Array to Binary Search Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Tree', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/',
    notes: 'Pick mid as root, recurse left half for left subtree and right half for right subtree.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.lca-structural-bst',
    patternSlug: 'lca-structural-bst',
    patternTitle: 'LCA & Structural BST',
    questTitle: 'Quest: The Rooted Ancestor',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-109',
    slug: 'convert-sorted-list-to-binary-search-tree',
    leetcodeNumber: 109,
    title: 'Convert Sorted List to Binary Search Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Linked List', 'Divide and Conquer', 'Tree', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/',
    notes: 'Fast/slow pointer to find mid node or inorder simulation via global head pointer.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.lca-structural-bst',
    patternSlug: 'lca-structural-bst',
    patternTitle: 'LCA & Structural BST',
    questTitle: 'Quest: The Rooted Ancestor',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1382',
    slug: 'balance-a-binary-search-tree',
    leetcodeNumber: 1382,
    title: 'Balance a Binary Search Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 80.0,
    isPremium: false,
    topics: ['Divide and Conquer', 'Greedy', 'Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/balance-a-binary-search-tree/',
    notes: 'Inorder array dump then rebuild height balanced BST via mid element recursion.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.lca-structural-bst',
    patternSlug: 'lca-structural-bst',
    patternTitle: 'LCA & Structural BST',
    questTitle: 'Quest: The Rooted Ancestor',
    kingdomTitle: 'The Ordered Grove',
  },

  // 4. BST Modification & Range Queries
  {
    id: 'lc-938',
    slug: 'range-sum-of-bst',
    leetcodeNumber: 938,
    title: 'Range Sum of BST',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 86.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/range-sum-of-bst/',
    notes: 'Pruned DFS traversal accumulating values within range [low, high].',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-669',
    slug: 'trim-a-binary-search-tree',
    leetcodeNumber: 669,
    title: 'Trim a Binary Search Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/trim-a-binary-search-tree/',
    notes: 'Recursive trimming: if val < low return trim(right); if val > high return trim(left).',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-538',
    slug: 'convert-bst-to-greater-tree',
    leetcodeNumber: 538,
    title: 'Convert BST to Greater Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/convert-bst-to-greater-tree/',
    notes: 'Reverse inorder traversal (Right -> Root -> Left) carrying sum accumulation.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1038',
    slug: 'binary-search-tree-to-greater-sum-tree',
    leetcodeNumber: 1038,
    title: 'Binary Search Tree to Greater Sum Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 85.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/binary-search-tree-to-greater-sum-tree/',
    notes: 'Identical logic to 538 using reverse inorder traversal.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-449',
    slug: 'serialize-and-deserialize-bst',
    leetcodeNumber: 449,
    title: 'Serialize and Deserialize BST',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['String', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Design', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/serialize-and-deserialize-bst/',
    notes: 'Preorder traversal string without null markers reconstructed using BST min/max bounds.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1373',
    slug: 'maximum-sum-bst-in-binary-tree',
    leetcodeNumber: 1373,
    title: 'Maximum Sum BST in Binary Tree',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Dynamic Programming', 'Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/',
    notes: 'DFS postorder returning tuple (isBST, minVal, maxVal, sumVal).',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-270',
    slug: 'closest-binary-search-tree-value',
    leetcodeNumber: 270,
    title: 'Closest Binary Search Tree Value',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 50.0,
    isPremium: true,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/closest-binary-search-tree-value/',
    notes: 'Iterative BST search tracking min difference to target double.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-272',
    slug: 'closest-binary-search-tree-value-ii',
    leetcodeNumber: 272,
    title: 'Closest Binary Search Tree Value II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 58.0,
    isPremium: true,
    topics: ['Two Pointers', 'Stack', 'Tree', 'Depth-First Search', 'Binary Search Tree', 'Heap', 'Binary Tree'],
    companies: ['Meta', 'LinkedIn'],
    url: 'https://leetcode.com/problems/closest-binary-search-tree-value-ii/',
    notes: 'Inorder traversal with sliding window Queue of size K or double predecessor/successor stacks.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1008',
    slug: 'construct-binary-search-tree-from-preorder-traversal',
    leetcodeNumber: 1008,
    title: 'Construct Binary Search Tree from Preorder Traversal',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 81.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Tree', 'Binary Search Tree', 'Monotonic Stack', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/',
    notes: 'Recursion with upper bound constraint or Monotonic Stack O(N).',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1569',
    slug: 'number-of-ways-to-reorder-array-to-get-same-bst',
    leetcodeNumber: 1569,
    title: 'Number of Ways to Reorder Array to Get Same BST',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Divide and Conquer', 'Dynamic Programming', 'Tree', 'Union-Find', 'Binary Search Tree', 'Combinatorics', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-ways-to-reorder-array-to-get-same-bst/',
    notes: 'Pascal triangle combinations C(leftLen + rightLen, leftLen) * ways(left) * ways(right).',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1305',
    slug: 'all-elements-in-two-binary-search-trees',
    leetcodeNumber: 1305,
    title: 'All Elements in Two Binary Search Trees',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 79.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Sorting', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/all-elements-in-two-binary-search-trees/',
    notes: 'Iterative inorder traversal on both BSTs simultaneously merging two sorted streams.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
  {
    id: 'lc-1214',
    slug: 'two-sum-bsts',
    leetcodeNumber: 1214,
    title: 'Two Sum BSTs',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Low',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: true,
    topics: ['Two Pointers', 'Binary Search', 'Stack', 'Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/two-sum-bsts/',
    notes: 'Traverse BST1 and binary search target - val in BST2 or double stack traversal.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Trees',
    patternId: 'pattern.bst-modification',
    patternSlug: 'bst-modification',
    patternTitle: 'BST Modification & Range Queries',
    questTitle: 'Quest: The Pruned Grove',
    kingdomTitle: 'The Ordered Grove',
  },
];
