import { ProblemModel } from '../../types';

export const BINARY_TREES_PROBLEMS: ProblemModel[] = [
  // 1. Tree Traversal (DFS/BFS)
  {
    id: 'lc-94',
    slug: 'binary-tree-inorder-traversal',
    leetcodeNumber: 94,
    title: 'Binary Tree Inorder Traversal',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['Stack', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/binary-tree-inorder-traversal/',
    notes: 'Inorder (Left, Root, Right) DFS recursion or stack.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-144',
    slug: 'binary-tree-preorder-traversal',
    leetcodeNumber: 144,
    title: 'Binary Tree Preorder Traversal',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Stack', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/binary-tree-preorder-traversal/',
    notes: 'Preorder (Root, Left, Right) DFS recursion or stack.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-145',
    slug: 'binary-tree-postorder-traversal',
    leetcodeNumber: 145,
    title: 'Binary Tree Postorder Traversal',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Stack', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/binary-tree-postorder-traversal/',
    notes: 'Postorder (Left, Right, Root) DFS recursion or stack.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-103',
    slug: 'binary-tree-zigzag-level-order-traversal',
    leetcodeNumber: 103,
    title: 'Binary Tree Zigzag Level Order Traversal',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Tree', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/',
    notes: 'Queue BFS with boolean flag reversing odd level collections.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-107',
    slug: 'binary-tree-level-order-traversal-ii',
    leetcodeNumber: 107,
    title: 'Binary Tree Level Order Traversal II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Tree', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/binary-tree-level-order-traversal-ii/',
    notes: 'Level order queue BFS pushing rows to result list in reverse (bottom-up).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-114',
    slug: 'flatten-binary-tree-to-linked-list',
    leetcodeNumber: 114,
    title: 'Flatten Binary Tree to Linked List',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Linked List', 'Stack', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/',
    notes: 'Reverse postorder traversal (Right -> Left -> Root) setting root.right = prev.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-99',
    slug: 'recover-binary-search-tree',
    leetcodeNumber: 99,
    title: 'Recover Binary Search Tree',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/recover-binary-search-tree/',
    notes: 'Inorder traversal tracking swapped pair nodes (first, second, prev).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-traversal',
    patternSlug: 'tree-traversal',
    patternTitle: 'Tree Traversal (DFS/BFS)',
    questTitle: 'Quest: The Canopy Path',
    kingdomTitle: 'The Branching Woods',
  },

  // 2. Recursive Tree Properties
  {
    id: 'lc-104',
    slug: 'maximum-depth-of-binary-tree',
    leetcodeNumber: 104,
    title: 'Maximum Depth of Binary Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    notes: '1 + max(maxDepth(left), maxDepth(right)).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-111',
    slug: 'minimum-depth-of-binary-tree',
    leetcodeNumber: 111,
    title: 'Minimum Depth of Binary Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/minimum-depth-of-binary-tree/',
    notes: 'BFS first leaf node level return or DFS taking min non-null child depth.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-100',
    slug: 'same-tree',
    leetcodeNumber: 100,
    title: 'Same Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/same-tree/',
    notes: 'Recursive node structural and value equivalence check.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-101',
    slug: 'symmetric-tree',
    leetcodeNumber: 101,
    title: 'Symmetric Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/symmetric-tree/',
    notes: 'Mirror check isMirror(t1.left, t2.right) && isMirror(t1.right, t2.left).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-110',
    slug: 'balanced-binary-tree',
    leetcodeNumber: 110,
    title: 'Balanced Binary Tree',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/balanced-binary-tree/',
    notes: 'Bottom-up height function returning -1 if abs(leftH - rightH) > 1.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-226',
    slug: 'invert-binary-tree',
    leetcodeNumber: 226,
    title: 'Invert Binary Tree',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/invert-binary-tree/',
    notes: 'Swap root.left and root.right recursively.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-543',
    slug: 'diameter-of-binary-tree',
    leetcodeNumber: 543,
    title: 'Diameter of Binary Tree',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/diameter-of-binary-tree/',
    notes: 'Track max(leftHeight + rightHeight) across all subtrees during depth calculation.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-572',
    slug: 'subtree-of-another-tree',
    leetcodeNumber: 572,
    title: 'Subtree of Another Tree',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'String Matching', 'Binary Tree', 'Hash Function'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/subtree-of-another-tree/',
    notes: 'Check isSameTree(root, subRoot) || isSubtree(root.left, subRoot) || isSubtree(root.right, subRoot).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-124',
    slug: 'binary-tree-maximum-path-sum',
    leetcodeNumber: 124,
    title: 'Binary Tree Maximum Path Sum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['Dynamic Programming', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    notes: 'Track global max(leftGain + rightGain + node.val) returning max single branch gain.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.recursive-tree-properties',
    patternSlug: 'recursive-tree-properties',
    patternTitle: 'Recursive Tree Properties',
    questTitle: 'Quest: The Ancient Roots',
    kingdomTitle: 'The Branching Woods',
  },

  // 3. Tree Construction & Serialization
  {
    id: 'lc-105',
    slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
    leetcodeNumber: 105,
    title: 'Construct Binary Tree from Preorder and Inorder Traversal',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Divide and Conquer', 'Tree', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
    notes: 'Root from preorder, divide inorder using HashMap index lookups.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-construction',
    patternSlug: 'tree-construction',
    patternTitle: 'Tree Construction & Serialization',
    questTitle: 'Quest: The Architect of Branches',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-106',
    slug: 'construct-binary-tree-from-inorder-and-postorder-traversal',
    leetcodeNumber: 106,
    title: 'Construct Binary Tree from Inorder and Postorder Traversal',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Divide and Conquer', 'Tree', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/',
    notes: 'Root from end of postorder array, divide inorder subranges.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-construction',
    patternSlug: 'tree-construction',
    patternTitle: 'Tree Construction & Serialization',
    questTitle: 'Quest: The Architect of Branches',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-654',
    slug: 'maximum-binary-tree',
    leetcodeNumber: 654,
    title: 'Maximum Binary Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 85.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Stack', 'Tree', 'Monotonic Stack', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-binary-tree/',
    notes: 'Pick max element as root, recurse left and right subarrays or Monotonic Stack O(N).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-construction',
    patternSlug: 'tree-construction',
    patternTitle: 'Tree Construction & Serialization',
    questTitle: 'Quest: The Architect of Branches',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-297',
    slug: 'serialize-and-deserialize-binary-tree',
    leetcodeNumber: 297,
    title: 'Serialize and Deserialize Binary Tree',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['String', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Design', 'Binary Tree'],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
    notes: 'Preorder string serialization with null delimiters and queue deserialization.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-construction',
    patternSlug: 'tree-construction',
    patternTitle: 'Tree Construction & Serialization',
    questTitle: 'Quest: The Architect of Branches',
    kingdomTitle: 'The Branching Woods',
  },

  // 4. Root-to-Leaf Path Analysis
  {
    id: 'lc-112',
    slug: 'path-sum',
    leetcodeNumber: 112,
    title: 'Path Sum',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/path-sum/',
    notes: 'DFS root-to-leaf path targetSum - root.val comparison.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.root-to-leaf-paths',
    patternSlug: 'root-to-leaf-paths',
    patternTitle: 'Root-to-Leaf Path Analysis',
    questTitle: 'Quest: The Root Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-257',
    slug: 'binary-tree-paths',
    leetcodeNumber: 257,
    title: 'Binary Tree Paths',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['String', 'Backtracking', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/binary-tree-paths/',
    notes: 'Collect all root-to-leaf paths as string representations "root->left->leaf".',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.root-to-leaf-paths',
    patternSlug: 'root-to-leaf-paths',
    patternTitle: 'Root-to-Leaf Path Analysis',
    questTitle: 'Quest: The Root Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-113',
    slug: 'path-sum-ii',
    leetcodeNumber: 113,
    title: 'Path Sum II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Backtracking', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/path-sum-ii/',
    notes: 'Backtracking path list collecting all root-to-leaf paths summing to target.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.root-to-leaf-paths',
    patternSlug: 'root-to-leaf-paths',
    patternTitle: 'Root-to-Leaf Path Analysis',
    questTitle: 'Quest: The Root Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-437',
    slug: 'path-sum-iii',
    leetcodeNumber: 437,
    title: 'Path Sum III',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/path-sum-iii/',
    notes: 'Prefix sum HashMap tracking counts of sub-paths ending at current node.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.root-to-leaf-paths',
    patternSlug: 'root-to-leaf-paths',
    patternTitle: 'Root-to-Leaf Path Analysis',
    questTitle: 'Quest: The Root Path',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-129',
    slug: 'sum-root-to-leaf-numbers',
    leetcodeNumber: 129,
    title: 'Sum Root to Leaf Numbers',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/sum-root-to-leaf-numbers/',
    notes: 'Accumulate currSum = currSum * 10 + node.val along root-to-leaf paths.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.root-to-leaf-paths',
    patternSlug: 'root-to-leaf-paths',
    patternTitle: 'Root-to-Leaf Path Analysis',
    questTitle: 'Quest: The Root Path',
    kingdomTitle: 'The Branching Woods',
  },

  // 5. Tree Views & Level Projections
  {
    id: 'lc-199',
    slug: 'binary-tree-right-side-view',
    leetcodeNumber: 199,
    title: 'Binary Tree Right Side View',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/binary-tree-right-side-view/',
    notes: 'BFS level order taking last element or Root-Right-Left DFS depth tracking.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-314',
    slug: 'binary-tree-vertical-order-traversal',
    leetcodeNumber: 314,
    title: 'Binary Tree Vertical Order Traversal',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: true,
    topics: ['Hash Table', 'Tree', 'Breadth-First Search', 'Sorting', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/binary-tree-vertical-order-traversal/',
    notes: 'BFS with column index tracking (col - 1 for left, col + 1 for right).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-987',
    slug: 'vertical-order-traversal-of-a-binary-tree',
    leetcodeNumber: 987,
    title: 'Vertical Order Traversal of a Binary Tree',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Hash Table', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Sorting', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/',
    notes: 'Store tuples (col, row, val), sort by col asc, row asc, val asc.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-662',
    slug: 'maximum-width-of-binary-tree',
    leetcodeNumber: 662,
    title: 'Maximum Width of Binary Tree',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/maximum-width-of-binary-tree/',
    notes: 'BFS with heap indexing (2*i and 2*i+1) normalized per level to avoid overflow.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },

  {
    id: 'lc-236',
    slug: 'lowest-common-ancestor-of-a-binary-tree',
    leetcodeNumber: 236,
    title: 'Lowest Common Ancestor of a Binary Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
    notes: 'DFS return node if matches p or q; LCA is node where left and right both non-null.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-1650',
    slug: 'lowest-common-ancestor-of-a-binary-tree-iii',
    leetcodeNumber: 1650,
    title: 'Lowest Common Ancestor of a Binary Tree III',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 78.0,
    isPremium: true,
    topics: ['Hash Table', 'Two Pointers', 'Tree', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-iii/',
    notes: 'Node has parent pointer; convert to Intersection of Two Linked Lists.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-865',
    slug: 'smallest-subtree-with-all-the-deepest-nodes',
    leetcodeNumber: 865,
    title: 'Smallest Subtree with all the Deepest Nodes',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 71.0,
    isPremium: false,
    topics: ['Hash Table', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/smallest-subtree-with-all-the-deepest-nodes/',
    notes: 'DFS postorder returning pair (depth, node).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-1123',
    slug: 'lowest-common-ancestor-of-deepest-leaves',
    leetcodeNumber: 1123,
    title: 'Lowest Common Ancestor of Deepest Leaves',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 71.0,
    isPremium: false,
    topics: ['Hash Table', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-deepest-leaves/',
    notes: 'Identical logic to 865 finding LCA of maximum depth leaves.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-116',
    slug: 'populating-next-right-pointers-in-each-node',
    leetcodeNumber: 116,
    title: 'Populating Next Right Pointers in Each Node',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/',
    notes: 'O(1) space level pointer traversal node.left.next = node.right.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-117',
    slug: 'populating-next-right-pointers-in-each-node-ii',
    leetcodeNumber: 117,
    title: 'Populating Next Right Pointers in Each Node II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/',
    notes: 'Use dummy head for next level linked list O(1) space.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-951',
    slug: 'flip-equivalent-binary-trees',
    leetcodeNumber: 951,
    title: 'Flip Equivalent Binary Trees',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/flip-equivalent-binary-trees/',
    notes: 'Recursive check matching (left1, left2) & (right1, right2) OR (left1, right2) & (right1, left2).',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-988',
    slug: 'smallest-string-starting-from-leaf',
    leetcodeNumber: 988,
    title: 'Smallest String Starting From Leaf',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['String', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/smallest-string-starting-from-leaf/',
    notes: 'DFS leaf-to-root string accumulation comparing lexically smallest string.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-1372',
    slug: 'longest-zigzag-path-in-a-binary-tree',
    leetcodeNumber: 1372,
    title: 'Longest ZigZag Path in a Binary Tree',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Dynamic Programming', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree/',
    notes: 'DFS carrying direction flag (isLeft) and current length score.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
  {
    id: 'lc-1609',
    slug: 'even-odd-tree',
    leetcodeNumber: 1609,
    title: 'Even Odd Tree',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Tree', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/even-odd-tree/',
    notes: 'BFS level order verifying even level odd values strictly increasing and vice-versa.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Trees',
    patternId: 'pattern.tree-views-levels',
    patternSlug: 'tree-views-levels',
    patternTitle: 'Tree Views & Level Projections',
    questTitle: 'Quest: The Solar Projection',
    kingdomTitle: 'The Branching Woods',
  },
];
