import { ProblemModel } from '../../types';

export const BINARY_SEARCH_PROBLEMS: ProblemModel[] = [
  // 1. Classic Binary Search
  {
    id: 'lc-704',
    slug: 'binary-search',
    leetcodeNumber: 704,
    title: 'Binary Search',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 17,
    xp: 50,
    acceptanceRate: 70.4,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Amazon', 'Meta', 'Salesforce', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/binary-search/',
    notes: 'Standard log(N) array binary search.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-35',
    slug: 'search-insert-position',
    leetcodeNumber: 35,
    title: 'Search Insert Position',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 19,
    xp: 50,
    acceptanceRate: 65.5,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Salesforce', 'Apple', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/search-insert-position/',
    notes: 'Lower bound binary search returning low index.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-374',
    slug: 'guess-number-higher-or-lower',
    leetcodeNumber: 374,
    title: 'Guess Number Higher or Lower',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 55.2,
    isPremium: false,
    topics: ['Binary Search', 'Interactive'],
    companies: ['Apple', 'Netflix', 'Salesforce'],
    url: 'https://leetcode.com/problems/guess-number-higher-or-lower/',
    notes: 'Interactive API lower/higher binary search range reduction.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-278',
    slug: 'first-bad-version',
    leetcodeNumber: 278,
    title: 'First Bad Version',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 24,
    xp: 50,
    acceptanceRate: 78.0,
    isPremium: false,
    topics: ['Binary Search', 'Interactive'],
    companies: ['LinkedIn', 'Atlassian'],
    url: 'https://leetcode.com/problems/first-bad-version/',
    notes: 'First true binary search condition check.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-34',
    slug: 'find-first-and-last-position-of-element-in-sorted-array',
    leetcodeNumber: 34,
    title: 'Find First and Last Position of Element in Sorted Array',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 27,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Apple', 'Meta', 'Uber'],
    url: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
    notes: 'Lower bound and upper bound binary search passes.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-74',
    slug: 'search-a-2d-matrix',
    leetcodeNumber: 74,
    title: 'Search a 2D Matrix',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 29,
    xp: 100,
    acceptanceRate: 56.3,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Matrix'],
    companies: ['Goldman Sachs', 'Oracle'],
    url: 'https://leetcode.com/problems/search-a-2d-matrix/',
    notes: 'Flatten 2D grid index mid to row = mid / cols, col = mid % cols.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-162',
    slug: 'find-peak-element',
    leetcodeNumber: 162,
    title: 'Find Peak Element',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/find-peak-element/',
    notes: 'Binary search over local slope nums[mid] < nums[mid+1].',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.classic-binary-search',
    patternSlug: 'classic-binary-search',
    patternTitle: 'Classic Binary Search',
    questTitle: 'Quest: The Straight Line',
    kingdomTitle: 'The Hidden Truth',
  },

  // 2. Binary Search on Rotated Arrays
  {
    id: 'lc-153',
    slug: 'find-minimum-in-rotated-sorted-array',
    leetcodeNumber: 153,
    title: 'Find Minimum in Rotated Sorted Array',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Meta', 'Amazon', 'Google', 'Apple'],
    url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
    notes: 'Compare nums[mid] with nums[right] to find unsorted pivot half.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.rotated-binary-search',
    patternSlug: 'rotated-binary-search',
    patternTitle: 'Binary Search on Rotated Arrays',
    questTitle: 'Quest: The Twisted Path',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-33',
    slug: 'search-in-rotated-sorted-array',
    leetcodeNumber: 33,
    title: 'Search in Rotated Sorted Array',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    notes: 'Check which half is sorted then decide if target lies inside it.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.rotated-binary-search',
    patternSlug: 'rotated-binary-search',
    patternTitle: 'Binary Search on Rotated Arrays',
    questTitle: 'Quest: The Twisted Path',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-81',
    slug: 'search-in-rotated-sorted-array-ii',
    leetcodeNumber: 81,
    title: 'Search in Rotated Sorted Array II',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/',
    notes: 'Handle duplicates by shrinking left++ and right-- when nums[left]==nums[mid]==nums[right].',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.rotated-binary-search',
    patternSlug: 'rotated-binary-search',
    patternTitle: 'Binary Search on Rotated Arrays',
    questTitle: 'Quest: The Twisted Path',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-154',
    slug: 'find-minimum-in-rotated-sorted-array-ii',
    leetcodeNumber: 154,
    title: 'Find Minimum in Rotated Sorted Array II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/',
    notes: 'Handle duplicate pivot values degrading worst-case to O(N).',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.rotated-binary-search',
    patternSlug: 'rotated-binary-search',
    patternTitle: 'Binary Search on Rotated Arrays',
    questTitle: 'Quest: The Twisted Path',
    kingdomTitle: 'The Hidden Truth',
  },

  // 3. Binary Search on Answer
  {
    id: 'lc-852',
    slug: 'peak-index-in-a-mountain-array',
    leetcodeNumber: 852,
    title: 'Peak Index in a Mountain Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/peak-index-in-a-mountain-array/',
    notes: 'Binary search for peak index where arr[mid] > arr[mid+1].',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-875',
    slug: 'koko-eating-bananas',
    leetcodeNumber: 875,
    title: 'Koko Eating Bananas',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Google', 'Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/koko-eating-bananas/',
    notes: 'Binary search speed range 1..max(piles) with feasibility function.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1011',
    slug: 'capacity-to-ship-packages-within-d-days',
    leetcodeNumber: 1011,
    title: 'Capacity To Ship Packages Within D Days',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',
    notes: 'Binary search capacity range max(weight)..sum(weights).',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-378',
    slug: 'kth-smallest-element-in-a-sorted-matrix',
    leetcodeNumber: 378,
    title: 'Kth Smallest Element in a Sorted Matrix',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Sorting', 'Heap', 'Matrix'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/',
    notes: 'Binary search value range matrix[0][0]..matrix[n-1][n-1] counting elements <= mid.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1300',
    slug: 'sum-of-mutated-array-closest-to-target',
    leetcodeNumber: 1300,
    title: 'Sum of Mutated Array Closest to Target',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/sum-of-mutated-array-closest-to-target/',
    notes: 'Binary search capped integer value to minimize sum diff.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-410',
    slug: 'split-array-largest-sum',
    leetcodeNumber: 410,
    title: 'Split Array Largest Sum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Dynamic Programming', 'Greedy', 'Prefix Sum'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/split-array-largest-sum/',
    notes: 'Binary search max subarray sum bound max(nums)..sum(nums) checking k splits.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1231',
    slug: 'divide-chocolate',
    leetcodeNumber: 1231,
    title: 'Divide Chocolate',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 58.0,
    isPremium: true,
    topics: ['Array', 'Binary Search'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/divide-chocolate/',
    notes: 'Maximize the minimum sweetness among K+1 cuts using binary search.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.search-on-answer',
    patternSlug: 'search-on-answer',
    patternTitle: 'Binary Search on Answer',
    questTitle: 'Quest: The Trial of Thresholds',
    kingdomTitle: 'The Hidden Truth',
  },

  // 4. 2D & Advanced Binary Search
  {
    id: 'lc-1351',
    slug: 'count-negative-numbers-in-a-sorted-matrix',
    leetcodeNumber: 1351,
    title: 'Count Negative Numbers in a Sorted Matrix',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Matrix'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/',
    notes: 'Staircase search top-right or binary search per row.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-69',
    slug: 'sqrtx',
    leetcodeNumber: 69,
    title: 'Sqrt(x)',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Math', 'Binary Search'],
    companies: ['Apple', 'Microsoft'],
    url: 'https://leetcode.com/problems/sqrtx/',
    notes: 'Binary search range 1..x checking mid * mid <= x.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-240',
    slug: 'search-a-2d-matrix-ii',
    leetcodeNumber: 240,
    title: 'Search a 2D Matrix II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/search-a-2d-matrix-ii/',
    notes: 'Staircase search starting top-right corner in O(M+N).',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1898',
    slug: 'maximum-number-of-removable-characters',
    leetcodeNumber: 1898,
    title: 'Maximum Number of Removable Characters',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'String', 'Binary Search'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-number-of-removable-characters/',
    notes: 'Binary search K removable characters checking subsequence validity.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1201',
    slug: 'ugly-number-iii',
    leetcodeNumber: 1201,
    title: 'Ugly Number III',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 28.0,
    isPremium: false,
    topics: ['Math', 'Binary Search', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/ugly-number-iii/',
    notes: 'Binary search value range + Inclusion-Exclusion principle using LCM.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1283',
    slug: 'find-the-smallest-divisor-given-a-threshold',
    leetcodeNumber: 1283,
    title: 'Find the Smallest Divisor Given a Threshold',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/',
    notes: 'Binary search divisor range 1..max(nums) with sum check.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1428',
    slug: 'leftmost-column-with-at-least-a-one',
    leetcodeNumber: 1428,
    title: 'Leftmost Column with at Least a One',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: true,
    topics: ['Array', 'Binary Search', 'Interactive', 'Matrix'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/leftmost-column-with-at-least-a-one/',
    notes: 'Staircase top-right scan or binary search per row.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-658',
    slug: 'find-k-closest-elements',
    leetcodeNumber: 658,
    title: 'Find K Closest Elements',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Sliding Window', 'Sorting', 'Heap'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/find-k-closest-elements/',
    notes: 'Binary search window left index comparing x - arr[mid] vs arr[mid+k] - x.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-2226',
    slug: 'maximum-candies-allocated-to-k-children',
    leetcodeNumber: 2226,
    title: 'Maximum Candies Allocated to K Children',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'Binary Search'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-candies-allocated-to-k-children/',
    notes: 'Binary search candy count per child.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-719',
    slug: 'find-k-th-smallest-pair-distance',
    leetcodeNumber: 719,
    title: 'Find K-th Smallest Pair Distance',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Sorting'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/find-k-th-smallest-pair-distance/',
    notes: 'Binary search distance range + two pointers count pairs with diff <= mid.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
  {
    id: 'lc-1889',
    slug: 'minimum-space-wasted-from-packaging',
    leetcodeNumber: 1889,
    title: 'Minimum Space Wasted From Packaging',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Prefix Sum', 'Sorting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimum-space-wasted-from-packaging/',
    notes: 'Binary search upper bound + prefix sum wasted space calculation.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    patternId: 'pattern.2d-binary-search',
    patternSlug: '2d-binary-search',
    patternTitle: '2D & Advanced Binary Search',
    questTitle: 'Quest: The Layered Search',
    kingdomTitle: 'The Hidden Truth',
  },
];
