import { ProblemModel } from '../../types';

export const BIT_MANIPULATION_PROBLEMS: ProblemModel[] = [
  // 1. Basic Bit Tricks & Operations
  {
    id: 'lc-191',
    slug: 'number-of-1-bits',
    leetcodeNumber: 191,
    title: 'Number of 1 Bits',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Divide and Conquer', 'Bit Manipulation'],
    companies: ['Amazon', 'Microsoft', 'Meta'],
    url: 'https://leetcode.com/problems/number-of-1-bits/',
    notes: 'Brian Kernighans algorithm n = n & (n - 1) counting set bits.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-190',
    slug: 'reverse-bits',
    leetcodeNumber: 190,
    title: 'Reverse Bits',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Divide and Conquer', 'Bit Manipulation'],
    companies: ['Amazon', 'Apple'],
    url: 'https://leetcode.com/problems/reverse-bits/',
    notes: 'Shift result left and append last bit n & 1 for 32 iterations.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-231',
    slug: 'power-of-two',
    leetcodeNumber: 231,
    title: 'Power of Two',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Math', 'Bit Manipulation', 'Recursion'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/power-of-two/',
    notes: 'n > 0 && (n & (n - 1)) == 0 single expression check.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-338',
    slug: 'counting-bits',
    leetcodeNumber: 338,
    title: 'Counting Bits',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 77.0,
    isPremium: false,
    topics: ['Dynamic Programming', 'Bit Manipulation'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/counting-bits/',
    notes: 'dp[i] = dp[i >> 1] + (i & 1) O(N) tabulation.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-461',
    slug: 'hamming-distance',
    leetcodeNumber: 461,
    title: 'Hamming Distance',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['Bit Manipulation'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/hamming-distance/',
    notes: 'Count set bits in x ^ y.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },

  // 2. XOR Applications
  {
    id: 'lc-136',
    slug: 'single-number',
    leetcodeNumber: 136,
    title: 'Single Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/single-number/',
    notes: 'XOR all elements in array; pairs cancel out to 0 leaving single number.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-137',
    slug: 'single-number-ii',
    leetcodeNumber: 137,
    title: 'Single Number II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/single-number-ii/',
    notes: 'Sum bits across all elements modulo 3 or digital logic ones / twos state variables.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-260',
    slug: 'single-number-iii',
    leetcodeNumber: 260,
    title: 'Single Number III',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/single-number-iii/',
    notes: 'Find diffBit = xorSum & (-xorSum) and split numbers into two groups by diffBit.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-371',
    slug: 'sum-of-two-integers',
    leetcodeNumber: 371,
    title: 'Sum of Two Integers',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Math', 'Bit Manipulation'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/sum-of-two-integers/',
    notes: 'XOR for sum without carry (a ^ b), AND shifted left for carry (a & b) << 1.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },

  // 3. Bitmask DP & State Representation
  {
    id: 'lc-847-b',
    slug: 'shortest-path-visiting-all-nodes-bitmask',
    leetcodeNumber: 847,
    title: 'Shortest Path Visiting All Nodes (Bitmask BFS)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 19.7,
    isPremium: false,
    topics: ['Dynamic Programming', 'Bit Manipulation', 'Breadth-First Search', 'Graph', 'Bitmask'],
    companies: ['LinkedIn', 'Google'],
    url: 'https://leetcode.com/problems/shortest-path-visiting-all-nodes/',
    notes: 'State (node, mask) where bitmask represents set of visited vertices.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.bitmask-dp',
    patternSlug: 'bitmask-dp',
    patternTitle: 'Bitmask DP & State Representation',
    questTitle: 'Quest: The Masked Cavern',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-1125',
    slug: 'smallest-sufficient-team',
    leetcodeNumber: 1125,
    title: 'Smallest Sufficient Team',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Bit Manipulation', 'Bitmask'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/smallest-sufficient-team/',
    notes: 'Bitmask DP dp[skillsMask] storing smallest array of person indices.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.bitmask-dp',
    patternSlug: 'bitmask-dp',
    patternTitle: 'Bitmask DP & State Representation',
    questTitle: 'Quest: The Masked Cavern',
    kingdomTitle: 'The Binary Caverns',
  },

  // 4. Bitmask Subsets & Counting
  {
    id: 'lc-477',
    slug: 'total-hamming-distance',
    leetcodeNumber: 477,
    title: 'Total Hamming Distance',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Bit Manipulation'],
    companies: ['Meta', 'Google'],
    url: 'https://leetcode.com/problems/total-hamming-distance/',
    notes: 'Count set bits count1 and unset bits count0 at each bit position 0..31; add count1 * count0.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.bitmask-subsets-counting',
    patternSlug: 'bitmask-subsets-counting',
    patternTitle: 'Bitmask Subsets & Counting',
    questTitle: 'Quest: The Submask Weaver',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-201',
    slug: 'bitwise-and-of-numbers-range',
    leetcodeNumber: 201,
    title: 'Bitwise AND of Numbers Range',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Bit Manipulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/bitwise-and-of-numbers-range/',
    notes: 'Find common binary prefix of left and right limits by right-shifting until left == right.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.bitmask-subsets-counting',
    patternSlug: 'bitmask-subsets-counting',
    patternTitle: 'Bitmask Subsets & Counting',
    questTitle: 'Quest: The Submask Weaver',
    kingdomTitle: 'The Binary Caverns',
  },

  {
    id: 'lc-29',
    slug: 'divide-two-integers',
    leetcodeNumber: 29,
    title: 'Divide Two Integers',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 17.0,
    isPremium: false,
    topics: ['Math', 'Bit Manipulation'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/divide-two-integers/',
    notes: 'Bitwise bit shifting division (dividend -= divisor << shift) without using multiplication/division operator.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-393',
    slug: 'utf-8-validation',
    leetcodeNumber: 393,
    title: 'UTF-8 Validation',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/utf-8-validation/',
    notes: 'Bit masking 8-bit integers checking leading 1-bit counts for 1, 2, 3, or 4 byte UTF-8 encodings.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-421',
    slug: 'maximum-xor-of-two-numbers-in-an-array',
    leetcodeNumber: 421,
    title: 'Maximum XOR of Two Numbers in an Array',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Bit Manipulation', 'Trie'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/',
    notes: 'Bitwise Trie inserting 32-bit binary representations and greedily querying opposite bits.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-693',
    slug: 'binary-number-with-alternating-bits',
    leetcodeNumber: 693,
    title: 'Binary Number with Alternating Bits',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Bit Manipulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/binary-number-with-alternating-bits/',
    notes: 'n ^ (n >> 1) should produce all 1s (val & (val + 1) == 0).',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-868',
    slug: 'binary-gap',
    leetcodeNumber: 868,
    title: 'Binary Gap',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Bit Manipulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/binary-gap/',
    notes: 'Track distance between consecutive 1-bits in binary representation.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-1318',
    slug: 'minimum-flips-to-make-a-or-b-equal-to-c',
    leetcodeNumber: 1318,
    title: 'Minimum Flips to Make a OR b Equal to c',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Bit Manipulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-flips-to-make-a-or-b-equal-to-c/',
    notes: 'Bitwise comparison position by position counting required flips.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.basic-bit-tricks',
    patternSlug: 'basic-bit-tricks',
    patternTitle: 'Basic Bit Tricks & Operations',
    questTitle: 'Quest: The Bitwise Spark',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-1442',
    slug: 'count-triplets-that-can-form-two-arrays-of-equal-xor',
    leetcodeNumber: 1442,
    title: 'Count Triplets That Can Form Two Arrays of Equal XOR',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 78.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Bit Manipulation', 'Prefix Sum'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/count-triplets-that-can-form-two-arrays-of-equal-xor/',
    notes: 'Prefix XOR pref[i] == pref[k+1] implies subarray XOR sum is 0.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-1707',
    slug: 'maximum-xor-with-an-element-from-array',
    leetcodeNumber: 1707,
    title: 'Maximum XOR With an Element From Array',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation', 'Trie'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/',
    notes: 'Sort queries and array + Trie insert elements <= m_i.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-1835',
    slug: 'find-xor-sum-of-all-pairs-bitwise-and',
    leetcodeNumber: 1835,
    title: 'Find XOR Sum of All Pairs Bitwise AND',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 200,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Bit Manipulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-xor-sum-of-all-pairs-bitwise-and/',
    notes: 'Distributive property: (a1 ^ a2) & (b1 ^ b2) = XOR sum of all pair ANDs.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-2429',
    slug: 'minimize-xor',
    leetcodeNumber: 2429,
    title: 'Minimize XOR',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Greedy', 'Bit Manipulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimize-xor/',
    notes: 'Greedily match set bits of num1 from MSB to LSB.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-2683',
    slug: 'neighboring-bitwise-xor',
    leetcodeNumber: 2683,
    title: 'Neighboring Bitwise XOR',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/neighboring-bitwise-xor/',
    notes: 'Cumulative XOR sum of derived array must equal 0 for valid original array.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
  {
    id: 'lc-2997',
    slug: 'minimum-number-of-operations-to-make-array-xor-equal-to-k',
    leetcodeNumber: 2997,
    title: 'Minimum Number of Operations to Make Array XOR Equal to K',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 100,
    acceptanceRate: 81.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-number-of-operations-to-make-array-xor-equal-to-k/',
    notes: 'XOR all array numbers with K, answer is set bits count of total XOR.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    patternId: 'pattern.xor-applications',
    patternSlug: 'xor-applications',
    patternTitle: 'XOR Applications',
    questTitle: 'Quest: The Cancelled Cipher',
    kingdomTitle: 'The Binary Caverns',
  },
];
