import { ProblemModel } from '../../types';

export const DYNAMIC_PROGRAMMING_PROBLEMS: ProblemModel[] = [
  // 1. 1D DP
  {
    id: 'lc-70',
    slug: 'climbing-stairs',
    leetcodeNumber: 70,
    title: 'Climbing Stairs',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 23,
    xp: 50,
    acceptanceRate: 77.2,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Memoization'],
    companies: ['Atlassian', 'Oracle', 'Uber', 'Apple'],
    url: 'https://leetcode.com/problems/climbing-stairs/',
    notes: 'dp[i] = dp[i-1] + dp[i-2] Fibonacci sequence.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-198',
    slug: 'house-robber',
    leetcodeNumber: 198,
    title: 'House Robber',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Meta', 'Adobe'],
    url: 'https://leetcode.com/problems/house-robber/',
    notes: 'dp[i] = max(dp[i-1], dp[i-2] + nums[i]).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-746',
    slug: 'min-cost-climbing-stairs',
    leetcodeNumber: 746,
    title: 'Min Cost Climbing Stairs',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 57.3,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Microsoft', 'Salesforce', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/min-cost-climbing-stairs/',
    notes: 'dp[i] = cost[i] + min(dp[i-1], dp[i-2]).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-139',
    slug: 'word-break',
    leetcodeNumber: 139,
    title: 'Word Break',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 39,
    xp: 100,
    acceptanceRate: 32.4,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Dynamic Programming', 'Trie', 'Memoization'],
    companies: ['Goldman Sachs', 'Bloomberg'],
    url: 'https://leetcode.com/problems/word-break/',
    notes: 'dp[i] is true if dp[j] is true and wordDict contains s[j..i].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-300',
    slug: 'longest-increasing-subsequence',
    leetcodeNumber: 300,
    title: 'Longest Increasing Subsequence',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 54.6,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Dynamic Programming'],
    companies: ['Salesforce', 'Apple', 'Oracle'],
    url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    notes: 'Patience sorting + binary search for O(N log N) LIS.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-213',
    slug: 'house-robber-ii',
    leetcodeNumber: 213,
    title: 'House Robber II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 27,
    xp: 100,
    acceptanceRate: 44.2,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Uber', 'Bloomberg', 'Netflix', 'LinkedIn'],
    url: 'https://leetcode.com/problems/house-robber-ii/',
    notes: 'Run House Robber I twice: nums[0..N-2] vs nums[1..N-1].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-377',
    slug: 'combination-sum-iv',
    leetcodeNumber: 377,
    title: 'Combination Sum IV',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 48.2,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Amazon', 'Google', 'Salesforce'],
    url: 'https://leetcode.com/problems/combination-sum-iv/',
    notes: 'Unbounded knapsack permutation count iteration.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-91',
    slug: 'decode-ways',
    leetcodeNumber: 91,
    title: 'Decode Ways',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 19.8,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Uber', 'Bloomberg', 'Google'],
    url: 'https://leetcode.com/problems/decode-ways/',
    notes: '1-digit and 2-digit valid numeric decoding transitions.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.1d-dp',
    patternSlug: '1d-dp',
    patternTitle: '1D DP',
    questTitle: 'Quest: The Linear Path',
    kingdomTitle: 'Time Citadel',
  },

  // 2. 2D Grid DP
  {
    id: 'lc-62',
    slug: 'unique-paths',
    leetcodeNumber: 62,
    title: 'Unique Paths',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 37,
    xp: 100,
    acceptanceRate: 56.8,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Combinatorics'],
    companies: ['LinkedIn', 'Oracle'],
    url: 'https://leetcode.com/problems/unique-paths/',
    notes: 'dp[r][c] = dp[r-1][c] + dp[r][c-1].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.2d-grid-dp',
    patternSlug: '2d-grid-dp',
    patternTitle: '2D Grid DP',
    questTitle: 'Quest: The Woven Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-64',
    slug: 'minimum-path-sum',
    leetcodeNumber: 64,
    title: 'Minimum Path Sum',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 54.7,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Matrix'],
    companies: ['Bloomberg', 'Oracle', 'Apple', 'Uber'],
    url: 'https://leetcode.com/problems/minimum-path-sum/',
    notes: 'dp[r][c] = grid[r][c] + min(dp[r-1][c], dp[r][c-1]).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.2d-grid-dp',
    patternSlug: '2d-grid-dp',
    patternTitle: '2D Grid DP',
    questTitle: 'Quest: The Woven Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-63',
    slug: 'unique-paths-ii',
    leetcodeNumber: 63,
    title: 'Unique Paths II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 48.1,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Matrix'],
    companies: ['Atlassian', 'Amazon', 'Netflix', 'Bloomberg'],
    url: 'https://leetcode.com/problems/unique-paths-ii/',
    notes: 'Grid DP with obstacle cells forced to 0 paths.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.2d-grid-dp',
    patternSlug: '2d-grid-dp',
    patternTitle: '2D Grid DP',
    questTitle: 'Quest: The Woven Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-120',
    slug: 'triangle',
    leetcodeNumber: 120,
    title: 'Triangle',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 57.9,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Salesforce', 'Microsoft'],
    url: 'https://leetcode.com/problems/triangle/',
    notes: 'Bottom-up triangle row min path accumulation.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.2d-grid-dp',
    patternSlug: '2d-grid-dp',
    patternTitle: '2D Grid DP',
    questTitle: 'Quest: The Woven Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-221',
    slug: 'maximal-square',
    leetcodeNumber: 221,
    title: 'Maximal Square',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 57.4,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Matrix'],
    companies: ['Uber', 'Atlassian', 'Amazon'],
    url: 'https://leetcode.com/problems/maximal-square/',
    notes: 'dp[r][c] = 1 + min(dp[r-1][c], dp[r][c-1], dp[r-1][c-1]).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.2d-grid-dp',
    patternSlug: '2d-grid-dp',
    patternTitle: '2D Grid DP',
    questTitle: 'Quest: The Woven Path',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-174',
    slug: 'dungeon-game',
    leetcodeNumber: 174,
    title: 'Dungeon Game',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 54,
    xp: 200,
    acceptanceRate: 21.7,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Matrix'],
    companies: ['Meta', 'Microsoft', 'LinkedIn'],
    url: 'https://leetcode.com/problems/dungeon-game/',
    notes: 'Reverse bottom-right to top-left health DP requirement.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.2d-grid-dp',
    patternSlug: '2d-grid-dp',
    patternTitle: '2D Grid DP',
    questTitle: 'Quest: The Woven Path',
    kingdomTitle: 'Time Citadel',
  },

  // 3. Knapsack DP
  {
    id: 'lc-416',
    slug: 'partition-equal-subset-sum',
    leetcodeNumber: 416,
    title: 'Partition Equal Subset Sum',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 33.2,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Microsoft', 'Netflix', 'Amazon'],
    url: 'https://leetcode.com/problems/partition-equal-subset-sum/',
    notes: '0/1 Knapsack boolean subset sum target sum/2.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.knapsack-dp',
    patternSlug: 'knapsack-dp',
    patternTitle: 'Knapsack DP',
    questTitle: "Quest: The Merchant's Sack",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-279',
    slug: 'perfect-squares',
    leetcodeNumber: 279,
    title: 'Perfect Squares',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 39.6,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Breadth-First Search'],
    companies: ['Adobe', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/perfect-squares/',
    notes: 'Unbounded knapsack min count using square numbers.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.knapsack-dp',
    patternSlug: 'knapsack-dp',
    patternTitle: 'Knapsack DP',
    questTitle: "Quest: The Merchant's Sack",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-518',
    slug: 'coin-change-ii',
    leetcodeNumber: 518,
    title: 'Coin Change II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 43.2,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Goldman Sachs', 'Oracle', 'Bloomberg'],
    url: 'https://leetcode.com/problems/coin-change-ii/',
    notes: 'Unbounded knapsack combination count (outer coin loop).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.knapsack-dp',
    patternSlug: 'knapsack-dp',
    patternTitle: 'Knapsack DP',
    questTitle: "Quest: The Merchant's Sack",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-322',
    slug: 'coin-change',
    leetcodeNumber: 322,
    title: 'Coin Change',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 46.7,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Breadth-First Search'],
    companies: ['Google', 'LinkedIn', 'Meta', 'Uber'],
    url: 'https://leetcode.com/problems/coin-change/',
    notes: 'Unbounded knapsack min coins recurrence dp[i] = min(dp[i], dp[i-coin]+1).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.knapsack-dp',
    patternSlug: 'knapsack-dp',
    patternTitle: 'Knapsack DP',
    questTitle: "Quest: The Merchant's Sack",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-879',
    slug: 'profitable-schemes',
    leetcodeNumber: 879,
    title: 'Profitable Schemes',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 21.9,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Netflix', 'Microsoft'],
    url: 'https://leetcode.com/problems/profitable-schemes/',
    notes: '3D Knapsack DP dp[group][minProfit].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.knapsack-dp',
    patternSlug: 'knapsack-dp',
    patternTitle: 'Knapsack DP',
    questTitle: "Quest: The Merchant's Sack",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-494',
    slug: 'target-sum',
    leetcodeNumber: 494,
    title: 'Target Sum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 52,
    xp: 200,
    acceptanceRate: 31.6,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Backtracking'],
    companies: ['Netflix', 'Bloomberg', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/target-sum/',
    notes: 'Transform +/- target sum into subset sum P = (target + sum)/2.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.knapsack-dp',
    patternSlug: 'knapsack-dp',
    patternTitle: 'Knapsack DP',
    questTitle: "Quest: The Merchant's Sack",
    kingdomTitle: 'Time Citadel',
  },

  // 4. String DP
  {
    id: 'lc-583',
    slug: 'delete-operation-for-two-strings',
    leetcodeNumber: 583,
    title: 'Delete Operation for Two Strings',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 55.7,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Apple', 'Atlassian', 'Oracle'],
    url: 'https://leetcode.com/problems/delete-operation-for-two-strings/',
    notes: 'Min deletes = len(s1) + len(s2) - 2 * LCS(s1, s2).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.string-dp',
    patternSlug: 'string-dp',
    patternTitle: 'String DP',
    questTitle: "Quest: The Scribe's Puzzle",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1143',
    slug: 'longest-common-subsequence',
    leetcodeNumber: 1143,
    title: 'Longest Common Subsequence',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 29,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Netflix', 'Apple'],
    url: 'https://leetcode.com/problems/longest-common-subsequence/',
    notes: 'Classic 2D String DP matching matrix dp[i][j].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.string-dp',
    patternSlug: 'string-dp',
    patternTitle: 'String DP',
    questTitle: "Quest: The Scribe's Puzzle",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-72',
    slug: 'edit-distance',
    leetcodeNumber: 72,
    title: 'Edit Distance',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 39,
    xp: 100,
    acceptanceRate: 38.6,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Netflix', 'Microsoft', 'Oracle', 'Bloomberg'],
    url: 'https://leetcode.com/problems/edit-distance/',
    notes: 'Levenshtein distance insert/delete/replace operations matrix.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.string-dp',
    patternSlug: 'string-dp',
    patternTitle: 'String DP',
    questTitle: "Quest: The Scribe's Puzzle",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-647',
    slug: 'palindromic-substrings',
    leetcodeNumber: 647,
    title: 'Palindromic Substrings',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 39,
    xp: 100,
    acceptanceRate: 55.4,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Atlassian', 'Apple', 'Oracle', 'Bloomberg'],
    url: 'https://leetcode.com/problems/palindromic-substrings/',
    notes: 'Expand around center pointers or 2D boolean DP.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.string-dp',
    patternSlug: 'string-dp',
    patternTitle: 'String DP',
    questTitle: "Quest: The Scribe's Puzzle",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-115',
    slug: 'distinct-subsequences',
    leetcodeNumber: 115,
    title: 'Distinct Subsequences',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 42,
    xp: 200,
    acceptanceRate: 27.7,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['LinkedIn', 'Amazon'],
    url: 'https://leetcode.com/problems/distinct-subsequences/',
    notes: 'Count occurrences of string t as subsequence of s.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.string-dp',
    patternSlug: 'string-dp',
    patternTitle: 'String DP',
    questTitle: "Quest: The Scribe's Puzzle",
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-97',
    slug: 'interleaving-string',
    leetcodeNumber: 97,
    title: 'Interleaving String',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 58,
    xp: 200,
    acceptanceRate: 24.6,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Microsoft', 'Adobe', 'Uber', 'Amazon'],
    url: 'https://leetcode.com/problems/interleaving-string/',
    notes: '2D DP dp[i][j] checking if s1[0..i] and s2[0..j] interleave into s3[0..i+j].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.string-dp',
    patternSlug: 'string-dp',
    patternTitle: 'String DP',
    questTitle: "Quest: The Scribe's Puzzle",
    kingdomTitle: 'Time Citadel',
  },

  // 5. Interval DP
  {
    id: 'lc-5',
    slug: 'longest-palindromic-substring',
    leetcodeNumber: 5,
    title: 'Longest Palindromic Substring',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 33,
    xp: 100,
    acceptanceRate: 43.9,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Meta', 'Salesforce', 'Uber', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/longest-palindromic-substring/',
    notes: 'Expand around center or subsegment interval DP.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.interval-dp',
    patternSlug: 'interval-dp',
    patternTitle: 'Interval DP',
    questTitle: 'Quest: The Nested Chambers',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-516',
    slug: 'longest-palindromic-subsequence',
    leetcodeNumber: 516,
    title: 'Longest Palindromic Subsequence',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 37.2,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Oracle', 'Meta', 'Uber', 'Microsoft'],
    url: 'https://leetcode.com/problems/longest-palindromic-subsequence/',
    notes: 'Interval DP dp[i][j] = dp[i+1][j-1] + 2 if s[i]==s[j].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.interval-dp',
    patternSlug: 'interval-dp',
    patternTitle: 'Interval DP',
    questTitle: 'Quest: The Nested Chambers',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-312',
    slug: 'burst-balloons',
    leetcodeNumber: 312,
    title: 'Burst Balloons',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 20.3,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Netflix', 'Bloomberg', 'Goldman Sachs', 'Meta'],
    url: 'https://leetcode.com/problems/burst-balloons/',
    notes: 'Reverse thinking interval DP picking last balloon burst in range [i..j].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.interval-dp',
    patternSlug: 'interval-dp',
    patternTitle: 'Interval DP',
    questTitle: 'Quest: The Nested Chambers',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1039',
    slug: 'minimum-score-triangulation-of-polygon',
    leetcodeNumber: 1039,
    title: 'Minimum Score Triangulation of Polygon',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 58,
    xp: 200,
    acceptanceRate: 25.9,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Amazon', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/minimum-score-triangulation-of-polygon/',
    notes: 'Interval DP splitting polygon between vertices i, j, k.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.interval-dp',
    patternSlug: 'interval-dp',
    patternTitle: 'Interval DP',
    questTitle: 'Quest: The Nested Chambers',
    kingdomTitle: 'Time Citadel',
  },

  // 6. Tree & State-Machine DP
  {
    id: 'lc-337',
    slug: 'house-robber-iii',
    leetcodeNumber: 337,
    title: 'House Robber III',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 32.6,
    isPremium: false,
    topics: ['Dynamic Programming', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Google', 'Amazon', 'Salesforce', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/house-robber-iii/',
    notes: 'Tree DFS returning pair [robbedHere, notRobbedHere].',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.tree-state-machine-dp',
    patternSlug: 'tree-state-machine-dp',
    patternTitle: 'Tree & State-Machine DP',
    questTitle: 'Quest: The Branching Fortune',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-309',
    slug: 'best-time-to-buy-and-sell-stock-with-cooldown',
    leetcodeNumber: 309,
    title: 'Best Time to Buy and Sell Stock with Cooldown',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 37,
    xp: 100,
    acceptanceRate: 39.1,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Oracle', 'Apple', 'LinkedIn', 'Adobe'],
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
    notes: 'State machine states: hold, sold, reset.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.tree-state-machine-dp',
    patternSlug: 'tree-state-machine-dp',
    patternTitle: 'Tree & State-Machine DP',
    questTitle: 'Quest: The Branching Fortune',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-188',
    slug: 'best-time-to-buy-and-sell-stock-iv',
    leetcodeNumber: 188,
    title: 'Best Time to Buy and Sell Stock IV',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 59,
    xp: 200,
    acceptanceRate: 34.4,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Meta', 'Microsoft', 'Uber', 'Atlassian'],
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/',
    notes: 'State machine DP tracking K transactions.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.tree-state-machine-dp',
    patternSlug: 'tree-state-machine-dp',
    patternTitle: 'Tree & State-Machine DP',
    questTitle: 'Quest: The Branching Fortune',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-968',
    slug: 'binary-tree-cameras',
    leetcodeNumber: 968,
    title: 'Binary Tree Cameras',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 64,
    xp: 200,
    acceptanceRate: 35.6,
    isPremium: false,
    topics: ['Dynamic Programming', 'Tree', 'Depth-First Search', 'Binary Tree'],
    companies: ['Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/binary-tree-cameras/',
    notes: 'Greedy bottom-up tree state: 0 (uncovered), 1 (camera), 2 (covered).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.tree-state-machine-dp',
    patternSlug: 'tree-state-machine-dp',
    patternTitle: 'Tree & State-Machine DP',
    questTitle: 'Quest: The Branching Fortune',
    kingdomTitle: 'Time Citadel',
  },

  // 7. Advanced State DP
  {
    id: 'lc-509',
    slug: 'fibonacci-number',
    leetcodeNumber: 509,
    title: 'Fibonacci Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Recursion', 'Memoization'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/fibonacci-number/',
    notes: 'O(N) iterative tabulation or O(1) space variables.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1137',
    slug: 'n-th-tribonacci-number',
    leetcodeNumber: 1137,
    title: 'N-th Tribonacci Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Memoization'],
    companies: ['Microsoft', 'Adobe', 'Uber'],
    url: 'https://leetcode.com/problems/n-th-tribonacci-number/',
    notes: 'T(n) = T(n-1) + T(n-2) + T(n-3) recurrence.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-121',
    slug: 'best-time-to-buy-and-sell-stock',
    leetcodeNumber: 121,
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Uber', 'Goldman Sachs', 'Apple', 'Netflix'],
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    notes: 'Single pass minPrice tracking and maxProfit accumulation.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-96',
    slug: 'unique-binary-search-trees',
    leetcodeNumber: 96,
    title: 'Unique Binary Search Trees',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Tree', 'Binary Search Tree', 'Binary Tree'],
    companies: ['Apple', 'Netflix'],
    url: 'https://leetcode.com/problems/unique-binary-search-trees/',
    notes: 'Catalan number recurrence G(n) = sum(G(i-1) * G(n-i)).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1049',
    slug: 'last-stone-weight-ii',
    leetcodeNumber: 1049,
    title: 'Last Stone Weight II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming'],
    companies: ['Bloomberg', 'Atlassian', 'LinkedIn'],
    url: 'https://leetcode.com/problems/last-stone-weight-ii/',
    notes: 'Partition stones into two subsets minimizing difference (0/1 knapsack).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1626',
    slug: 'best-team-with-no-conflicts',
    leetcodeNumber: 1626,
    title: 'Best Team With No Conflicts',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Sorting'],
    companies: ['LinkedIn', 'Salesforce', 'Oracle', 'Google'],
    url: 'https://leetcode.com/problems/best-team-with-no-conflicts/',
    notes: 'Sort players by age then score, LIS variant DP.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1594',
    slug: 'maximum-non-negative-product-in-a-matrix',
    leetcodeNumber: 1594,
    title: 'Maximum Non Negative Product in a Matrix',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Matrix'],
    companies: ['Oracle', 'Google'],
    url: 'https://leetcode.com/problems/maximum-non-negative-product-in-a-matrix/',
    notes: 'Track minProduct and maxProduct at each grid cell.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-474',
    slug: 'ones-and-zeroes',
    leetcodeNumber: 474,
    title: 'Ones and Zeroes',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'String', 'Dynamic Programming'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/ones-and-zeroes/',
    notes: '2D Knapsack DP dp[m][n] max subsets with m zeroes and n ones.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1621',
    slug: 'number-of-sets-of-k-non-overlapping-line-segments',
    leetcodeNumber: 1621,
    title: 'Number of Sets of K Non-Overlapping Line Segments',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Combinatorics'],
    companies: ['Microsoft', 'Adobe', 'Uber', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/number-of-sets-of-k-non-overlapping-line-segments/',
    notes: '2D DP dp[n][k] or combinatorics C(n+k, 2k).',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1155',
    slug: 'number-of-dice-rolls-with-target-sum',
    leetcodeNumber: 1155,
    title: 'Number of Dice Rolls With Target Sum',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['Dynamic Programming'],
    companies: ['Uber', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/',
    notes: 'dp[n][target] = sum(dp[n-1][target - k]) for k=1..faces.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-887',
    slug: 'super-egg-drop',
    leetcodeNumber: 887,
    title: 'Super Egg Drop',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 48,
    xp: 200,
    acceptanceRate: 30.0,
    isPremium: false,
    topics: ['Math', 'Binary Search', 'Dynamic Programming'],
    companies: ['Apple', 'Netflix', 'Bloomberg'],
    url: 'https://leetcode.com/problems/super-egg-drop/',
    notes: 'DP with binary search or inverse DP dp[k][moves] = max floors testable.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1235',
    slug: 'maximum-profit-in-job-scheduling',
    leetcodeNumber: 1235,
    title: 'Maximum Profit in Job Scheduling',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Dynamic Programming', 'Sorting'],
    companies: ['Bloomberg', 'Atlassian', 'LinkedIn', 'Salesforce'],
    url: 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/',
    notes: 'Sort jobs by end time + binary search latest non-overlapping job.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-741',
    slug: 'cherry-pickup',
    leetcodeNumber: 741,
    title: 'Cherry Pickup',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 52,
    xp: 200,
    acceptanceRate: 24.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Matrix'],
    companies: ['LinkedIn', 'Salesforce'],
    url: 'https://leetcode.com/problems/cherry-pickup/',
    notes: 'Simulate two simultaneous paths from (0,0) to (N-1,N-1) in 3D DP.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-87',
    slug: 'scramble-string',
    leetcodeNumber: 87,
    title: 'Scramble String',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 54,
    xp: 200,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Oracle', 'Google', 'Amazon'],
    url: 'https://leetcode.com/problems/scramble-string/',
    notes: 'Recursive split memoization with frequency pruning.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
  {
    id: 'lc-1359',
    slug: 'count-all-valid-pickup-and-delivery-options',
    leetcodeNumber: 1359,
    title: 'Count All Valid Pickup and Delivery Options',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 56,
    xp: 200,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Combinatorics'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Adobe'],
    url: 'https://leetcode.com/problems/count-all-valid-pickup-and-delivery-options/',
    notes: 'dp[i] = dp[i-1] * i * (2*i - 1) modulo 10^9+7.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    patternId: 'pattern.advanced-state-dp',
    patternSlug: 'advanced-state-dp',
    patternTitle: 'Advanced State DP',
    questTitle: 'Quest: The Hidden Ledger',
    kingdomTitle: 'Time Citadel',
  },
];
