import { ProblemModel } from '../../types';

export const GRAPHS_PROBLEMS: ProblemModel[] = [
  // 1. Graph Traversal (DFS/BFS)
  {
    id: 'lc-200',
    slug: 'number-of-islands',
    leetcodeNumber: 200,
    title: 'Number of Islands',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/number-of-islands/',
    notes: '2D Grid DFS / BFS connected component sink marking.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-133',
    slug: 'clone-graph',
    leetcodeNumber: 133,
    title: 'Clone Graph',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Hash Table', 'Depth-First Search', 'Breadth-First Search', 'Graph'],
    companies: ['Meta', 'Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/clone-graph/',
    notes: 'DFS / BFS graph traversal carrying oldNode -> newNode HashMap.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-695',
    slug: 'max-area-of-island',
    leetcodeNumber: 695,
    title: 'Max Area of Island',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 71.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Matrix'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/max-area-of-island/',
    notes: 'Flood fill DFS returning 1 + left + right + up + down component sizes.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-130',
    slug: 'surrounded-regions',
    leetcodeNumber: 130,
    title: 'Surrounded Regions',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Matrix'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/surrounded-regions/',
    notes: 'Boundary connected component DFS marking safe O cells.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-417',
    slug: 'pacific-atlantic-water-flow',
    leetcodeNumber: 417,
    title: 'Pacific Atlantic Water Flow',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Matrix'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
    notes: 'Reverse flow DFS from Pacific and Atlantic ocean boundary cells.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-733',
    slug: 'flood-fill',
    leetcodeNumber: 733,
    title: 'Flood Fill',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Matrix'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/flood-fill/',
    notes: 'Recursive 4-directional color replacement DFS.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-841',
    slug: 'keys-and-rooms',
    leetcodeNumber: 841,
    title: 'Keys and Rooms',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 100,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/keys-and-rooms/',
    notes: 'Graph DFS/BFS visited array set reaching all rooms.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },

  // 2. Topological Sort
  {
    id: 'lc-207',
    slug: 'course-schedule',
    leetcodeNumber: 207,
    title: 'Course Schedule',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Topological Sort'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/course-schedule/',
    notes: 'Kahn algorithm in-degree BFS or DFS cycle state tracking (visited/visiting).',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.topological-sort',
    patternSlug: 'topological-sort',
    patternTitle: 'Topological Sort',
    questTitle: 'Quest: The Order of Precedence',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-210',
    slug: 'course-schedule-ii',
    leetcodeNumber: 210,
    title: 'Course Schedule II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Topological Sort'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/course-schedule-ii/',
    notes: 'Kahns algorithm building topological sort ordering list.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.topological-sort',
    patternSlug: 'topological-sort',
    patternTitle: 'Topological Sort',
    questTitle: 'Quest: The Order of Precedence',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-269',
    slug: 'alien-dictionary',
    leetcodeNumber: 269,
    title: 'Alien Dictionary',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 35.0,
    isPremium: true,
    topics: ['Array', 'String', 'Depth-First Search', 'Breadth-First Search', 'Graph', 'Topological Sort'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/alien-dictionary/',
    notes: 'Build character dependency graph from adjacent dictionary words + Topological Sort.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.topological-sort',
    patternSlug: 'topological-sort',
    patternTitle: 'Topological Sort',
    questTitle: 'Quest: The Order of Precedence',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-310',
    slug: 'minimum-height-trees',
    leetcodeNumber: 310,
    title: 'Minimum Height Trees',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Topological Sort'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/minimum-height-trees/',
    notes: 'Topological trimming of degree-1 leaf nodes inward until 1 or 2 centers remain.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.topological-sort',
    patternSlug: 'topological-sort',
    patternTitle: 'Topological Sort',
    questTitle: 'Quest: The Order of Precedence',
    kingdomTitle: 'Shadow Forest',
  },

  // 3. Union-Find (Disjoint Set Union)
  {
    id: 'lc-547',
    slug: 'number-of-provinces',
    leetcodeNumber: 547,
    title: 'Number of Provinces',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/number-of-provinces/',
    notes: 'Union-Find with path compression and rank tracking connected components.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-684',
    slug: 'redundant-connection',
    leetcodeNumber: 684,
    title: 'Redundant Connection',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/redundant-connection/',
    notes: 'First edge whose u and v share same DSU root forms cycle.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-721',
    slug: 'accounts-merge',
    leetcodeNumber: 721,
    title: 'Accounts Merge',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Sorting'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/accounts-merge/',
    notes: 'Map email -> account ID and union emails belonging to same account.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-990',
    slug: 'satisfiability-of-equality-equations',
    leetcodeNumber: 990,
    title: 'Satisfiability of Equality Equations',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Array', 'String', 'Union-Find', 'Graph'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/satisfiability-of-equality-equations/',
    notes: 'Union variables with == relations first, then verify != variables do not share root.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },

  // 4. Bipartite & Colorability
  {
    id: 'lc-785',
    slug: 'is-graph-bipartite',
    leetcodeNumber: 785,
    title: 'Is Graph Bipartite?',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/is-graph-bipartite/',
    notes: '2-coloring DFS/BFS marking nodes with 1 and -1.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.bipartite-coloring',
    patternSlug: 'bipartite-coloring',
    patternTitle: 'Bipartite & Colorability',
    questTitle: 'Quest: The Dual Realm',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-886',
    slug: 'possible-bipartition',
    leetcodeNumber: 886,
    title: 'Possible Bipartition',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/possible-bipartition/',
    notes: 'Construct dislike graph and run 2-coloring bipartite check.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.bipartite-coloring',
    patternSlug: 'bipartite-coloring',
    patternTitle: 'Bipartite & Colorability',
    questTitle: 'Quest: The Dual Realm',
    kingdomTitle: 'Shadow Forest',
  },

  // 5. Advanced Graph Traversal & Cycle Detection
  {
    id: 'lc-797',
    slug: 'all-paths-from-source-to-target',
    leetcodeNumber: 797,
    title: 'All Paths From Source to Target',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 82.0,
    isPremium: false,
    topics: ['Backtracking', 'Depth-First Search', 'Breadth-First Search', 'Graph'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/all-paths-from-source-to-target/',
    notes: 'DAG backtracking DFS collecting all paths from node 0 to N-1.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.advanced-graph-traversal',
    patternSlug: 'advanced-graph-traversal',
    patternTitle: 'Advanced Graph Traversal & Cycle Detection',
    questTitle: 'Quest: The Labyrinth of Echoes',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-802',
    slug: 'find-eventual-safe-states',
    leetcodeNumber: 802,
    title: 'Find Eventual Safe States',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Topological Sort'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/find-eventual-safe-states/',
    notes: 'Reverse edges + Kahn algorithm or 3-state DFS cycle detection.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.advanced-graph-traversal',
    patternSlug: 'advanced-graph-traversal',
    patternTitle: 'Advanced Graph Traversal & Cycle Detection',
    questTitle: 'Quest: The Labyrinth of Echoes',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1466',
    slug: 'reorder-routes-to-make-all-paths-lead-to-the-city-zero',
    leetcodeNumber: 1466,
    title: 'Reorder Routes to Make All Paths Lead to the City Zero',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/',
    notes: 'Build undirected graph tracking directed edge orientation + DFS from 0 counting required reversals.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.advanced-graph-traversal',
    patternSlug: 'advanced-graph-traversal',
    patternTitle: 'Advanced Graph Traversal & Cycle Detection',
    questTitle: 'Quest: The Labyrinth of Echoes',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1192',
    slug: 'critical-connections-in-a-network',
    leetcodeNumber: 1192,
    title: 'Critical Connections in a Network',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Graph', 'Biconnected Component'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/critical-connections-in-a-network/',
    notes: 'Tarjan bridge-finding algorithm using discovery time low[u] > rank[v].',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.advanced-graph-traversal',
    patternSlug: 'advanced-graph-traversal',
    patternTitle: 'Advanced Graph Traversal & Cycle Detection',
    questTitle: 'Quest: The Labyrinth of Echoes',
    kingdomTitle: 'Shadow Forest',
  },

  // 6. Graph Construction & Multi-source BFS
  {
    id: 'lc-1162',
    slug: 'as-far-from-land-as-possible',
    leetcodeNumber: 1162,
    title: 'As Far from Land as Possible',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Breadth-First Search', 'Matrix'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/as-far-from-land-as-possible/',
    notes: 'Multi-source BFS pushing all land cells 1 to queue and expanding into water 0.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-construction-multi-bfs',
    patternSlug: 'graph-construction-multi-bfs',
    patternTitle: 'Graph Construction & Multi-source BFS',
    questTitle: 'Quest: The Expanding Ripple',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-934',
    slug: 'shortest-bridge',
    leetcodeNumber: 934,
    title: 'Shortest Bridge',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Matrix'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/shortest-bridge/',
    notes: 'DFS flood fill to find first island then multi-source BFS to reach second island.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-construction-multi-bfs',
    patternSlug: 'graph-construction-multi-bfs',
    patternTitle: 'Graph Construction & Multi-source BFS',
    questTitle: 'Quest: The Expanding Ripple',
    kingdomTitle: 'Shadow Forest',
  },

  {
    id: 'lc-323',
    slug: 'number-of-connected-components-in-an-undirected-graph',
    leetcodeNumber: 323,
    title: 'Number of Connected Components in an Undirected Graph',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: true,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
    notes: 'Union-Find tracking count initialized to N and decremented on union.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-261',
    slug: 'graph-valid-tree',
    leetcodeNumber: 261,
    title: 'Graph Valid Tree',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: true,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Meta', 'Google'],
    url: 'https://leetcode.com/problems/graph-valid-tree/',
    notes: 'Verify edges == n - 1 and all nodes form a single connected component.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-399',
    slug: 'evaluate-division',
    leetcodeNumber: 399,
    title: 'Evaluate Division',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph', 'Shortest Path'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/evaluate-division/',
    notes: 'Weighted directed graph DFS / BFS path product or Union-Find with weights.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-743-g',
    slug: 'network-delay-time-graphs',
    leetcodeNumber: 743,
    title: 'Network Delay Time (Graph Representation)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Heap', 'Shortest Path'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/network-delay-time/',
    notes: 'Dijkstra shortest path algorithm on weighted graph.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-787-g',
    slug: 'cheapest-flights-within-k-stops-graphs',
    leetcodeNumber: 787,
    title: 'Cheapest Flights Within K Stops (Graph Representation)',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['Dynamic Programming', 'Depth-First Search', 'Breadth-First Search', 'Graph', 'Heap', 'Shortest Path'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
    notes: 'Bellman-Ford or BFS queue with stops limit constraint.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.graph-traversal',
    patternSlug: 'graph-traversal',
    patternTitle: 'Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Shadow Web',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1319',
    slug: 'number-of-operations-to-make-network-connected',
    leetcodeNumber: 1319,
    title: 'Number of Operations to Make Network Connected',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-operations-to-make-network-connected/',
    notes: 'If edges < n - 1 return -1; answer is connected components - 1.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-947',
    slug: 'most-stones-removed-with-same-row-or-column',
    leetcodeNumber: 947,
    title: 'Most Stones Removed with Same Row or Column',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['Hash Table', 'Depth-First Search', 'Union-Find', 'Graph'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/',
    notes: 'Union stones sharing row x or col y~10000; totalStones - numComponents.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1584',
    slug: 'min-cost-to-connect-all-points',
    leetcodeNumber: 1584,
    title: 'Min Cost to Connect All Points',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Array', 'Union-Find', 'Graph', 'Minimum Spanning Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
    notes: 'Kruskals MST algorithm with Manhattan distance edges or Prims algorithm.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1202',
    slug: 'smallest-string-with-swaps',
    leetcodeNumber: 1202,
    title: 'Smallest String With Swaps',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/smallest-string-with-swaps/',
    notes: 'Union-Find index components then sort characters per component.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1627',
    slug: 'graph-connectivity-with-threshold',
    leetcodeNumber: 1627,
    title: 'Graph Connectivity With Threshold',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Union-Find', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/graph-connectivity-with-threshold/',
    notes: 'Sieve-like Union-Find connecting multiples of values > threshold.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-839',
    slug: 'similar-string-groups',
    leetcodeNumber: 839,
    title: 'Similar String Groups',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/similar-string-groups/',
    notes: 'Check string pair diff <= 2 and union similar strings.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1579',
    slug: 'remove-max-number-of-edges-to-keep-graph-fully-traversable',
    leetcodeNumber: 1579,
    title: 'Remove Max Number of Edges to Keep Graph Fully Traversable',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Union-Find', 'Graph'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/remove-max-number-of-edges-to-keep-graph-fully-traversable/',
    notes: 'Two DSU instances (Alice and Bob) prioritizing Type 3 (shared) edges first.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1697',
    slug: 'checking-existence-of-edge-length-limited-paths',
    leetcodeNumber: 1697,
    title: 'Checking Existence of Edge Length Limited Paths',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/',
    notes: 'Offline query processing: sort queries and edges by weight then incrementally Union edges.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1568',
    slug: 'minimum-number-of-days-to-disconnect-island',
    leetcodeNumber: 1568,
    title: 'Minimum Number of Days to Disconnect Island',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Matrix', 'Strongly Connected Component'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-number-of-days-to-disconnect-island/',
    notes: 'Answer is 0, 1, or 2 days max. Check connected components after removing each land cell.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.advanced-graph-traversal',
    patternSlug: 'advanced-graph-traversal',
    patternTitle: 'Advanced Graph Traversal & Cycle Detection',
    questTitle: 'Quest: The Labyrinth of Echoes',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1203',
    slug: 'sort-items-by-groups-respecting-dependencies',
    leetcodeNumber: 1203,
    title: 'Sort Items by Groups Respecting Dependencies',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Topological Sort'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/sort-items-by-groups-respecting-dependencies/',
    notes: 'Dual Topological Sort on Groups graph and Items within each Group.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.topological-sort',
    patternSlug: 'topological-sort',
    patternTitle: 'Topological Sort',
    questTitle: 'Quest: The Order of Precedence',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-1489',
    slug: 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree',
    leetcodeNumber: 1489,
    title: 'Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Union-Find', 'Graph', 'Minimum Spanning Tree', 'Sorting'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/',
    notes: 'Kruskal MST baseline weight comparison forcing/excluding each edge.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
  {
    id: 'lc-2092',
    slug: 'find-all-people-with-secret',
    leetcodeNumber: 2092,
    title: 'Find All People With Secret',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/find-all-people-with-secret/',
    notes: 'Group meetings by timestamp, Union-Find people sharing secret, and reset non-secret roots.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graphs',
    patternId: 'pattern.union-find',
    patternSlug: 'union-find',
    patternTitle: 'Union-Find (Disjoint Set Union)',
    questTitle: 'Quest: The Unifying Bond',
    kingdomTitle: 'Shadow Forest',
  },
];
