import { ProblemModel } from '../../types';

export const GREEDY_PROBLEMS: ProblemModel[] = [
  // 1. Interval & Array Greedy
  {
    id: 'lc-55',
    slug: 'jump-game',
    leetcodeNumber: 55,
    title: 'Jump Game',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Greedy'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/jump-game/',
    notes: 'Greedy maxReachable index tracking max(maxReachable, i + nums[i]).',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-45',
    slug: 'jump-game-ii',
    leetcodeNumber: 45,
    title: 'Jump Game II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Greedy'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/jump-game-ii/',
    notes: 'BFS window expansion incrementing jumps when reaching current window boundary.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-134',
    slug: 'gas-station',
    leetcodeNumber: 134,
    title: 'Gas Station',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Greedy'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/gas-station/',
    notes: 'Total net gas check + reset starting index whenever current Tank < 0.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-605',
    slug: 'can-place-flowers',
    leetcodeNumber: 605,
    title: 'Can Place Flowers',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 29.0,
    isPremium: false,
    topics: ['Array', 'Greedy'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/can-place-flowers/',
    notes: 'Greedy placement if prev, curr, and next cells are all 0.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-860',
    slug: 'lemonade-change',
    leetcodeNumber: 860,
    title: 'Lemonade Change',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Greedy'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/lemonade-change/',
    notes: 'Greedy change return: prefer giving $10 + $5 over three $5 bills for a $20 bill.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1005',
    slug: 'maximize-sum-of-array-after-k-negations',
    leetcodeNumber: 1005,
    title: 'Maximize Sum Of Array After K Negations',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximize-sum-of-array-after-k-negations/',
    notes: 'Flip largest negative numbers first; if K remains odd, flip smallest positive.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },

  // 2. Greedy with Sorting & Priority Queue
  {
    id: 'lc-409',
    slug: 'longest-palindrome',
    leetcodeNumber: 409,
    title: 'Longest Palindrome',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Greedy'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/longest-palindrome/',
    notes: 'Sum even frequency pairs + at most one odd center character.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-763-g',
    slug: 'partition-labels-greedy',
    leetcodeNumber: 763,
    title: 'Partition Labels (Greedy)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 79.0,
    isPremium: false,
    topics: ['Hash Table', 'Two Pointers', 'String', 'Greedy'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/partition-labels/',
    notes: 'Expand current partition end pointer to max(lastOccurrences of chars seen).',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-406',
    slug: 'queue-reconstruction-by-height',
    leetcodeNumber: 406,
    title: 'Queue Reconstruction by Height',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 73.0,
    isPremium: false,
    topics: ['Array', 'Binary Indexed Tree', 'Segment Tree', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/queue-reconstruction-by-height/',
    notes: 'Sort people by height desc then k asc; insert person into result list at index k.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-659',
    slug: 'split-array-into-consecutive-subsequences',
    leetcodeNumber: 659,
    title: 'Split Array into Consecutive Subsequences',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Greedy', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/split-array-into-consecutive-subsequences/',
    notes: 'Frequency map + tail map tracking available consecutive sequences of length >= 3.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },

  // 3. String & Numeric Greedy
  {
    id: 'lc-68',
    slug: 'text-justification',
    leetcodeNumber: 68,
    title: 'Text Justification',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Array', 'String', 'Simulation'],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/text-justification/',
    notes: 'Greedy line packing + even space distribution / left justification logic.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-sorting',
    patternSlug: 'greedy-sorting',
    patternTitle: 'String & Numeric Greedy',
    questTitle: 'Quest: The Greedy Scribe',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1578',
    slug: 'minimum-time-to-make-rope-colorful',
    leetcodeNumber: 1578,
    title: 'Minimum Time to Make Rope Colorful',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Array', 'String', 'Dynamic Programming', 'Greedy'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/minimum-time-to-make-rope-colorful/',
    notes: 'For consecutive duplicate colors, delete all balloons except one with max cost.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-sorting',
    patternSlug: 'greedy-sorting',
    patternTitle: 'String & Numeric Greedy',
    questTitle: 'Quest: The Greedy Scribe',
    kingdomTitle: "The Merchant's Gambit",
  },

  // 4. Advanced Scheduling & Resource Allocation
  {
    id: 'lc-502',
    slug: 'ipo',
    leetcodeNumber: 502,
    title: 'IPO',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting', 'Heap'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/ipo/',
    notes: 'Min-Heap of projects sorted by capital + Max-Heap of projects by profit.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-graph-scheduling',
    patternSlug: 'greedy-graph-scheduling',
    patternTitle: 'Advanced Scheduling & Resource Allocation',
    questTitle: "Quest: The Grand Auction",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-135-g',
    slug: 'candy-greedy',
    leetcodeNumber: 135,
    title: 'Candy (Greedy Peak Distribution)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Greedy'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/candy/',
    notes: 'Single pass peak and slope counting algorithm for O(1) space.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-graph-scheduling',
    patternSlug: 'greedy-graph-scheduling',
    patternTitle: 'Advanced Scheduling & Resource Allocation',
    questTitle: "Quest: The Grand Auction",
    kingdomTitle: "The Merchant's Gambit",
  },

  {
    id: 'lc-646',
    slug: 'maximum-length-of-pair-chain',
    leetcodeNumber: 646,
    title: 'Maximum Length of Pair Chain',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Greedy', 'Sorting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-length-of-pair-chain/',
    notes: 'Sort pairs by end time; pick next pair if start > current end.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1710',
    slug: 'maximum-units-on-a-truck',
    leetcodeNumber: 1710,
    title: 'Maximum Units on a Truck',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-units-on-a-truck/',
    notes: 'Sort boxTypes by unitsPerBox descending, greedily take max available boxes.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1793',
    slug: 'maximum-score-of-a-good-subarray',
    leetcodeNumber: 1793,
    title: 'Maximum Score of a Good Subarray',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-score-of-a-good-subarray/',
    notes: 'Two pointer expanding outward from index k moving towards larger adjacent value.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1871',
    slug: 'jump-game-vii',
    leetcodeNumber: 1871,
    title: 'Jump Game VII',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 25.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming', 'Sliding Window', 'Prefix Sum'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/jump-game-vii/',
    notes: 'DP + sliding window / max reachable index bound tracking.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.interval-greedy',
    patternSlug: 'interval-greedy',
    patternTitle: 'Interval & Array Greedy',
    questTitle: "Quest: The Merchant's Choice",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1899',
    slug: 'merge-triplets-to-form-target-triplet',
    leetcodeNumber: 1899,
    title: 'Merge Triplets to Form Target Triplet',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Array', 'Greedy'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',
    notes: 'Filter valid triplets where t[0]<=target[0] && t[1]<=target[1] && t[2]<=target[2].',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-871',
    slug: 'minimum-number-of-refueling-stops',
    leetcodeNumber: 871,
    title: 'Minimum Number of Refueling Stops',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Greedy', 'Heap'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/minimum-number-of-refueling-stops/',
    notes: 'Max-Heap of passed gas stations refueling greedily when fuel depletes.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-graph-scheduling',
    patternSlug: 'greedy-graph-scheduling',
    patternTitle: 'Advanced Scheduling & Resource Allocation',
    questTitle: "Quest: The Grand Auction",
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1647',
    slug: 'minimum-deletions-to-make-character-frequencies-unique',
    leetcodeNumber: 1647,
    title: 'Minimum Deletions to Make Character Frequencies Unique',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Greedy', 'Sorting'],
    companies: ['Microsoft'],
    url: 'https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/',
    notes: 'HashSet tracking taken frequencies, decrementing duplicates until unique or 0.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-sorting',
    patternSlug: 'greedy-sorting',
    patternTitle: 'String & Numeric Greedy',
    questTitle: 'Quest: The Greedy Scribe',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1754',
    slug: 'largest-merge-of-two-strings',
    leetcodeNumber: 1754,
    title: 'Largest Merge Of Two Strings',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Two Pointers', 'String', 'Greedy'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/largest-merge-of-two-strings/',
    notes: 'Greedily append character from string with larger lexicographical suffix.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-sorting',
    patternSlug: 'greedy-sorting',
    patternTitle: 'String & Numeric Greedy',
    questTitle: 'Quest: The Greedy Scribe',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1775',
    slug: 'equal-sum-arrays-with-minimum-number-of-operations',
    leetcodeNumber: 1775,
    title: 'Equal Sum Arrays With Minimum Number of Operations',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Greedy', 'Counting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/equal-sum-arrays-with-minimum-number-of-operations/',
    notes: 'Count available gain operations (6 - num for smaller, num - 1 for larger) in frequency array.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1881',
    slug: 'maximum-value-after-insertion',
    leetcodeNumber: 1881,
    title: 'Maximum Value after Insertion',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Low',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['String', 'Greedy'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/maximum-value-after-insertion/',
    notes: 'For positive number insert digit before first smaller digit; for negative insert before first larger.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-sorting',
    patternSlug: 'greedy-sorting',
    patternTitle: 'String & Numeric Greedy',
    questTitle: 'Quest: The Greedy Scribe',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-1903',
    slug: 'largest-odd-number-in-string',
    leetcodeNumber: 1903,
    title: 'Largest Odd Number in String',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Math', 'String', 'Greedy'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/largest-odd-number-in-string/',
    notes: 'Scan string right-to-left returning prefix up to last odd digit.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.greedy-sorting',
    patternSlug: 'greedy-sorting',
    patternTitle: 'String & Numeric Greedy',
    questTitle: 'Quest: The Greedy Scribe',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-2144',
    slug: 'minimum-cost-of-buying-candies-with-discount',
    leetcodeNumber: 2144,
    title: 'Minimum Cost of Buying Candies With Discount',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimum-cost-of-buying-candies-with-discount/',
    notes: 'Sort descending, pay for first 2 in every triplet, take 3rd free.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
  {
    id: 'lc-2224',
    slug: 'minimum-number-of-operations-to-convert-time',
    leetcodeNumber: 2224,
    title: 'Minimum Number of Operations to Convert Time',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['String', 'Greedy'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimum-number-of-operations-to-convert-time/',
    notes: 'Convert difference to minutes and greedily divide by 60, 15, 5, 1.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    patternId: 'pattern.array-greedy',
    patternSlug: 'array-greedy',
    patternTitle: 'Greedy with Sorting & Priority Queue',
    questTitle: 'Quest: The Optimal Harvest',
    kingdomTitle: "The Merchant's Gambit",
  },
];
