import { ProblemModel } from '../../types';

export const HASHING_PROBLEMS: ProblemModel[] = [
  // 1. HashMap Frequency Counting
  {
    id: 'lc-242',
    slug: 'valid-anagram',
    leetcodeNumber: 242,
    title: 'Valid Anagram',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sorting'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/valid-anagram/',
    notes: '26-element frequency count comparison.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-387',
    slug: 'first-unique-character-in-a-string',
    leetcodeNumber: 387,
    title: 'First Unique Character in a String',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 66.1,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Queue'],
    companies: ['Adobe', 'Meta'],
    url: 'https://leetcode.com/problems/first-unique-character-in-a-string/',
    notes: 'Character frequency pass then find first count == 1 index.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-349',
    slug: 'intersection-of-two-arrays',
    leetcodeNumber: 349,
    title: 'Intersection of Two Arrays',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 21,
    xp: 50,
    acceptanceRate: 75.8,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Two Pointers', 'Binary Search', 'Sorting'],
    companies: ['Apple', 'Meta', 'Salesforce'],
    url: 'https://leetcode.com/problems/intersection-of-two-arrays/',
    notes: 'HashSet lookup for common elements in two arrays.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-706',
    slug: 'design-hashmap',
    leetcodeNumber: 706,
    title: 'Design HashMap',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 17,
    xp: 50,
    acceptanceRate: 63.7,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Linked List', 'Design', 'Hash Function'],
    companies: ['Oracle', 'Goldman Sachs', 'Salesforce'],
    url: 'https://leetcode.com/problems/design-hashmap/',
    notes: 'Implement separate chaining using LinkedList bucket array.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-49',
    slug: 'group-anagrams',
    leetcodeNumber: 49,
    title: 'Group Anagrams',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 33,
    xp: 100,
    acceptanceRate: 56.1,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Sorting'],
    companies: ['LinkedIn', 'Oracle', 'Microsoft'],
    url: 'https://leetcode.com/problems/group-anagrams/',
    notes: 'Group strings by sorted character key or char count tuple in HashMap.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-1657',
    slug: 'determine-if-two-strings-are-close',
    leetcodeNumber: 1657,
    title: 'Determine if Two Strings Are Close',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sorting'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/determine-if-two-strings-are-close/',
    notes: 'Compare character sets and sorted frequency counts.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-454',
    slug: '4sum-ii',
    leetcodeNumber: 454,
    title: '4Sum II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/4sum-ii/',
    notes: 'Store A+B sums in HashMap then lookup -(C+D) sums.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-128',
    slug: 'longest-consecutive-sequence',
    leetcodeNumber: 128,
    title: 'Longest Consecutive Sequence',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 47.1,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Union-Find'],
    companies: ['Meta', 'Salesforce', 'Bloomberg'],
    url: 'https://leetcode.com/problems/longest-consecutive-sequence/',
    notes: 'HashSet sequence building starting only from sequence start numbers (num-1 not in set).',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashmap-frequency',
    patternSlug: 'hashmap-frequency',
    patternTitle: 'HashMap Frequency Counting',
    questTitle: 'Quest: The Tally Chamber',
    kingdomTitle: 'The Cipher Vaults',
  },

  // 2. Set-Based Lookup
  {
    id: 'lc-705',
    slug: 'design-hashset',
    leetcodeNumber: 705,
    title: 'Design HashSet',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Linked List', 'Design', 'Hash Function'],
    companies: ['Apple', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/design-hashset/',
    notes: 'Implement custom hash set with bucket chaining.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.set-lookup',
    patternSlug: 'set-lookup',
    patternTitle: 'Set-Based Lookup',
    questTitle: 'Quest: The Vault of Presence',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-781',
    slug: 'rabbits-in-forest',
    leetcodeNumber: 781,
    title: 'Rabbits in Forest',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Hash Table', 'Math', 'Greedy'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/rabbits-in-forest/',
    notes: 'Group identical answer frequencies ceiling ceil(count / (ans + 1)) * (ans + 1).',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.set-lookup',
    patternSlug: 'set-lookup',
    patternTitle: 'Set-Based Lookup',
    questTitle: 'Quest: The Vault of Presence',
    kingdomTitle: 'The Cipher Vaults',
  },

  // 3. Hashing with Design
  {
    id: 'lc-146',
    slug: 'lru-cache',
    leetcodeNumber: 146,
    title: 'LRU Cache',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 100,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List', 'Design', 'Doubly-Linked List'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
    url: 'https://leetcode.com/problems/lru-cache/',
    notes: 'Combine HashMap for O(1) key lookup with Doubly LinkedList for O(1) recency moves.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashing-design',
    patternSlug: 'hashing-design',
    patternTitle: 'Hashing with Design',
    questTitle: 'Quest: The Cipher Architect',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-981',
    slug: 'time-based-key-value-store',
    leetcodeNumber: 981,
    title: 'Time Based Key-Value Store',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Binary Search', 'Design'],
    companies: ['Meta', 'Netflix', 'Google'],
    url: 'https://leetcode.com/problems/time-based-key-value-store/',
    notes: 'HashMap key -> Array of (timestamp, value) pairs + Binary Search.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashing-design',
    patternSlug: 'hashing-design',
    patternTitle: 'Hashing with Design',
    questTitle: 'Quest: The Cipher Architect',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-460',
    slug: 'lfu-cache',
    leetcodeNumber: 460,
    title: 'LFU Cache',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List', 'Design', 'Doubly-Linked List'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/lfu-cache/',
    notes: 'HashMap for key lookup + HashMap for frequency -> Doubly LinkedList of nodes.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashing-design',
    patternSlug: 'hashing-design',
    patternTitle: 'Hashing with Design',
    questTitle: 'Quest: The Cipher Architect',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-432',
    slug: 'all-oone-data-structure',
    leetcodeNumber: 432,
    title: 'All O`one Data Structure',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List', 'Design', 'Doubly-Linked List'],
    companies: ['Uber', 'Google', 'Amazon'],
    url: 'https://leetcode.com/problems/all-oone-data-structure/',
    notes: 'Doubly LinkedList of frequency buckets with HashSets of keys.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.hashing-design',
    patternSlug: 'hashing-design',
    patternTitle: 'Hashing with Design',
    questTitle: 'Quest: The Cipher Architect',
    kingdomTitle: 'The Cipher Vaults',
  },

  // 4. Hashing in Arrays & Strings
  {
    id: 'lc-1189',
    slug: 'maximum-number-of-balloons',
    leetcodeNumber: 1189,
    title: 'Maximum Number of Balloons',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Counting'],
    companies: ['Tesla', 'Amazon'],
    url: 'https://leetcode.com/problems/maximum-number-of-balloons/',
    notes: 'Char frequency count divided by balloon requirements (l and o divided by 2).',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-205',
    slug: 'isomorphic-strings',
    leetcodeNumber: 205,
    title: 'Isomorphic Strings',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 19,
    xp: 50,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Hash Table', 'String'],
    companies: ['LinkedIn', 'Amazon'],
    url: 'https://leetcode.com/problems/isomorphic-strings/',
    notes: 'Bi-directional HashMap character mapping validation.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-1002',
    slug: 'find-common-characters',
    leetcodeNumber: 1002,
    title: 'Find Common Characters',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/find-common-characters/',
    notes: 'Min frequency array reduction across all input words.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-1207',
    slug: 'unique-number-of-occurrences',
    leetcodeNumber: 1207,
    title: 'Unique Number of Occurrences',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/unique-number-of-occurrences/',
    notes: 'Frequency HashMap count into HashSet uniqueness size check.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-347',
    slug: 'top-k-frequent-elements',
    leetcodeNumber: 347,
    title: 'Top K Frequent Elements',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Divide and Conquer', 'Sorting', 'Heap', 'Bucket Sort', 'Counting', 'Quickselect'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/top-k-frequent-elements/',
    notes: 'Frequency map + Bucket Sort or Min-Heap of size K.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-966',
    slug: 'vowel-spellchecker',
    leetcodeNumber: 966,
    title: 'Vowel Spellchecker',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/vowel-spellchecker/',
    notes: 'Three HashMaps for exact match, case-insensitive, and vowel-masked matches.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
  {
    id: 'lc-535',
    slug: 'encode-and-decode-tinyurl',
    leetcodeNumber: 535,
    title: 'Encode and Decode TinyURL',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 85.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Design', 'Hash Function'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/encode-and-decode-tinyurl/',
    notes: 'Base62 encoding / random hash string key generation.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    patternId: 'pattern.marked-ledger-hashing',
    patternSlug: 'marked-ledger-hashing',
    patternTitle: 'Hashing in Arrays & Strings',
    questTitle: 'Quest: The Marked Ledger',
    kingdomTitle: 'The Cipher Vaults',
  },
];
