import { ProblemModel } from '../../types';

export const HEAP_PROBLEMS: ProblemModel[] = [
  // 1. Top-K Elements & Heap Fundamentals
  {
    id: 'lc-703',
    slug: 'kth-largest-element-in-a-stream',
    leetcodeNumber: 703,
    title: 'Kth Largest Element in a Stream',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Tree', 'Design', 'Binary Search Tree', 'Heap', 'Binary Tree', 'Data Stream'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/',
    notes: 'Maintain Min-Heap of size K returning heap peek value.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1046',
    slug: 'last-stone-weight',
    leetcodeNumber: 1046,
    title: 'Last Stone Weight',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Array', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/last-stone-weight/',
    notes: 'Max-Heap popping two largest stones and pushing back absolute difference.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-692',
    slug: 'top-k-frequent-words',
    leetcodeNumber: 692,
    title: 'Top K Frequent Words',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Trie', 'Sorting', 'Heap', 'Bucket Sort', 'Counting', 'Quickselect'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/top-k-frequent-words/',
    notes: 'Custom comparator Heap: frequency ascending then string descending for Min-Heap of size K.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-373',
    slug: 'find-k-pairs-with-smallest-sums',
    leetcodeNumber: 373,
    title: 'Find K Pairs with Smallest Sums',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['Array', 'Heap'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/',
    notes: 'Min-Heap storing tuples (nums1[i] + nums2[j], i, j) advancing j+1.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },

  // 2. Two-Heap Technique (Median Streams)
  {
    id: 'lc-295',
    slug: 'find-median-from-data-stream',
    leetcodeNumber: 295,
    title: 'Find Median from Data Stream',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Two Pointers', 'Design', 'Sorting', 'Heap', 'Data Stream'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/find-median-from-data-stream/',
    notes: 'Max-Heap for lower half + Min-Heap for upper half balanced sizes.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.two-heap',
    patternSlug: 'two-heap',
    patternTitle: 'Two-Heap Technique (Median Streams)',
    questTitle: 'Quest: The Dual Balance',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-480',
    slug: 'sliding-window-median',
    leetcodeNumber: 480,
    title: 'Sliding Window Median',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sliding Window', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/sliding-window-median/',
    notes: 'Two heaps with lazy invalid element removal HashMap.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.two-heap',
    patternSlug: 'two-heap',
    patternTitle: 'Two-Heap Technique (Median Streams)',
    questTitle: 'Quest: The Dual Balance',
    kingdomTitle: 'The Summit Fortress',
  },

  // 3. Heap for Task & Event Scheduling
  {
    id: 'lc-1834',
    slug: 'single-threaded-cpu',
    leetcodeNumber: 1834,
    title: 'Single-Threaded CPU',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Sorting', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/single-threaded-cpu/',
    notes: 'Sort tasks by enqueue time + Min-Heap ordered by processing time.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1353',
    slug: 'maximum-number-of-events-that-can-be-attended',
    leetcodeNumber: 1353,
    title: 'Maximum Number of Events That Can Be Attended',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 33.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/',
    notes: 'Day by day simulation adding active event end times to Min-Heap.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },

  // 4. Advanced Heap Design & Simulation
  {
    id: 'lc-218-h',
    slug: 'the-skyline-problem-heap',
    leetcodeNumber: 218,
    title: 'The Skyline Problem (Priority Queue)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Line Sweep', 'Heap', 'Ordered Set'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/the-skyline-problem/',
    notes: 'Max-Heap tracking active building heights on x-coordinate sweep.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-design-simulation',
    patternSlug: 'heap-design-simulation',
    patternTitle: 'Advanced Heap Design & Simulation',
    questTitle: 'Quest: The Summit Sentinel',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1675',
    slug: 'minimize-deviation-in-array',
    leetcodeNumber: 1675,
    title: 'Minimize Deviation in Array',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Heap', 'Ordered Set'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimize-deviation-in-array/',
    notes: 'Double odd numbers, push to Max-Heap, track minVal and pop/divide even numbers.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-design-simulation',
    patternSlug: 'heap-design-simulation',
    patternTitle: 'Advanced Heap Design & Simulation',
    questTitle: 'Quest: The Summit Sentinel',
    kingdomTitle: 'The Summit Fortress',
  },

  {
    id: 'lc-767',
    slug: 'reorganize-string',
    leetcodeNumber: 767,
    title: 'Reorganize String',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Greedy', 'Sorting', 'Heap', 'Counting'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/reorganize-string/',
    notes: 'Max-Heap of character frequencies alternating top 2 elements.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1057',
    slug: 'campus-bikes',
    leetcodeNumber: 1057,
    title: 'Campus Bikes',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: true,
    topics: ['Array', 'Greedy', 'Sorting', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/campus-bikes/',
    notes: 'Min-Heap / Bucket sort on (Manhattan distance, workerIdx, bikeIdx) pairs.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1086',
    slug: 'high-five',
    leetcodeNumber: 1086,
    title: 'High Five',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 78.0,
    isPremium: true,
    topics: ['Array', 'Hash Table', 'Sorting', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/high-five/',
    notes: 'TreeMap studentId -> Min-Heap of top 5 scores.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1405',
    slug: 'longest-happy-string',
    leetcodeNumber: 1405,
    title: 'Longest Happy String',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['String', 'Greedy', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/longest-happy-string/',
    notes: 'Max-Heap of available a, b, c character counts building string greedily.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-design-simulation',
    patternSlug: 'heap-design-simulation',
    patternTitle: 'Advanced Heap Design & Simulation',
    questTitle: 'Quest: The Summit Sentinel',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1792',
    slug: 'maximum-average-pass-ratio',
    leetcodeNumber: 1792,
    title: 'Maximum Average Pass Ratio',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-average-pass-ratio/',
    notes: 'Max-Heap ordered by potential gain delta (pass+1)/(total+1) - pass/total.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1882',
    slug: 'process-tasks-using-servers',
    leetcodeNumber: 1882,
    title: 'Process Tasks Using Servers',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Array', 'Heap'],
    companies: ['Uber'],
    url: 'https://leetcode.com/problems/process-tasks-using-servers/',
    notes: 'Two Min-Heaps: freeServers (weight, index) and busyServers (freeTime, weight, index).',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1942',
    slug: 'the-number-of-the-smallest-unoccupied-chair',
    leetcodeNumber: 1942,
    title: 'The Number of the Smallest Unoccupied Chair',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/the-number-of-the-smallest-unoccupied-chair/',
    notes: 'Min-Heap of available chair indices + Min-Heap of leaving friends.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-1962',
    slug: 'remove-stones-to-minimize-the-total',
    leetcodeNumber: 1962,
    title: 'Remove Stones to Minimize the Total',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/remove-stones-to-minimize-the-total/',
    notes: 'Max-Heap popping largest pile K times and pushing floor(val / 2).',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-2208',
    slug: 'minimum-operations-to-halve-array-sum',
    leetcodeNumber: 2208,
    title: 'Minimum Operations to Halve Array Sum',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimum-operations-to-halve-array-sum/',
    notes: 'Max-Heap popping largest double value and halving until sum reduction target is met.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-2402-h',
    slug: 'meeting-rooms-iii-heap',
    leetcodeNumber: 2402,
    title: 'Meeting Rooms III (Priority Queue Scheduling)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sorting', 'Heap'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/meeting-rooms-iii/',
    notes: 'Two priority queues maintaining available room IDs and active end times.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.heap-scheduling',
    patternSlug: 'heap-scheduling',
    patternTitle: 'Heap for Task & Event Scheduling',
    questTitle: 'Quest: The Task Master',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-2462',
    slug: 'total-cost-to-hire-k-workers',
    leetcodeNumber: 2462,
    title: 'Total Cost to Hire K Workers',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/total-cost-to-hire-k-workers/',
    notes: 'Two Min-Heaps (first candidates and last candidates) selecting cheapest worker.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.two-heap',
    patternSlug: 'two-heap',
    patternTitle: 'Two-Heap Technique (Median Streams)',
    questTitle: 'Quest: The Dual Balance',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-2542',
    slug: 'maximum-subsequence-score',
    leetcodeNumber: 2542,
    title: 'Maximum Subsequence Score',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting', 'Heap'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-subsequence-score/',
    notes: 'Sort pair tuples by nums2 descending + Min-Heap of size K for nums1 sum.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
  {
    id: 'lc-2558',
    slug: 'take-gifts-from-the-richest-pile',
    leetcodeNumber: 2558,
    title: 'Take Gifts From the Richest Pile',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Array', 'Heap', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/take-gifts-from-the-richest-pile/',
    notes: 'Max-Heap popping largest pile k times and pushing floor(sqrt(val)).',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap',
    patternId: 'pattern.top-k-elements',
    patternSlug: 'top-k-elements',
    patternTitle: 'Top-K Elements & Heap Fundamentals',
    questTitle: 'Quest: The Peak Pinnacle',
    kingdomTitle: 'The Summit Fortress',
  },
];
