import { ProblemModel } from '../../types';

export const INTERVALS_PROBLEMS: ProblemModel[] = [
  // 1. Merge Intervals
  {
    id: 'lc-56-int',
    slug: 'merge-intervals-standard',
    leetcodeNumber: 56,
    title: 'Merge Intervals (Standard)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Array', 'Sorting'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/merge-intervals/',
    notes: 'Sort intervals by start time then merge overlapping end times.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.merge-intervals',
    patternSlug: 'merge-intervals',
    patternTitle: 'Merge Intervals',
    questTitle: 'Quest: The Fused Timelines',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-57',
    slug: 'insert-interval',
    leetcodeNumber: 57,
    title: 'Insert Interval',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Array'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/insert-interval/',
    notes: '3-stage single pass: left non-overlapping, merge overlapping, right non-overlapping.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.merge-intervals',
    patternSlug: 'merge-intervals',
    patternTitle: 'Merge Intervals',
    questTitle: 'Quest: The Fused Timelines',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-759',
    slug: 'employee-free-time',
    leetcodeNumber: 759,
    title: 'Employee Free Time',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 72.0,
    isPremium: true,
    topics: ['Array', 'Sorting', 'Heap'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/employee-free-time/',
    notes: 'Merge all working intervals then extract gap intervals.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.merge-intervals',
    patternSlug: 'merge-intervals',
    patternTitle: 'Merge Intervals',
    questTitle: 'Quest: The Fused Timelines',
    kingdomTitle: 'The Timeline Kingdom',
  },

  // 2. Interval Scheduling & Overlaps
  {
    id: 'lc-435',
    slug: 'non-overlapping-intervals',
    leetcodeNumber: 435,
    title: 'Non-overlapping Intervals',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/non-overlapping-intervals/',
    notes: 'Sort intervals by end time and greedily pick earliest ending non-overlapping interval.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-scheduling',
    patternSlug: 'interval-scheduling',
    patternTitle: 'Interval Scheduling & Overlaps',
    questTitle: 'Quest: The Conflict Resolver',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-252',
    slug: 'meeting-rooms',
    leetcodeNumber: 252,
    title: 'Meeting Rooms',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 57.0,
    isPremium: true,
    topics: ['Array', 'Sorting'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/meeting-rooms/',
    notes: 'Sort intervals and check adjacent overlap start[i] < end[i-1].',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-scheduling',
    patternSlug: 'interval-scheduling',
    patternTitle: 'Interval Scheduling & Overlaps',
    questTitle: 'Quest: The Conflict Resolver',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-253',
    slug: 'meeting-rooms-ii',
    leetcodeNumber: 253,
    title: 'Meeting Rooms II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: true,
    topics: ['Array', 'Two Pointers', 'Greedy', 'Sorting', 'Heap'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/meeting-rooms-ii/',
    notes: 'Min-Heap of end times or separate start/end time sorted arrays.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-scheduling',
    patternSlug: 'interval-scheduling',
    patternTitle: 'Interval Scheduling & Overlaps',
    questTitle: 'Quest: The Conflict Resolver',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-452',
    slug: 'minimum-number-of-arrows-to-burst-balloons',
    leetcodeNumber: 452,
    title: 'Minimum Number of Arrows to Burst Balloons',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Sorting'],
    companies: ['Meta', 'Google'],
    url: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/',
    notes: 'Greedy arrow placement at min(end) of overlapping intervals.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-scheduling',
    patternSlug: 'interval-scheduling',
    patternTitle: 'Interval Scheduling & Overlaps',
    questTitle: 'Quest: The Conflict Resolver',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-1288',
    slug: 'remove-covered-intervals',
    leetcodeNumber: 1288,
    title: 'Remove Covered Intervals',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/remove-covered-intervals/',
    notes: 'Sort start asc then end desc; track max end seen so far.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-scheduling',
    patternSlug: 'interval-scheduling',
    patternTitle: 'Interval Scheduling & Overlaps',
    questTitle: 'Quest: The Conflict Resolver',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-1272',
    slug: 'remove-interval',
    leetcodeNumber: 1272,
    title: 'Remove Interval',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 64.0,
    isPremium: true,
    topics: ['Array'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/remove-interval/',
    notes: 'Single pass interval splitting around removeInterval bounds.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-scheduling',
    patternSlug: 'interval-scheduling',
    patternTitle: 'Interval Scheduling & Overlaps',
    questTitle: 'Quest: The Conflict Resolver',
    kingdomTitle: 'The Timeline Kingdom',
  },

  // 3. Line Sweep & Point Events
  {
    id: 'lc-218',
    slug: 'the-skyline-problem',
    leetcodeNumber: 218,
    title: 'The Skyline Problem',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Line Sweep', 'Heap', 'Ordered Set'],
    companies: ['Google', 'Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/the-skyline-problem/',
    notes: 'Sweep line algorithm pushing/popping heights on building start/end events.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.sweep-line',
    patternSlug: 'sweep-line',
    patternTitle: 'Line Sweep & Point Events',
    questTitle: 'Quest: The Horizon Sweep',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-1851',
    slug: 'minimum-interval-to-include-each-query',
    leetcodeNumber: 1851,
    title: 'Minimum Interval to Include Each Query',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Sorting', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/',
    notes: 'Sort queries & intervals + Min-Heap storing active interval lengths.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.sweep-line',
    patternSlug: 'sweep-line',
    patternTitle: 'Line Sweep & Point Events',
    questTitle: 'Quest: The Horizon Sweep',
    kingdomTitle: 'The Timeline Kingdom',
  },

  // 4. Advanced Interval Design
  {
    id: 'lc-731',
    slug: 'my-calendar-ii',
    leetcodeNumber: 731,
    title: 'My Calendar II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Design', 'Segment Tree', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/my-calendar-ii/',
    notes: 'Maintain single booking list and double booking list.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-729',
    slug: 'my-calendar-i',
    leetcodeNumber: 729,
    title: 'My Calendar I',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Design', 'Segment Tree', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/my-calendar-i/',
    notes: 'TreeMap / BST checking floor and ceiling key overlaps.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-732',
    slug: 'my-calendar-iii',
    leetcodeNumber: 732,
    title: 'My Calendar III',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 48,
    xp: 200,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Binary Search', 'Design', 'Segment Tree', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/my-calendar-iii/',
    notes: 'Difference array / TreeMap line sweep max ongoing count.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-352',
    slug: 'data-stream-as-disjoint-intervals',
    leetcodeNumber: 352,
    title: 'Data Stream as Disjoint Intervals',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['Binary Search', 'Design', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/data-stream-as-disjoint-intervals/',
    notes: 'TreeMap storing intervals [start, end] merging on new number insertion.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-616',
    slug: 'add-bold-tag-in-string',
    leetcodeNumber: 616,
    title: 'Add Bold Tag in String',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: true,
    topics: ['Array', 'Hash Table', 'String', 'Trie', 'String Matching'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/add-bold-tag-in-string/',
    notes: 'Find all matching substring interval ranges, merge overlapping, and insert bold tags.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-715',
    slug: 'range-module',
    leetcodeNumber: 715,
    title: 'Range Module',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Design', 'Segment Tree', 'Ordered Set'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/range-module/',
    notes: 'TreeMap of disjoint intervals maintaining addRange, queryRange, removeRange operations.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-2054',
    slug: 'two-best-non-overlapping-events',
    leetcodeNumber: 2054,
    title: 'Two Best Non-Overlapping Events',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Dynamic Programming', 'Sorting', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/two-best-non-overlapping-events/',
    notes: 'Sort events + suffix max value array with binary search.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-2251',
    slug: 'number-of-flowers-in-full-bloom',
    leetcodeNumber: 2251,
    title: 'Number of Flowers in Full Bloom',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Binary Search', 'Sorting', 'Prefix Sum', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/number-of-flowers-in-full-bloom/',
    notes: 'Binary search starts array and ends array: started_count - ended_count.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-2402',
    slug: 'meeting-rooms-iii',
    leetcodeNumber: 2402,
    title: 'Meeting Rooms III',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sorting', 'Heap'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/meeting-rooms-iii/',
    notes: 'Two Min-Heaps (unusedRooms and busyRooms) tracking meeting room assignments.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
  {
    id: 'lc-995',
    slug: 'minimum-number-of-k-consecutive-bit-flips',
    leetcodeNumber: 995,
    title: 'Minimum Number of K Consecutive Bit Flips',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation', 'Queue', 'Sliding Window', 'Prefix Sum'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/',
    notes: 'Difference array / sliding window tracking active flip count state.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    patternId: 'pattern.interval-design-advanced',
    patternSlug: 'interval-design-advanced',
    patternTitle: 'Advanced Interval Design',
    questTitle: 'Quest: The Chrono Architect',
    kingdomTitle: 'The Timeline Kingdom',
  },
];
