import { ProblemModel } from '../../types';

export const LINKED_LIST_PROBLEMS: ProblemModel[] = [
  // 1. Basic Linked List Manipulation
  {
    id: 'lc-206',
    slug: 'reverse-linked-list',
    leetcodeNumber: 206,
    title: 'Reverse Linked List',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['Linked List', 'Recursion'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/reverse-linked-list/',
    notes: 'Iterative 3-pointer prev/curr/next pointer reversals.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.basic-linked-list',
    patternSlug: 'basic-linked-list',
    patternTitle: 'Basic Linked List Manipulation',
    questTitle: 'Quest: The Unbroken Link',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-21',
    slug: 'merge-two-sorted-lists',
    leetcodeNumber: 21,
    title: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Linked List', 'Recursion'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    notes: 'Dummy node pointer merging of two sorted linked lists.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.basic-linked-list',
    patternSlug: 'basic-linked-list',
    patternTitle: 'Basic Linked List Manipulation',
    questTitle: 'Quest: The Unbroken Link',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-83',
    slug: 'remove-duplicates-from-sorted-list',
    leetcodeNumber: 83,
    title: 'Remove Duplicates from Sorted List',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Linked List'],
    companies: ['Adobe', 'Amazon'],
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/',
    notes: 'Bypass duplicate next nodes in sorted single pass.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.basic-linked-list',
    patternSlug: 'basic-linked-list',
    patternTitle: 'Basic Linked List Manipulation',
    questTitle: 'Quest: The Unbroken Link',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-203',
    slug: 'remove-linked-list-elements',
    leetcodeNumber: 203,
    title: 'Remove Linked List Elements',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Linked List', 'Recursion'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/remove-linked-list-elements/',
    notes: 'Dummy node pointer traversal to delete val matching nodes.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.basic-linked-list',
    patternSlug: 'basic-linked-list',
    patternTitle: 'Basic Linked List Manipulation',
    questTitle: 'Quest: The Unbroken Link',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-237',
    slug: 'delete-node-in-a-linked-list',
    leetcodeNumber: 237,
    title: 'Delete Node in a Linked List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 100,
    acceptanceRate: 78.0,
    isPremium: false,
    topics: ['Linked List'],
    companies: ['Apple', 'Microsoft'],
    url: 'https://leetcode.com/problems/delete-node-in-a-linked-list/',
    notes: 'Copy next node val to current node and bypass next node.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.basic-linked-list',
    patternSlug: 'basic-linked-list',
    patternTitle: 'Basic Linked List Manipulation',
    questTitle: 'Quest: The Unbroken Link',
    kingdomTitle: 'The Chain Islands',
  },

  // 2. Fast & Slow Pointers in Linked List
  {
    id: 'lc-234',
    slug: 'palindrome-linked-list',
    leetcodeNumber: 234,
    title: 'Palindrome Linked List',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers', 'Stack', 'Recursion'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/palindrome-linked-list/',
    notes: 'Find midpoint via fast/slow pointers, reverse second half, compare values.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.fast-slow-linked-list',
    patternSlug: 'fast-slow-linked-list',
    patternTitle: 'Fast & Slow Pointers in Linked List',
    questTitle: 'Quest: The Midpoint Discovery',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-19',
    slug: 'remove-nth-node-from-end-of-list',
    leetcodeNumber: 19,
    title: 'Remove Nth Node From End of List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
    notes: 'Two pointers N steps apart to locate target node before end.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.fast-slow-linked-list',
    patternSlug: 'fast-slow-linked-list',
    patternTitle: 'Fast & Slow Pointers in Linked List',
    questTitle: 'Quest: The Midpoint Discovery',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-160',
    slug: 'intersection-of-two-linked-lists',
    leetcodeNumber: 160,
    title: 'Intersection of Two Linked Lists',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
    notes: 'Two pointer switching heads pointerA = pointerA ? pointerA.next : headB.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.fast-slow-linked-list',
    patternSlug: 'fast-slow-linked-list',
    patternTitle: 'Fast & Slow Pointers in Linked List',
    questTitle: 'Quest: The Midpoint Discovery',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-143',
    slug: 'reorder-list',
    leetcodeNumber: 143,
    title: 'Reorder List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers', 'Stack', 'Recursion'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/reorder-list/',
    notes: 'Split at midpoint, reverse right half, merge alternating nodes.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.fast-slow-linked-list',
    patternSlug: 'fast-slow-linked-list',
    patternTitle: 'Fast & Slow Pointers in Linked List',
    questTitle: 'Quest: The Midpoint Discovery',
    kingdomTitle: 'The Chain Islands',
  },

  // 3. Advanced Linked List Structures
  {
    id: 'lc-92',
    slug: 'reverse-linked-list-ii',
    leetcodeNumber: 92,
    title: 'Reverse Linked List II',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Linked List'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/reverse-linked-list-ii/',
    notes: 'Reverse subsegment left..right in-place using dummy node.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-61',
    slug: 'rotate-list',
    leetcodeNumber: 61,
    title: 'Rotate List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/rotate-list/',
    notes: 'Connect tail to head forming circular list, break at length - (k % length).',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-82',
    slug: 'remove-duplicates-from-sorted-list-ii',
    leetcodeNumber: 82,
    title: 'Remove Duplicates from Sorted List II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/',
    notes: 'Dummy node pointer removing all nodes that have duplicate values.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-86',
    slug: 'partition-list',
    leetcodeNumber: 86,
    title: 'Partition List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/partition-list/',
    notes: 'Maintain two separate lists (less than x and greater/equal x) and combine.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-138',
    slug: 'copy-list-with-random-pointer',
    leetcodeNumber: 138,
    title: 'Copy List with Random Pointer',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
    notes: 'Interleaved cloned nodes or HashMap oldNode -> newNode mapping.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-25',
    slug: 'reverse-nodes-in-k-group',
    leetcodeNumber: 25,
    title: 'Reverse Nodes in k-Group',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Linked List', 'Recursion'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
    notes: 'Iterative / Recursive reversal of K-sized segments maintaining group connections.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-23',
    slug: 'merge-k-sorted-lists',
    leetcodeNumber: 23,
    title: 'Merge k Sorted Lists',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Linked List', 'Divide and Conquer', 'Heap', 'Merge Sort'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    notes: 'Min-Heap of size K or Divide & Conquer binary list merging.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.advanced-linked-list-structures',
    patternSlug: 'advanced-linked-list-structures',
    patternTitle: 'Advanced Linked List Structures',
    questTitle: 'Quest: The Chain Weaver',
    kingdomTitle: 'The Chain Islands',
  },

  // 4. Linked List Design & Manipulation
  {
    id: 'lc-707',
    slug: 'design-linked-list',
    leetcodeNumber: 707,
    title: 'Design Linked List',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 27.0,
    isPremium: false,
    topics: ['Linked List', 'Design'],
    companies: ['Apple', 'Amazon'],
    url: 'https://leetcode.com/problems/design-linked-list/',
    notes: 'Implement Singly or Doubly Linked List with index operations.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-445',
    slug: 'add-two-numbers-ii',
    leetcodeNumber: 445,
    title: 'Add Two Numbers II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Linked List', 'Math', 'Stack'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/add-two-numbers-ii/',
    notes: 'Use Stacks or reverse input lists to process digits without modifying lists.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-2',
    slug: 'add-two-numbers',
    leetcodeNumber: 2,
    title: 'Add Two Numbers',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Linked List', 'Math', 'Recursion'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/add-two-numbers/',
    notes: 'Digit by digit sum with carry propagation.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-430',
    slug: 'flatten-a-multilevel-doubly-linked-list',
    leetcodeNumber: 430,
    title: 'Flatten a Multilevel Doubly Linked List',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Linked List', 'Depth-First Search', 'Doubly-Linked List'],
    companies: ['Amazon', 'Bloomberg'],
    url: 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/',
    notes: 'DFS recursion or stack flattening child pointer nodes into doubly linked list.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-147',
    slug: 'insertion-sort-list',
    leetcodeNumber: 147,
    title: 'Insertion Sort List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Linked List', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/insertion-sort-list/',
    notes: 'Maintain sorted dummy head and insert current node in place.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-725',
    slug: 'split-linked-list-in-parts',
    leetcodeNumber: 725,
    title: 'Split Linked List in Parts',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Linked List'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/split-linked-list-in-parts/',
    notes: 'Calculate base size length/k and remainder length%k per segment.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-1019',
    slug: 'next-greater-node-in-linked-list',
    leetcodeNumber: 1019,
    title: 'Next Greater Node In Linked List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Linked List', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/next-greater-node-in-linked-list/',
    notes: 'Convert linked list to array or use Monotonic Stack directly.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-1669',
    slug: 'merge-in-between-linked-lists',
    leetcodeNumber: 1669,
    title: 'Merge In Between Linked Lists',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 80.0,
    isPremium: false,
    topics: ['Linked List'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/merge-in-between-linked-lists/',
    notes: 'Splice list2 into list1 replacing subsegment from index a to b.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-2181',
    slug: 'merge-nodes-in-between-zeros',
    leetcodeNumber: 2181,
    title: 'Merge Nodes in Between Zeros',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 86.0,
    isPremium: false,
    topics: ['Linked List', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/merge-nodes-in-between-zeros/',
    notes: 'Sum node values between 0-valued delimiter nodes.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-2095',
    slug: 'delete-the-middle-node-of-a-linked-list',
    leetcodeNumber: 2095,
    title: 'Delete the Middle Node of a Linked List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/',
    notes: 'Fast & slow pointer to locate prev-middle node and delete middle node.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-2130',
    slug: 'maximum-twin-sum-of-a-linked-list',
    leetcodeNumber: 2130,
    title: 'Maximum Twin Sum of a Linked List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 81.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers', 'Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-twin-sum-of-a-linked-list/',
    notes: 'Find midpoint, reverse second half, and calculate max pair sum node[i] + node[n-1-i].',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },

  {
    id: 'lc-1171',
    slug: 'remove-zero-sum-consecutive-nodes-from-linked-list',
    leetcodeNumber: 1171,
    title: 'Remove Zero Sum Consecutive Nodes from Linked List',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List'],
    companies: ['Uber', 'Amazon'],
    url: 'https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/',
    notes: 'Prefix sum HashMap mapping to purge zero-sum sub-lists.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-2074',
    slug: 'reverse-nodes-in-even-length-groups',
    leetcodeNumber: 2074,
    title: 'Reverse Nodes in Even Length Groups',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Linked List'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/reverse-nodes-in-even-length-groups/',
    notes: 'Group nodes into sizes 1, 2, 3... and reverse nodes if group actual length is even.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
  {
    id: 'lc-2816',
    slug: 'double-a-number-represented-as-a-linked-list',
    leetcodeNumber: 2816,
    title: 'Double a Number Represented as a Linked List',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Linked List', 'Math', 'Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/double-a-number-represented-as-a-linked-list/',
    notes: 'Reverse list or single pass checking if val >= 5 to set carry to next node.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    patternId: 'pattern.linked-list-design',
    patternSlug: 'linked-list-design',
    patternTitle: 'Linked List Design & Manipulation',
    questTitle: 'Quest: The Node Architect',
    kingdomTitle: 'The Chain Islands',
  },
];
