import { ProblemModel } from '../../types';

export const MATH_NUMBER_THEORY_PROBLEMS: ProblemModel[] = [
  // 1. Number Properties & Primes
  {
    id: 'lc-204',
    slug: 'count-primes',
    leetcodeNumber: 204,
    title: 'Count Primes',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 33.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Number Theory'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/count-primes/',
    notes: 'Sieve of Eratosthenes boolean array marking multiples of prime i up to n.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-9',
    slug: 'palindrome-number',
    leetcodeNumber: 9,
    title: 'Palindrome Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Math'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/palindrome-number/',
    notes: 'Reverse half of integer digits x % 10 without converting to string.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-7',
    slug: 'reverse-integer',
    leetcodeNumber: 7,
    title: 'Reverse Integer',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 28.0,
    isPremium: false,
    topics: ['Math'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/reverse-integer/',
    notes: 'Digit reversal checking 32-bit INT_MAX and INT_MIN overflow bounds.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },

  // 2. GCD, LCM & Modular Arithmetic
  {
    id: 'lc-1979',
    slug: 'find-greatest-common-divisor-of-array',
    leetcodeNumber: 1979,
    title: 'Find Greatest Common Divisor of Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 77.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Number Theory'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/find-greatest-common-divisor-of-array/',
    notes: 'Euclidean GCD algorithm gcd(a, b) = b == 0 ? a : gcd(b, a % b).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.gcd-lcm-modular-arithmetic',
    patternSlug: 'gcd-lcm-modular-arithmetic',
    patternTitle: 'GCD, LCM & Modular Arithmetic',
    questTitle: 'Quest: The Euclidean Scale',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-50',
    slug: 'powx-n',
    leetcodeNumber: 50,
    title: 'Pow(x, n)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 34.0,
    isPremium: false,
    topics: ['Math', 'Recursion'],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/powx-n/',
    notes: 'Fast exponentiation binary exponentiation O(log N).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.gcd-lcm-modular-arithmetic',
    patternSlug: 'gcd-lcm-modular-arithmetic',
    patternTitle: 'GCD, LCM & Modular Arithmetic',
    questTitle: 'Quest: The Euclidean Scale',
    kingdomTitle: 'The Numeric Sanctum',
  },

  // 3. Combinatorics & Probability
  {
    id: 'lc-62-m',
    slug: 'unique-paths-combinatorics',
    leetcodeNumber: 62,
    title: 'Unique Paths (Combinatorics Formula)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Math', 'Dynamic Programming', 'Combinatorics'],
    companies: ['LinkedIn', 'Oracle'],
    url: 'https://leetcode.com/problems/unique-paths/',
    notes: 'Compute Combination C(m+n-2, m-1) formula directly.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.combinatorics-probability',
    patternSlug: 'combinatorics-probability',
    patternTitle: 'Combinatorics & Probability',
    questTitle: 'Quest: The Permutation Forge',
    kingdomTitle: 'The Numeric Sanctum',
  },

  // 4. Geometry & Simulation
  {
    id: 'lc-149',
    slug: 'max-points-on-a-line',
    leetcodeNumber: 149,
    title: 'Max Points on a Line',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 25.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Math', 'Geometry'],
    companies: ['Google', 'Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/max-points-on-a-line/',
    notes: 'Slope dy/dx reduced by GCD mapped in HashMap for each anchor point.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.geometry-simulation',
    patternSlug: 'geometry-simulation',
    patternTitle: 'Geometry & Simulation',
    questTitle: 'Quest: The Geometric Compass',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-223',
    slug: 'rectangle-area',
    leetcodeNumber: 223,
    title: 'Rectangle Area',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Math', 'Geometry'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/rectangle-area/',
    notes: 'Area A + Area B - Overlap Area (max(0, minX2 - maxX1) * max(0, minY2 - maxY1)).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.geometry-simulation',
    patternSlug: 'geometry-simulation',
    patternTitle: 'Geometry & Simulation',
    questTitle: 'Quest: The Geometric Compass',
    kingdomTitle: 'The Numeric Sanctum',
  },

  // 5. Advanced Number Theory
  {
    id: 'lc-866',
    slug: 'prime-palindrome',
    leetcodeNumber: 866,
    title: 'Prime Palindrome',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 25.0,
    isPremium: false,
    topics: ['Math', 'Number Theory'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/prime-palindrome/',
    notes: 'Generate palindromes sequentially and test for primality using trial division.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-theory-applications',
    patternSlug: 'number-theory-applications',
    patternTitle: 'Advanced Number Theory',
    questTitle: 'Quest: The Sanctum Arcana',
    kingdomTitle: 'The Numeric Sanctum',
  },

  {
    id: 'lc-13',
    slug: 'roman-to-integer',
    leetcodeNumber: 13,
    title: 'Roman to Integer',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Hash Table', 'Math', 'String'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/roman-to-integer/',
    notes: 'If curr < next subtract curr value, else add curr value.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-12',
    slug: 'integer-to-roman',
    leetcodeNumber: 12,
    title: 'Integer to Roman',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Hash Table', 'Math', 'String'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/integer-to-roman/',
    notes: 'Greedy value mapping arrays [1000, 900, 500, 400...] and Roman symbols.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-172',
    slug: 'factorial-trailing-zeroes',
    leetcodeNumber: 172,
    title: 'Factorial Trailing Zeroes',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 100,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Math'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/factorial-trailing-zeroes/',
    notes: 'Count factors of 5 in n! (n/5 + n/25 + n/125...).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-319',
    slug: 'bulb-switcher',
    leetcodeNumber: 319,
    title: 'Bulb Switcher',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Math', 'Brainteaser'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/bulb-switcher/',
    notes: 'Only perfect square numbers have odd number of factors; return floor(sqrt(n)).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-367',
    slug: 'valid-perfect-square',
    leetcodeNumber: 367,
    title: 'Valid Perfect Square',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Math', 'Binary Search'],
    companies: ['Google', 'LinkedIn'],
    url: 'https://leetcode.com/problems/valid-perfect-square/',
    notes: 'Binary search range 1..num checking mid * mid == num.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-365',
    slug: 'water-and-jug-problem',
    leetcodeNumber: 365,
    title: 'Water and Jug Problem',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Math', 'Depth-First Search', 'Breadth-First Search'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/water-and-jug-problem/',
    notes: 'Bézouts identity: target % gcd(x, y) == 0 && target <= x + y.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.gcd-lcm-modular-arithmetic',
    patternSlug: 'gcd-lcm-modular-arithmetic',
    patternTitle: 'GCD, LCM & Modular Arithmetic',
    questTitle: 'Quest: The Euclidean Scale',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-412',
    slug: 'fizz-buzz',
    leetcodeNumber: 412,
    title: 'Fizz Buzz',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 10,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Math', 'String', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/fizz-buzz/',
    notes: 'Modulo checks 15 (FizzBuzz), 3 (Fizz), 5 (Buzz).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-441',
    slug: 'arranging-coins',
    leetcodeNumber: 441,
    title: 'Arranging Coins',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Math', 'Binary Search'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/arranging-coins/',
    notes: 'Solve quadratic equation k*(k+1)/2 <= n or Binary Search.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-453',
    slug: 'minimum-moves-to-equal-array-elements',
    leetcodeNumber: 453,
    title: 'Minimum Moves to Equal Array Elements',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Math'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimum-moves-to-equal-array-elements/',
    notes: 'Incrementing n-1 elements by 1 is equivalent to decrementing 1 element by 1; answer = sum - n*min.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-462',
    slug: 'minimum-moves-to-equal-array-elements-ii',
    leetcodeNumber: 462,
    title: 'Minimum Moves to Equal Array Elements II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Sorting', 'Quickselect'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/minimum-moves-to-equal-array-elements-ii/',
    notes: 'Target value is median of array; sum abs(nums[i] - median).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-507',
    slug: 'perfect-number',
    leetcodeNumber: 507,
    title: 'Perfect Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Low',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Math'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/perfect-number/',
    notes: 'Sum proper divisors up to sqrt(num).',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-829',
    slug: 'consecutive-numbers-sum',
    leetcodeNumber: 829,
    title: 'Consecutive Numbers Sum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Math'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/consecutive-numbers-sum/',
    notes: 'Solve N = k*x + k*(k-1)/2 checking if (N - k*(k-1)/2) % k == 0.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.combinatorics-probability',
    patternSlug: 'combinatorics-probability',
    patternTitle: 'Combinatorics & Probability',
    questTitle: 'Quest: The Permutation Forge',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-858',
    slug: 'mirror-reflection',
    leetcodeNumber: 858,
    title: 'Mirror Reflection',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Math', 'Geometry', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/mirror-reflection/',
    notes: 'Find LCM of p and q; check parity of p * m = q * n.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.geometry-simulation',
    patternSlug: 'geometry-simulation',
    patternTitle: 'Geometry & Simulation',
    questTitle: 'Quest: The Geometric Compass',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-970',
    slug: 'powerful-integers',
    leetcodeNumber: 970,
    title: 'Powerful Integers',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Low',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Hash Table', 'Math'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/powerful-integers/',
    notes: 'Double loop generating x^i + y^j <= bound into HashSet.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1017',
    slug: 'convert-to-base-2',
    leetcodeNumber: 1017,
    title: 'Convert to Base -2',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Low',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Math'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/convert-to-base-2/',
    notes: 'Base -2 division remainder handling negative mod arithmetic.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1073',
    slug: 'adding-two-negabinary-numbers',
    leetcodeNumber: 1073,
    title: 'Adding Two Negabinary Numbers',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Math'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/adding-two-negabinary-numbers/',
    notes: 'Base -2 digit by digit addition with carry tracking.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1201-m',
    slug: 'ugly-number-iii-math',
    leetcodeNumber: 1201,
    title: 'Ugly Number III (LCM Inclusion-Exclusion)',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 28.0,
    isPremium: false,
    topics: ['Math', 'Binary Search', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/ugly-number-iii/',
    notes: 'Binary search + Inclusion-Exclusion principle N = mid/a + mid/b + mid/c - mid/lcm(a,b)...',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.gcd-lcm-modular-arithmetic',
    patternSlug: 'gcd-lcm-modular-arithmetic',
    patternTitle: 'GCD, LCM & Modular Arithmetic',
    questTitle: 'Quest: The Euclidean Scale',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1250',
    slug: 'check-if-it-is-a-good-array',
    leetcodeNumber: 1250,
    title: 'Check If It Is a Good Array',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 25,
    xp: 200,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/check-if-it-is-a-good-array/',
    notes: 'Bézouts Identity: return true if GCD of entire array == 1.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.gcd-lcm-modular-arithmetic',
    patternSlug: 'gcd-lcm-modular-arithmetic',
    patternTitle: 'GCD, LCM & Modular Arithmetic',
    questTitle: 'Quest: The Euclidean Scale',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1363',
    slug: 'largest-multiple-of-three',
    leetcodeNumber: 1363,
    title: 'Largest Multiple of Three',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 33.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Dynamic Programming', 'Greedy', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/largest-multiple-of-three/',
    notes: 'Sum digits mod 3; remove 1 smallest digit with mod 1 or 2 smallest digits with mod 2.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1492',
    slug: 'the-kth-factor-of-n',
    leetcodeNumber: 1492,
    title: 'The kth Factor of n',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 100,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Math', 'Number Theory'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/the-kth-factor-of-n/',
    notes: 'Iterate 1..sqrt(n) collecting factors and complementary factors.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.number-properties',
    patternSlug: 'number-properties',
    patternTitle: 'Number Properties & Primes',
    questTitle: 'Quest: The Prime Lattice',
    kingdomTitle: 'The Numeric Sanctum',
  },
  {
    id: 'lc-1819',
    slug: 'number-of-different-subsequences-gcds',
    leetcodeNumber: 1819,
    title: 'Number of Different Subsequences GCDs',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 41.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Counting', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/number-of-different-subsequences-gcds/',
    notes: 'For each candidate GCD g 1..maxVal, compute GCD of all present multiples of g.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    patternId: 'pattern.gcd-lcm-modular-arithmetic',
    patternSlug: 'gcd-lcm-modular-arithmetic',
    patternTitle: 'GCD, LCM & Modular Arithmetic',
    questTitle: 'Quest: The Euclidean Scale',
    kingdomTitle: 'The Numeric Sanctum',
  },
];
