import { ProblemModel } from '../../types';

export const MATRIX_PROBLEMS: ProblemModel[] = [
  // 1. Matrix Traversal & Spiral Order
  {
    id: 'lc-54',
    slug: 'spiral-matrix',
    leetcodeNumber: 54,
    title: 'Spiral Matrix',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Amazon', 'Microsoft', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/spiral-matrix/',
    notes: 'Boundary pointers (top, bottom, left, right) inward spiral traversal.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-59',
    slug: 'spiral-matrix-ii',
    leetcodeNumber: 59,
    title: 'Spiral Matrix II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/spiral-matrix-ii/',
    notes: 'Generate NxN matrix in spiral order incrementing values 1..N^2.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-498',
    slug: 'diagonal-traverse',
    leetcodeNumber: 498,
    title: 'Diagonal Traverse',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/diagonal-traverse/',
    notes: 'Group matrix elements by diagonal sum r + c, flipping odd diagonals.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },

  // 2. Matrix Search & Staircase Search
  {
    id: 'lc-74-m',
    slug: 'search-a-2d-matrix-grid',
    leetcodeNumber: 74,
    title: 'Search a 2D Matrix (Grid Coordinates)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.3,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Matrix'],
    companies: ['Goldman Sachs', 'Oracle'],
    url: 'https://leetcode.com/problems/search-a-2d-matrix/',
    notes: 'Binary search mapping 1D index to row = index / cols, col = index % cols.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-search',
    patternSlug: 'matrix-search',
    patternTitle: 'Matrix Search & Staircase Search',
    questTitle: 'Quest: The Staircase Search',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-240-m',
    slug: 'search-a-2d-matrix-ii-grid',
    leetcodeNumber: 240,
    title: 'Search a 2D Matrix II (Staircase Search)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/search-a-2d-matrix-ii/',
    notes: 'Staircase pointer starting top-right (r=0, c=cols-1) in O(M+N).',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-search',
    patternSlug: 'matrix-search',
    patternTitle: 'Matrix Search & Staircase Search',
    questTitle: 'Quest: The Staircase Search',
    kingdomTitle: 'The Grid Kingdom',
  },

  // 3. Matrix Graph Traversal (DFS/BFS)
  {
    id: 'lc-200-m',
    slug: 'number-of-islands-matrix',
    leetcodeNumber: 200,
    title: 'Number of Islands (Grid Traversal)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/number-of-islands/',
    notes: '4-directional matrix DFS connected component marking.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-as-graph',
    patternSlug: 'matrix-as-graph',
    patternTitle: 'Matrix Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Grid Graph',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-130-m',
    slug: 'surrounded-regions-matrix',
    leetcodeNumber: 130,
    title: 'Surrounded Regions (Grid Graph)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Matrix'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/surrounded-regions/',
    notes: 'Boundary O cell matrix flood fill DFS.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-as-graph',
    patternSlug: 'matrix-as-graph',
    patternTitle: 'Matrix Graph Traversal (DFS/BFS)',
    questTitle: 'Quest: The Grid Graph',
    kingdomTitle: 'The Grid Kingdom',
  },

  // 4. In-Place Matrix Manipulation & Rotation
  {
    id: 'lc-48',
    slug: 'rotate-image',
    leetcodeNumber: 48,
    title: 'Rotate Image',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/rotate-image/',
    notes: 'Transpose matrix in-place (swap matrix[i][j] with matrix[j][i]) then reverse each row.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.in-place-matrix-manipulation',
    patternSlug: 'in-place-matrix-manipulation',
    patternTitle: 'In-Place Matrix Manipulation & Rotation',
    questTitle: 'Quest: The In-Place Cipher',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-73',
    slug: 'set-matrix-zeroes',
    leetcodeNumber: 73,
    title: 'Set Matrix Zeroes',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/set-matrix-zeroes/',
    notes: 'Use first row and first column as zero markers for O(1) space complexity.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.in-place-matrix-manipulation',
    patternSlug: 'in-place-matrix-manipulation',
    patternTitle: 'In-Place Matrix Manipulation & Rotation',
    questTitle: 'Quest: The In-Place Cipher',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-289',
    slug: 'game-of-life',
    leetcodeNumber: 289,
    title: 'Game of Life',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/game-of-life/',
    notes: 'Use 2-bit state flags (00, 01, 10, 11) for in-place cellular automata updates.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.in-place-matrix-manipulation',
    patternSlug: 'in-place-matrix-manipulation',
    patternTitle: 'In-Place Matrix Manipulation & Rotation',
    questTitle: 'Quest: The In-Place Cipher',
    kingdomTitle: 'The Grid Kingdom',
  },

  // 5. Matrix Construction & Transformation
  {
    id: 'lc-867',
    slug: 'transpose-matrix',
    leetcodeNumber: 867,
    title: 'Transpose Matrix',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/transpose-matrix/',
    notes: 'Construct M x N result grid setting result[j][i] = matrix[i][j].',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-construction-rotation',
    patternSlug: 'matrix-construction-rotation',
    patternTitle: 'Matrix Construction & Transformation',
    questTitle: 'Quest: The Grid Weaver',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-566',
    slug: 'reshape-the-matrix',
    leetcodeNumber: 566,
    title: 'Reshape the Matrix',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/reshape-the-matrix/',
    notes: 'Flatten 1D index i = r * cols + c and map to new R x C grid.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-construction-rotation',
    patternSlug: 'matrix-construction-rotation',
    patternTitle: 'Matrix Construction & Transformation',
    questTitle: 'Quest: The Grid Weaver',
    kingdomTitle: 'The Grid Kingdom',
  },

  {
    id: 'lc-36',
    slug: 'valid-sudoku',
    leetcodeNumber: 36,
    title: 'Valid Sudoku',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Matrix'],
    companies: ['Amazon', 'Meta', 'Apple'],
    url: 'https://leetcode.com/problems/valid-sudoku/',
    notes: 'HashSet validation for rows, columns, and 3x3 sub-boxes (boxIdx = (r/3)*3 + c/3).',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-832',
    slug: 'flipping-an-image',
    leetcodeNumber: 832,
    title: 'Flipping an Image',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 80.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Matrix', 'Simulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/flipping-an-image/',
    notes: 'Reverse each row and invert bits row[i] ^ 1.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.in-place-matrix-manipulation',
    patternSlug: 'in-place-matrix-manipulation',
    patternTitle: 'In-Place Matrix Manipulation & Rotation',
    questTitle: 'Quest: The In-Place Cipher',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1260',
    slug: 'shift-2d-grid',
    leetcodeNumber: 1260,
    title: 'Shift 2D Grid',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Low',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/shift-2d-grid/',
    notes: '1D flattened index shifting (i + k) % (m * n).',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-construction-rotation',
    patternSlug: 'matrix-construction-rotation',
    patternTitle: 'Matrix Construction & Transformation',
    questTitle: 'Quest: The Grid Weaver',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1329',
    slug: 'sort-the-matrix-diagonally',
    leetcodeNumber: 1329,
    title: 'Sort the Matrix Diagonally',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 82.0,
    isPremium: false,
    topics: ['Array', 'Sorting', 'Matrix'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/sort-the-matrix-diagonally/',
    notes: 'Group matrix elements by diagonal index r - c into HashMaps/PriorityQueues, sort and rewrite.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-construction-rotation',
    patternSlug: 'matrix-construction-rotation',
    patternTitle: 'Matrix Construction & Transformation',
    questTitle: 'Quest: The Grid Weaver',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1572',
    slug: 'matrix-diagonal-sum',
    leetcodeNumber: 1572,
    title: 'Matrix Diagonal Sum',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 82.0,
    isPremium: false,
    topics: ['Array', 'Matrix'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/matrix-diagonal-sum/',
    notes: 'Sum primary diagonal (i, i) and secondary diagonal (i, n-1-i), subtracting center if odd N.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1605',
    slug: 'find-valid-matrix-given-row-and-column-sums',
    leetcodeNumber: 1605,
    title: 'Find Valid Matrix Given Row and Column Sums',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 80.0,
    isPremium: false,
    topics: ['Array', 'Greedy', 'Matrix'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-valid-matrix-given-row-and-column-sums/',
    notes: 'Greedily set matrix[i][j] = min(rowSum[i], colSum[j]) and subtract value.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-construction-rotation',
    patternSlug: 'matrix-construction-rotation',
    patternTitle: 'Matrix Construction & Transformation',
    questTitle: 'Quest: The Grid Weaver',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1672',
    slug: 'richest-customer-wealth',
    leetcodeNumber: 1672,
    title: 'Richest Customer Wealth',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 88.0,
    isPremium: false,
    topics: ['Array', 'Matrix'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/richest-customer-wealth/',
    notes: 'Row-by-row sum accumulation tracking max row sum.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1886',
    slug: 'determine-whether-matrix-can-be-obtained-by-rotation',
    leetcodeNumber: 1886,
    title: 'Determine Whether Matrix Can Be Obtained By Rotation',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Matrix'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/',
    notes: 'Rotate matrix 90 degrees up to 4 times and check equality with target.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.in-place-matrix-manipulation',
    patternSlug: 'in-place-matrix-manipulation',
    patternTitle: 'In-Place Matrix Manipulation & Rotation',
    questTitle: 'Quest: The In-Place Cipher',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-1901',
    slug: 'find-a-peak-element-ii',
    leetcodeNumber: 1901,
    title: 'Find a Peak Element II',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Matrix'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-a-peak-element-ii/',
    notes: '2D binary search over columns finding max element in column and comparing left/right neighbors in O(N log M).',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-search',
    patternSlug: 'matrix-search',
    patternTitle: 'Matrix Search & Staircase Search',
    questTitle: 'Quest: The Staircase Search',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-2022',
    slug: 'convert-1d-array-into-2d-array',
    leetcodeNumber: 2022,
    title: 'Convert 1D Array Into 2D Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Simulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/convert-1d-array-into-2d-array/',
    notes: 'Check length == m * n, then map index i to result[i / n][i % n].',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-construction-rotation',
    patternSlug: 'matrix-construction-rotation',
    patternTitle: 'Matrix Construction & Transformation',
    questTitle: 'Quest: The Grid Weaver',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-2125',
    slug: 'number-of-laser-beams-in-a-bank',
    leetcodeNumber: 2125,
    title: 'Number of Laser Beams in a Bank',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 83.0,
    isPremium: false,
    topics: ['Array', 'Math', 'String', 'Matrix'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-laser-beams-in-a-bank/',
    notes: 'Count 1s per non-zero row, multiply consecutive non-zero row counts.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-2373',
    slug: 'largest-local-values-in-a-matrix',
    leetcodeNumber: 2373,
    title: 'Largest Local Values in a Matrix',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 84.0,
    isPremium: false,
    topics: ['Array', 'Matrix'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/largest-local-values-in-a-matrix/',
    notes: '3x3 submatrix max scan for each output cell (n-2) x (n-2).',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
  {
    id: 'lc-304-m',
    slug: 'range-sum-query-2d-immutable-matrix',
    leetcodeNumber: 304,
    title: 'Range Sum Query 2D - Immutable (Matrix Grid)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Design', 'Matrix', 'Prefix Sum'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/range-sum-query-2d-immutable/',
    notes: '2D inclusion-exclusion prefix sum matrix calculation.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    patternId: 'pattern.matrix-traversal',
    patternSlug: 'matrix-traversal',
    patternTitle: 'Matrix Traversal & Spiral Order',
    questTitle: 'Quest: The Spiral Labyrinth',
    kingdomTitle: 'The Grid Kingdom',
  },
];
