import { ProblemModel } from '../../types';

export const MINIMUM_SPANNING_TREE_PROBLEMS: ProblemModel[] = [
  // 1. Kruskal's Algorithm
  {
    id: 'lc-1584-mst',
    slug: 'min-cost-to-connect-all-points-kruskal',
    leetcodeNumber: 1584,
    title: 'Min Cost to Connect All Points (Kruskal)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Array', 'Union-Find', 'Graph', 'Minimum Spanning Tree'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
    notes: 'Kruskal MST edge sorting + Union-Find path compression.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1135',
    slug: 'connecting-cities-with-minimum-cost',
    leetcodeNumber: 1135,
    title: 'Connecting Cities With Minimum Cost',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: true,
    topics: ['Union-Find', 'Graph', 'Minimum Spanning Tree'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/connecting-cities-with-minimum-cost/',
    notes: 'Standard Kruskals MST checking connected components == 1.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1489-k',
    slug: 'find-critical-and-pseudo-critical-edges-kruskal',
    leetcodeNumber: 1489,
    title: 'Find Critical and Pseudo-Critical Edges (Kruskal)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Union-Find', 'Graph', 'Minimum Spanning Tree', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/',
    notes: 'Evaluate MST weight changes under forced/excluded edge Kruskal runs.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },

  // 2. Prim's Algorithm
  {
    id: 'lc-1584-p',
    slug: 'min-cost-to-connect-all-points-prims',
    leetcodeNumber: 1584,
    title: 'Min Cost to Connect All Points (Prim)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Array', 'Union-Find', 'Graph', 'Minimum Spanning Tree'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
    notes: 'Prims MST algorithm with Min-Heap storing minimum edge distances.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.prims-algorithm',
    patternSlug: 'prims-algorithm',
    patternTitle: "Prim's Algorithm",
    questTitle: 'Quest: The Expanding Tree',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1168',
    slug: 'optimize-water-distribution-in-a-village',
    leetcodeNumber: 1168,
    title: 'Optimize Water Distribution in a Village',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 64.0,
    isPremium: true,
    topics: ['Union-Find', 'Graph', 'Minimum Spanning Tree', 'Heap'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/optimize-water-distribution-in-a-village/',
    notes: 'Virtual node 0 representing well creation + Prims/Kruskals MST algorithm.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.prims-algorithm',
    patternSlug: 'prims-algorithm',
    patternTitle: "Prim's Algorithm",
    questTitle: 'Quest: The Expanding Tree',
    kingdomTitle: 'The Web of Kingdoms',
  },

  // 3. MST Applications
  {
    id: 'lc-1697-m',
    slug: 'checking-existence-of-edge-length-limited-paths-mst',
    leetcodeNumber: 1697,
    title: 'Checking Existence of Edge Length Limited Paths (MST)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/',
    notes: 'Offline query processing with DSU edge threshold additions.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.mst-applications',
    patternSlug: 'mst-applications',
    patternTitle: 'MST Applications',
    questTitle: 'Quest: The Network Bridge',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1579-m',
    slug: 'remove-max-number-of-edges-to-keep-graph-fully-traversable-mst',
    leetcodeNumber: 1579,
    title: 'Remove Max Number of Edges to Keep Graph Fully Traversable (MST)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Union-Find', 'Graph'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/remove-max-number-of-edges-to-keep-graph-fully-traversable/',
    notes: 'Spanning forest construction using DSU for Alice and Bob.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.mst-applications',
    patternSlug: 'mst-applications',
    patternTitle: 'MST Applications',
    questTitle: 'Quest: The Network Bridge',
    kingdomTitle: 'The Web of Kingdoms',
  },

  {
    id: 'lc-261-mst',
    slug: 'graph-valid-tree-mst',
    leetcodeNumber: 261,
    title: 'Graph Valid Tree (MST Check)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: true,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Meta', 'Google'],
    url: 'https://leetcode.com/problems/graph-valid-tree/',
    notes: 'Verify graph contains exactly N-1 edges and single connected component via DSU.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-323-mst',
    slug: 'number-of-connected-components-in-an-undirected-graph-mst',
    leetcodeNumber: 323,
    title: 'Number of Connected Components (MST)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: true,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
    notes: 'DSU tree merging counting isolated connected components.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1724',
    slug: 'checking-existence-of-edge-length-limited-paths-ii',
    leetcodeNumber: 1724,
    title: 'Checking Existence of Edge Length Limited Paths II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 50.0,
    isPremium: true,
    topics: ['Union-Find', 'Graph', 'Minimum Spanning Tree', 'Binary Search'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths-ii/',
    notes: 'Online query processing using Persistent DSU / MST LCA heavy-light decomposition.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.mst-applications',
    patternSlug: 'mst-applications',
    patternTitle: 'MST Applications',
    questTitle: 'Quest: The Network Bridge',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-2092-m',
    slug: 'find-all-people-with-secret-mst',
    leetcodeNumber: 2092,
    title: 'Find All People With Secret (MST Spanning Forest)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/find-all-people-with-secret/',
    notes: 'Time-sorted DSU spanning forest construction.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.mst-applications',
    patternSlug: 'mst-applications',
    patternTitle: 'MST Applications',
    questTitle: 'Quest: The Network Bridge',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-947-m',
    slug: 'most-stones-removed-with-same-row-or-column-mst',
    leetcodeNumber: 947,
    title: 'Most Stones Removed (MST Connected Component)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['Hash Table', 'Depth-First Search', 'Union-Find', 'Graph'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/',
    notes: 'Max stones removed = Total stones - Number of MST connected components.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1202-m',
    slug: 'smallest-string-with-swaps-mst',
    leetcodeNumber: 1202,
    title: 'Smallest String With Swaps (MST Component Sort)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/smallest-string-with-swaps/',
    notes: 'Group swap pairs using DSU spanning components.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-839-m',
    slug: 'similar-string-groups-mst',
    leetcodeNumber: 839,
    title: 'Similar String Groups (MST Components)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/similar-string-groups/',
    notes: 'DSU similarity graph components count.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1319-m',
    slug: 'number-of-operations-to-make-network-connected-mst',
    leetcodeNumber: 1319,
    title: 'Number of Operations to Make Network Connected (MST)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-operations-to-make-network-connected/',
    notes: 'Redundant edge counting to form single spanning tree.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.kruskals-algorithm',
    patternSlug: 'kruskals-algorithm',
    patternTitle: "Kruskal's Algorithm",
    questTitle: 'Quest: The Minimal Web',
    kingdomTitle: 'The Web of Kingdoms',
  },
  {
    id: 'lc-1627-m',
    slug: 'graph-connectivity-with-threshold-mst',
    leetcodeNumber: 1627,
    title: 'Graph Connectivity With Threshold (MST Multiples)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Union-Find', 'Number Theory'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/graph-connectivity-with-threshold/',
    notes: 'Number theory DSU component spanning graph.',
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    patternId: 'pattern.mst-applications',
    patternSlug: 'mst-applications',
    patternTitle: 'MST Applications',
    questTitle: 'Quest: The Network Bridge',
    kingdomTitle: 'The Web of Kingdoms',
  },
];
