import { ProblemModel } from '../../types';

export const PREFIX_SUM_PROBLEMS: ProblemModel[] = [
  // 1. Basic Prefix Sum
  {
    id: 'lc-1480',
    slug: 'running-sum-of-1d-array',
    leetcodeNumber: 1480,
    title: 'Running Sum of 1d Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 62.5,
    isPremium: false,
    topics: ['Array', 'Prefix Sum'],
    companies: ['Atlassian', 'Microsoft'],
    url: 'https://leetcode.com/problems/running-sum-of-1d-array/',
    notes: 'Single pass running sum accumulation.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1732',
    slug: 'find-the-highest-altitude',
    leetcodeNumber: 1732,
    title: 'Find the Highest Altitude',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 60.3,
    isPremium: false,
    topics: ['Array', 'Prefix Sum'],
    companies: ['Atlassian', 'Uber', 'Bloomberg', 'Oracle'],
    url: 'https://leetcode.com/problems/find-the-highest-altitude/',
    notes: 'Track max cumulative altitude gain from start.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-303',
    slug: 'range-sum-query-immutable',
    leetcodeNumber: 303,
    title: 'Range Sum Query - Immutable',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 52.9,
    isPremium: false,
    topics: ['Array', 'Design', 'Prefix Sum'],
    companies: ['LinkedIn', 'Salesforce'],
    url: 'https://leetcode.com/problems/range-sum-query-immutable/',
    notes: 'Precompute prefix sum array for O(1) range queries.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-724',
    slug: 'find-pivot-index',
    leetcodeNumber: 724,
    title: 'Find Pivot Index',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 21,
    xp: 50,
    acceptanceRate: 61.2,
    isPremium: false,
    topics: ['Array', 'Prefix Sum'],
    companies: ['LinkedIn', 'Uber'],
    url: 'https://leetcode.com/problems/find-pivot-index/',
    notes: 'Left sum == totalSum - leftSum - currentNum.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-238',
    slug: 'product-of-array-except-self',
    leetcodeNumber: 238,
    title: 'Product of Array Except Self',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 37.5,
    isPremium: false,
    topics: ['Array', 'Prefix Sum'],
    companies: ['Netflix', 'Atlassian'],
    url: 'https://leetcode.com/problems/product-of-array-except-self/',
    notes: 'Prefix products pass and suffix products pass in O(N).',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1094',
    slug: 'car-pooling',
    leetcodeNumber: 1094,
    title: 'Car Pooling',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 37,
    xp: 100,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Array', 'Sorting', 'Heap', 'Prefix Sum', 'Simulation'],
    companies: ['Google', 'Meta', 'Netflix'],
    url: 'https://leetcode.com/problems/car-pooling/',
    notes: 'Difference array / sweep line trip capacity updates.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-930',
    slug: 'binary-subarrays-with-sum',
    leetcodeNumber: 930,
    title: 'Binary Subarrays With Sum',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 29,
    xp: 100,
    acceptanceRate: 38.9,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sliding Window', 'Prefix Sum'],
    companies: ['Google', 'Goldman Sachs', 'Atlassian'],
    url: 'https://leetcode.com/problems/binary-subarrays-with-sum/',
    notes: 'Prefix sum frequency map for target binary sum.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-560',
    slug: 'subarray-sum-equals-k',
    leetcodeNumber: 560,
    title: 'Subarray Sum Equals K',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 33,
    xp: 100,
    acceptanceRate: 51.4,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Prefix Sum'],
    companies: ['Atlassian', 'Oracle'],
    url: 'https://leetcode.com/problems/subarray-sum-equals-k/',
    notes: 'Store seen prefix sum frequencies in HashMap.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-523',
    slug: 'continuous-subarray-sum',
    leetcodeNumber: 523,
    title: 'Continuous Subarray Sum',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 37,
    xp: 100,
    acceptanceRate: 41.4,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Math', 'Prefix Sum'],
    companies: ['Netflix', 'Bloomberg', 'Apple'],
    url: 'https://leetcode.com/problems/continuous-subarray-sum/',
    notes: 'HashMap storing earliest index for remainder (prefixSum % k).',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-basics',
    patternSlug: 'prefix-sum-basics',
    patternTitle: 'Basic Prefix Sum',
    questTitle: 'Quest: The Running Total',
    kingdomTitle: 'Kingdom of Accumulation',
  },

  // 2. 2D Prefix Sum
  {
    id: 'lc-304',
    slug: 'range-sum-query-2d-immutable',
    leetcodeNumber: 304,
    title: 'Range Sum Query 2D - Immutable',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 34.4,
    isPremium: false,
    topics: ['Array', 'Design', 'Matrix', 'Prefix Sum'],
    companies: ['Amazon', 'Atlassian', 'Meta', 'Adobe'],
    url: 'https://leetcode.com/problems/range-sum-query-2d-immutable/',
    notes: 'Inclusion-Exclusion principle 2D cumulative sum grid.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.2d-prefix-sum',
    patternSlug: '2d-prefix-sum',
    patternTitle: '2D Prefix Sum',
    questTitle: 'Quest: The Grid Ledger',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1314',
    slug: 'matrix-block-sum',
    leetcodeNumber: 1314,
    title: 'Matrix Block Sum',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 54.4,
    isPremium: false,
    topics: ['Array', 'Matrix', 'Prefix Sum'],
    companies: ['Apple', 'Uber', 'Oracle'],
    url: 'https://leetcode.com/problems/matrix-block-sum/',
    notes: 'Compute K-bounded submatrix sums using 2D prefix array.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.2d-prefix-sum',
    patternSlug: '2d-prefix-sum',
    patternTitle: '2D Prefix Sum',
    questTitle: 'Quest: The Grid Ledger',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-363',
    slug: 'max-sum-of-rectangle-no-larger-than-k',
    leetcodeNumber: 363,
    title: 'Max Sum of Rectangle No Larger Than K',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 21.5,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Matrix', 'Prefix Sum', 'TreeSet'],
    companies: ['Google', 'Amazon', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/',
    notes: '2D row compression combined with 1D TreeSet prefix sum bound.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.2d-prefix-sum',
    patternSlug: '2d-prefix-sum',
    patternTitle: '2D Prefix Sum',
    questTitle: 'Quest: The Grid Ledger',
    kingdomTitle: 'Kingdom of Accumulation',
  },

  // 3. Prefix XOR & Difference Arrays
  {
    id: 'lc-1720',
    slug: 'decode-xored-array',
    leetcodeNumber: 1720,
    title: 'Decode XORed Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 21,
    xp: 50,
    acceptanceRate: 68.7,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation'],
    companies: ['Amazon', 'Microsoft', 'Bloomberg', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/decode-xored-array/',
    notes: 'Reconstruct original array using arr[i+1] = encoded[i] ^ arr[i].',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-xor',
    patternSlug: 'prefix-xor',
    patternTitle: 'Prefix XOR & Difference Arrays',
    questTitle: 'Quest: The Cumulative Cipher',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1310',
    slug: 'xor-queries-of-a-subarray',
    leetcodeNumber: 1310,
    title: 'XOR Queries of a Subarray',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 37,
    xp: 100,
    acceptanceRate: 41.9,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation', 'Prefix Sum'],
    companies: ['Goldman Sachs', 'Salesforce', 'Microsoft', 'LinkedIn'],
    url: 'https://leetcode.com/problems/xor-queries-of-a-subarray/',
    notes: 'SubarrayXOR(L, R) = PrefXOR[R+1] ^ PrefXOR[L].',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-xor',
    patternSlug: 'prefix-xor',
    patternTitle: 'Prefix XOR & Difference Arrays',
    questTitle: 'Quest: The Cumulative Cipher',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-370',
    slug: 'range-addition',
    leetcodeNumber: 370,
    title: 'Range Addition',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 33,
    xp: 100,
    acceptanceRate: 57.2,
    isPremium: true,
    topics: ['Array', 'Prefix Sum'],
    companies: ['Salesforce', 'Atlassian', 'Meta'],
    url: 'https://leetcode.com/problems/range-addition/',
    notes: 'Difference array +val at start, -val at end+1, final prefix sum pass.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-xor',
    patternSlug: 'prefix-xor',
    patternTitle: 'Prefix XOR & Difference Arrays',
    questTitle: 'Quest: The Cumulative Cipher',
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1177',
    slug: 'can-make-palindrome-from-substring',
    leetcodeNumber: 1177,
    title: 'Can Make Palindrome from Substring',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 49.7,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Bit Manipulation', 'Prefix Sum'],
    companies: ['Microsoft', 'Netflix', 'Uber', 'Google'],
    url: 'https://leetcode.com/problems/can-make-palindrome-from-substring/',
    notes: 'Bitmask prefix array tracking character odd frequency counts.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-xor',
    patternSlug: 'prefix-xor',
    patternTitle: 'Prefix XOR & Difference Arrays',
    questTitle: 'Quest: The Cumulative Cipher',
    kingdomTitle: 'Kingdom of Accumulation',
  },

  // 4. Prefix Sum with Hashing
  {
    id: 'lc-1893',
    slug: 'check-if-all-the-integers-in-a-range-are-covered',
    leetcodeNumber: 1893,
    title: 'Check if All the Integers in a Range Are Covered',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Low',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Prefix Sum'],
    companies: ['Microsoft', 'Adobe'],
    url: 'https://leetcode.com/problems/check-if-all-the-integers-in-a-range-are-covered/',
    notes: 'Difference array coverage marking for ranges.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1108',
    slug: 'defanging-an-ip-address',
    leetcodeNumber: 1108,
    title: 'Defanging an IP Address',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Uber', 'Goldman Sachs', 'Apple'],
    url: 'https://leetcode.com/problems/defanging-an-ip-address/',
    notes: 'Replace dot characters with defanged brackets.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-974',
    slug: 'subarray-sums-divisible-by-k',
    leetcodeNumber: 974,
    title: 'Subarray Sums Divisible by K',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Prefix Sum'],
    companies: ['Apple', 'Netflix', 'Bloomberg', 'Atlassian'],
    url: 'https://leetcode.com/problems/subarray-sums-divisible-by-k/',
    notes: 'Modulo prefix sum frequency tracking (handle negative remainders).',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1590',
    slug: 'make-sum-divisible-by-p',
    leetcodeNumber: 1590,
    title: 'Make Sum Divisible by P',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Prefix Sum'],
    companies: ['Bloomberg', 'Atlassian'],
    url: 'https://leetcode.com/problems/make-sum-divisible-by-p/',
    notes: 'Find shortest subarray with sum % p equal to totalSum % p.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-325',
    slug: 'maximum-size-subarray-sum-equals-k',
    leetcodeNumber: 325,
    title: 'Maximum Size Subarray Sum Equals k',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: true,
    topics: ['Array', 'Hash Table', 'Prefix Sum'],
    companies: ['LinkedIn', 'Salesforce', 'Oracle'],
    url: 'https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/',
    notes: 'Store earliest index for each prefix sum value in HashMap.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1524',
    slug: 'number-of-sub-arrays-with-odd-sum',
    leetcodeNumber: 1524,
    title: 'Number of Sub-arrays With Odd Sum',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Dynamic Programming', 'Prefix Sum'],
    companies: ['Oracle', 'Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/number-of-sub-arrays-with-odd-sum/',
    notes: 'Track counts of odd and even prefix sums.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1738',
    slug: 'find-kth-largest-xor-coordinate-value',
    leetcodeNumber: 1738,
    title: 'Find Kth Largest XOR Coordinate Value',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Bit Manipulation', 'Heap', 'Matrix', 'Prefix Sum', 'Quickselect'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/find-kth-largest-xor-coordinate-value/',
    notes: '2D prefix XOR computation combined with Min-Heap for Kth largest.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1109',
    slug: 'corporate-flight-bookings',
    leetcodeNumber: 1109,
    title: 'Corporate Flight Bookings',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Prefix Sum'],
    companies: ['Microsoft', 'Adobe', 'Uber'],
    url: 'https://leetcode.com/problems/corporate-flight-bookings/',
    notes: 'Difference array range update technique.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-2270',
    slug: 'number-of-ways-to-split-array',
    leetcodeNumber: 2270,
    title: 'Number of Ways to Split Array',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Prefix Sum'],
    companies: ['Uber', 'Goldman Sachs', 'Apple', 'Netflix'],
    url: 'https://leetcode.com/problems/number-of-ways-to-split-array/',
    notes: 'Single pass prefix sum vs suffix total comparison.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
  {
    id: 'lc-1074',
    slug: 'number-of-submatrices-that-sum-to-target',
    leetcodeNumber: 1074,
    title: 'Number of Submatrices That Sum to Target',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 56,
    xp: 200,
    acceptanceRate: 23.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Matrix', 'Prefix Sum'],
    companies: ['Apple', 'Netflix'],
    url: 'https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/',
    notes: '2D row compression combined with 1D Subarray Sum Equals K hash map.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    patternId: 'pattern.prefix-sum-hashing',
    patternSlug: 'prefix-sum-hashing',
    patternTitle: 'Prefix Sum with Hashing',
    questTitle: "Quest: The Ledger's Memory",
    kingdomTitle: 'Kingdom of Accumulation',
  },
];
