import { ProblemModel } from '../../types';

export const QUEUE_DEQUE_PROBLEMS: ProblemModel[] = [
  // 1. Queue Fundamentals & Design
  {
    id: 'lc-225',
    slug: 'implement-stack-using-queues',
    leetcodeNumber: 225,
    title: 'Implement Stack using Queues',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Stack', 'Design', 'Queue'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/implement-stack-using-queues/',
    notes: 'Single queue rotation or two queues stack simulation.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.queue-fundamentals',
    patternSlug: 'queue-fundamentals',
    patternTitle: 'Queue Fundamentals & Design',
    questTitle: 'Quest: The Flowing Queue',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-232',
    slug: 'implement-queue-using-stacks',
    leetcodeNumber: 232,
    title: 'Implement Queue using Stacks',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Stack', 'Design', 'Queue'],
    companies: ['Amazon', 'Microsoft', 'Meta'],
    url: 'https://leetcode.com/problems/implement-queue-using-stacks/',
    notes: 'In-stack for push, out-stack for pop amortized O(1).',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.queue-fundamentals',
    patternSlug: 'queue-fundamentals',
    patternTitle: 'Queue Fundamentals & Design',
    questTitle: 'Quest: The Flowing Queue',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-933',
    slug: 'number-of-recent-calls',
    leetcodeNumber: 933,
    title: 'Number of Recent Calls',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 74.0,
    isPremium: false,
    topics: ['Design', 'Queue', 'Data Stream'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-recent-calls/',
    notes: 'Queue polling timestamps older than t - 3000.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.queue-fundamentals',
    patternSlug: 'queue-fundamentals',
    patternTitle: 'Queue Fundamentals & Design',
    questTitle: 'Quest: The Flowing Queue',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-346',
    slug: 'moving-average-from-data-stream',
    leetcodeNumber: 346,
    title: 'Moving Average from Data Stream',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 77.0,
    isPremium: true,
    topics: ['Array', 'Design', 'Queue', 'Data Stream'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/moving-average-from-data-stream/',
    notes: 'Queue fixed size size with cumulative sum tracking.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.queue-fundamentals',
    patternSlug: 'queue-fundamentals',
    patternTitle: 'Queue Fundamentals & Design',
    questTitle: 'Quest: The Flowing Queue',
    kingdomTitle: 'The Corridor of Queues',
  },

  // 2. Monotonic Deque
  {
    id: 'lc-1696',
    slug: 'jump-game-vi',
    leetcodeNumber: 1696,
    title: 'Jump Game VI',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Queue', 'Sliding Window', 'Monotonic Queue', 'Heap'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/jump-game-vi/',
    notes: 'DP + Monotonic decreasing deque storing best max dp[i-k..i-1] scores.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.monotonic-deque',
    patternSlug: 'monotonic-deque',
    patternTitle: 'Monotonic Deque',
    questTitle: 'Quest: The Monotonic Corridor',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-862',
    slug: 'shortest-subarray-with-sum-at-least-k',
    leetcodeNumber: 862,
    title: 'Shortest Subarray with Sum at Least K',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 27.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Queue', 'Sliding Window', 'Heap', 'Prefix Sum', 'Monotonic Queue'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/',
    notes: 'Monotonic increasing deque on prefix sums P[i] - P[opt] >= K.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.monotonic-deque',
    patternSlug: 'monotonic-deque',
    patternTitle: 'Monotonic Deque',
    questTitle: 'Quest: The Monotonic Corridor',
    kingdomTitle: 'The Corridor of Queues',
  },

  // 3. BFS Queues
  {
    id: 'lc-102',
    slug: 'binary-tree-level-order-traversal',
    leetcodeNumber: 102,
    title: 'Binary Tree Level Order Traversal',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Tree', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    notes: 'Standard level-by-level queue traversal collecting row nodes.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.bfs-queue',
    patternSlug: 'bfs-queue',
    patternTitle: 'BFS Queues',
    questTitle: 'Quest: The Level Expansion',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-994',
    slug: 'rotting-oranges',
    leetcodeNumber: 994,
    title: 'Rotting Oranges',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['Array', 'Breadth-First Search', 'Matrix'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/rotting-oranges/',
    notes: 'Multi-source BFS grid traversal counting elapsed minutes.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.bfs-queue',
    patternSlug: 'bfs-queue',
    patternTitle: 'BFS Queues',
    questTitle: 'Quest: The Level Expansion',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-286',
    slug: 'walls-and-gates',
    leetcodeNumber: 286,
    title: 'Walls and Gates',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: true,
    topics: ['Array', 'Breadth-First Search', 'Matrix'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/walls-and-gates/',
    notes: 'Multi-source BFS queue starting from all gate locations simultaneously.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.bfs-queue',
    patternSlug: 'bfs-queue',
    patternTitle: 'BFS Queues',
    questTitle: 'Quest: The Level Expansion',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-542',
    slug: '01-matrix',
    leetcodeNumber: 542,
    title: '01 Matrix',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Breadth-First Search', 'Matrix'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/01-matrix/',
    notes: 'Multi-source BFS starting from all 0-cells.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.bfs-queue',
    patternSlug: 'bfs-queue',
    patternTitle: 'BFS Queues',
    questTitle: 'Quest: The Level Expansion',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-863',
    slug: 'all-nodes-distance-k-in-binary-tree',
    leetcodeNumber: 863,
    title: 'All Nodes Distance K in Binary Tree',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Tree'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/',
    notes: 'Build parent graph mapping then run BFS outward from target node.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.bfs-queue',
    patternSlug: 'bfs-queue',
    patternTitle: 'BFS Queues',
    questTitle: 'Quest: The Level Expansion',
    kingdomTitle: 'The Corridor of Queues',
  },

  // 4. Circular & Special Queue Design
  {
    id: 'lc-622',
    slug: 'design-circular-queue',
    leetcodeNumber: 622,
    title: 'Design Circular Queue',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Array', 'Header', 'Design', 'Queue'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/design-circular-queue/',
    notes: 'Fixed size array with head, tail, and count pointers (tail = (head + count - 1) % k).',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-641',
    slug: 'design-circular-deque',
    leetcodeNumber: 641,
    title: 'Design Circular Deque',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Header', 'Design', 'Queue'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/design-circular-deque/',
    notes: 'Circular array implementation supporting insertFront, insertLast, deleteFront, deleteLast.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-1429',
    slug: 'first-unique-number',
    leetcodeNumber: 1429,
    title: 'First Unique Number',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: true,
    topics: ['Array', 'Hash Table', 'Design', 'Queue', 'Data Stream'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/first-unique-number/',
    notes: 'Queue of numbers + HashMap frequency tracking lazy queue popping.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-950',
    slug: 'reveal-cards-in-increasing-order',
    leetcodeNumber: 950,
    title: 'Reveal Cards In Increasing Order',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 78.0,
    isPremium: false,
    topics: ['Array', 'Queue', 'Sorting', 'Simulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/reveal-cards-in-increasing-order/',
    notes: 'Simulate deck card operations backwards using Deque.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-621',
    slug: 'task-scheduler',
    leetcodeNumber: 621,
    title: 'Task Scheduler',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 57.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Greedy', 'Sorting', 'Heap', 'Counting'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/task-scheduler/',
    notes: 'Max-Heap + Cooldown Queue tracking available tasks at time T.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-353',
    slug: 'design-snake-game',
    leetcodeNumber: 353,
    title: 'Design Snake Game',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 45,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: true,
    topics: ['Array', 'Hash Table', 'Design', 'Queue', 'Matrix'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/design-snake-game/',
    notes: 'Deque snake body coordinates + HashSet collision lookup.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },

  {
    id: 'lc-1823',
    slug: 'find-the-winner-of-the-circular-game',
    leetcodeNumber: 1823,
    title: 'Find the Winner of the Circular Game',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 78.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Recursion', 'Queue', 'Simulation'],
    companies: ['Google', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/find-the-winner-of-the-circular-game/',
    notes: 'Josephus problem simulation using Queue or DP f(n, k) = (f(n-1, k) + k) % n.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-1700',
    slug: 'number-of-students-unable-to-eat-lunch',
    leetcodeNumber: 1700,
    title: 'Number of Students Unable to Eat Lunch',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Queue', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-students-unable-to-eat-lunch/',
    notes: 'Queue student preference count decrement until top sandwich cannot be taken.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-2073',
    slug: 'time-needed-to-buy-tickets',
    leetcodeNumber: 2073,
    title: 'Time Needed to Buy Tickets',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Queue', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/time-needed-to-buy-tickets/',
    notes: 'Single pass min math calculation min(tickets[i], tickets[k]) for i <= k.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-1670',
    slug: 'design-front-middle-back-queue',
    leetcodeNumber: 1670,
    title: 'Design Front Middle Back Queue',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Linked List', 'Design', 'Queue'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/design-front-middle-back-queue/',
    notes: 'Two deques (left and right) balanced around middle pointer.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-1825',
    slug: 'finding-mk-average',
    leetcodeNumber: 1825,
    title: 'Finding MK Average',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Design', 'Queue', 'Heap', 'Data Stream', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/finding-mk-average/',
    notes: 'Queue + 3 MultiSets (top K, middle, bottom K) maintaining balanced elements.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
  {
    id: 'lc-864',
    slug: 'shortest-path-to-get-all-keys',
    leetcodeNumber: 864,
    title: 'Shortest Path to Get All Keys',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 51.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation', 'Breadth-First Search', 'Matrix'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/shortest-path-to-get-all-keys/',
    notes: 'Bitmask grid BFS state (r, c, keyMask).',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue & Deque',
    patternId: 'pattern.circular-queue-design',
    patternSlug: 'circular-queue-design',
    patternTitle: 'Circular & Special Queue Design',
    questTitle: 'Quest: The Ring Buffer',
    kingdomTitle: 'The Corridor of Queues',
  },
];
