import { ProblemModel } from '../../types';

export const SHORTEST_PATH_PROBLEMS: ProblemModel[] = [
  // 1. BFS Shortest Path
  {
    id: 'lc-1926',
    slug: 'nearest-exit-from-entrance-in-maze',
    leetcodeNumber: 1926,
    title: 'Nearest Exit from Entrance in Maze',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 56.7,
    isPremium: false,
    topics: ['Array', 'Breadth-First Search', 'Matrix'],
    companies: ['Oracle', 'Netflix'],
    url: 'https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/',
    notes: '2D Grid BFS level traversal finding nearest boundary cell.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.bfs-shortest-path',
    patternSlug: 'bfs-shortest-path',
    patternTitle: 'BFS Shortest Path',
    questTitle: 'Quest: The Quickest Route',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1091',
    slug: 'shortest-path-in-binary-matrix',
    leetcodeNumber: 1091,
    title: 'Shortest Path in Binary Matrix',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 35.9,
    isPremium: false,
    topics: ['Array', 'Breadth-First Search', 'Matrix'],
    companies: ['Uber', 'Salesforce', 'Apple'],
    url: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/',
    notes: '8-directional 2D grid BFS for shortest clear path.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.bfs-shortest-path',
    patternSlug: 'bfs-shortest-path',
    patternTitle: 'BFS Shortest Path',
    questTitle: 'Quest: The Quickest Route',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-127',
    slug: 'word-ladder',
    leetcodeNumber: 127,
    title: 'Word Ladder',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 34.2,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Breadth-First Search'],
    companies: ['Adobe', 'Atlassian', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/word-ladder/',
    notes: 'BFS level exploration on single-character mutation graph.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.bfs-shortest-path',
    patternSlug: 'bfs-shortest-path',
    patternTitle: 'BFS Shortest Path',
    questTitle: 'Quest: The Quickest Route',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-752',
    slug: 'open-the-lock',
    leetcodeNumber: 752,
    title: 'Open the Lock',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 46.5,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Breadth-First Search'],
    companies: ['Atlassian', 'Google', 'Bloomberg', 'Adobe'],
    url: 'https://leetcode.com/problems/open-the-lock/',
    notes: '4-digit wheel state BFS avoiding deadends.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.bfs-shortest-path',
    patternSlug: 'bfs-shortest-path',
    patternTitle: 'BFS Shortest Path',
    questTitle: 'Quest: The Quickest Route',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-126',
    slug: 'word-ladder-ii',
    leetcodeNumber: 126,
    title: 'Word Ladder II',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 59,
    xp: 200,
    acceptanceRate: 31.1,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Backtracking', 'Breadth-First Search'],
    companies: ['LinkedIn', 'Google', 'Oracle', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/word-ladder-ii/',
    notes: 'BFS parent tree construction + DFS backtracking for all shortest paths.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.bfs-shortest-path',
    patternSlug: 'bfs-shortest-path',
    patternTitle: 'BFS Shortest Path',
    questTitle: 'Quest: The Quickest Route',
    kingdomTitle: 'The Swift Roads',
  },

  // 2. Dijkstra's Algorithm
  {
    id: 'lc-743',
    slug: 'network-delay-time',
    leetcodeNumber: 743,
    title: 'Network Delay Time',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 52.2,
    isPremium: false,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Heap', 'Shortest Path'],
    companies: ['Microsoft', 'Meta'],
    url: 'https://leetcode.com/problems/network-delay-time/',
    notes: 'Classic single-source Min-Heap Dijkstra in weighted graph.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.dijkstras-algorithm',
    patternSlug: 'dijkstras-algorithm',
    patternTitle: "Dijkstra's Algorithm",
    questTitle: 'Quest: The Weighted Path',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1631',
    slug: 'path-with-minimum-effort',
    leetcodeNumber: 1631,
    title: 'Path With Minimum Effort',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 37,
    xp: 100,
    acceptanceRate: 43.7,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Heap', 'Matrix'],
    companies: ['Uber', 'Bloomberg', 'Amazon'],
    url: 'https://leetcode.com/problems/path-with-minimum-effort/',
    notes: 'Min-max absolute height difference Dijkstra grid path.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.dijkstras-algorithm',
    patternSlug: 'dijkstras-algorithm',
    patternTitle: "Dijkstra's Algorithm",
    questTitle: 'Quest: The Weighted Path',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1514',
    slug: 'path-with-maximum-probability',
    leetcodeNumber: 1514,
    title: 'Path with Maximum Probability',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 54.4,
    isPremium: false,
    topics: ['Array', 'Graph', 'Heap', 'Shortest Path'],
    companies: ['Amazon', 'Meta', 'Adobe'],
    url: 'https://leetcode.com/problems/path-with-maximum-probability/',
    notes: 'Max-Heap Dijkstra multiplying edge probabilities.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.dijkstras-algorithm',
    patternSlug: 'dijkstras-algorithm',
    patternTitle: "Dijkstra's Algorithm",
    questTitle: 'Quest: The Weighted Path',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1976',
    slug: 'number-of-ways-to-arrive-at-destination',
    leetcodeNumber: 1976,
    title: 'Number of Ways to Arrive at Destination',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 46.8,
    isPremium: false,
    topics: ['Dynamic Programming', 'Graph', 'Topological Sort', 'Shortest Path'],
    companies: ['Meta', 'Atlassian', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/',
    notes: 'Dijkstra tracking count of shortest paths modulo 10^9+7.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.dijkstras-algorithm',
    patternSlug: 'dijkstras-algorithm',
    patternTitle: "Dijkstra's Algorithm",
    questTitle: 'Quest: The Weighted Path',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-787',
    slug: 'cheapest-flights-within-k-stops',
    leetcodeNumber: 787,
    title: 'Cheapest Flights Within K Stops',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 59,
    xp: 200,
    acceptanceRate: 39.1,
    isPremium: false,
    topics: ['Dynamic Programming', 'Depth-First Search', 'Breadth-First Search', 'Graph', 'Heap', 'Shortest Path'],
    companies: ['Google', 'LinkedIn', 'Goldman Sachs'],
    url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
    notes: 'Bellman-Ford or modified Dijkstra with stops K state limit.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.dijkstras-algorithm',
    patternSlug: 'dijkstras-algorithm',
    patternTitle: "Dijkstra's Algorithm",
    questTitle: 'Quest: The Weighted Path',
    kingdomTitle: 'The Swift Roads',
  },

  // 3. Bellman-Ford & Floyd-Warshall
  {
    id: 'lc-1334',
    slug: 'find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance',
    leetcodeNumber: 1334,
    title: 'Find the City With the Smallest Number of Neighbors at a Threshold Distance',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 31,
    xp: 100,
    acceptanceRate: 48.3,
    isPremium: false,
    topics: ['Dynamic Programming', 'Graph', 'Shortest Path'],
    companies: ['Uber', 'Meta', 'Amazon', 'Apple'],
    url: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/',
    notes: 'Floyd-Warshall all-pairs distance matrix O(V^3).',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.bellman-ford',
    patternSlug: 'bellman-ford',
    patternTitle: 'Bellman-Ford & Floyd-Warshall',
    questTitle: 'Quest: The Road of Negatives',
    kingdomTitle: 'The Swift Roads',
  },

  // 4. A* & 0-1 BFS
  {
    id: 'lc-1293',
    slug: 'shortest-path-in-a-grid-with-obstacles-elimination',
    leetcodeNumber: 1293,
    title: 'Shortest Path in a Grid with Obstacles Elimination',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 27,
    xp: 100,
    acceptanceRate: 36.1,
    isPremium: false,
    topics: ['Array', 'Breadth-First Search', 'Matrix'],
    companies: ['Netflix', 'Adobe', 'Amazon'],
    url: 'https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/',
    notes: '3D state BFS visited[r][c][k] for obstacle elimination.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.a-star-01-bfs',
    patternSlug: 'a-star-01-bfs',
    patternTitle: 'A* & 0-1 BFS',
    questTitle: 'Quest: The Illuminated Path',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-847',
    slug: 'shortest-path-visiting-all-nodes',
    leetcodeNumber: 847,
    title: 'Shortest Path Visiting All Nodes',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 57,
    xp: 200,
    acceptanceRate: 19.7,
    isPremium: false,
    topics: ['Dynamic Programming', 'Bit Manipulation', 'Breadth-First Search', 'Graph', 'Bitmask'],
    companies: ['LinkedIn', 'Oracle', 'Goldman Sachs', 'Meta'],
    url: 'https://leetcode.com/problems/shortest-path-visiting-all-nodes/',
    notes: 'Multi-source BFS with bitmask state tracking visited vertices.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.a-star-01-bfs',
    patternSlug: 'a-star-01-bfs',
    patternTitle: 'A* & 0-1 BFS',
    questTitle: 'Quest: The Illuminated Path',
    kingdomTitle: 'The Swift Roads',
  },

  // 5. Modified Dijkstra Variants
  {
    id: 'lc-1129',
    slug: 'shortest-path-with-alternating-colors',
    leetcodeNumber: 1129,
    title: 'Shortest Path with Alternating Colors',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Breadth-First Search', 'Graph'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/shortest-path-with-alternating-colors/',
    notes: 'BFS with state (node, edgeColor) for red/blue alternating paths.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1786',
    slug: 'number-of-restricted-paths-from-first-to-last-node',
    leetcodeNumber: 1786,
    title: 'Number of Restricted Paths From First to Last Node',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['Dynamic Programming', 'Graph', 'Topological Sort', 'Heap', 'Shortest Path'],
    companies: ['Meta', 'Microsoft', 'Adobe'],
    url: 'https://leetcode.com/problems/number-of-restricted-paths-from-first-to-last-node/',
    notes: 'Dijkstra from destination node + memoized DP count.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-505',
    slug: 'the-maze-ii',
    leetcodeNumber: 505,
    title: 'The Maze II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: true,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Heap', 'Matrix', 'Shortest Path'],
    companies: ['Adobe', 'Uber', 'Goldman Sachs', 'Apple'],
    url: 'https://leetcode.com/problems/the-maze-ii/',
    notes: 'Rolling ball until wall hit Dijkstra distance update.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-2662',
    slug: 'minimum-cost-of-a-path-with-special-roads',
    leetcodeNumber: 2662,
    title: 'Minimum Cost of a Path With Special Roads',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Graph', 'Heap', 'Shortest Path'],
    companies: ['Goldman Sachs', 'Apple'],
    url: 'https://leetcode.com/problems/minimum-cost-of-a-path-with-special-roads/',
    notes: 'Dijkstra over 2D point coordinates using special shortcut edges.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1368',
    slug: 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid',
    leetcodeNumber: 1368,
    title: 'Minimum Cost to Make at Least One Valid Path in a Grid',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 56,
    xp: 200,
    acceptanceRate: 28.0,
    isPremium: false,
    topics: ['Array', 'Breadth-First Search', 'Matrix', 'Heap', 'Shortest Path'],
    companies: ['Netflix', 'Bloomberg', 'Atlassian'],
    url: 'https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/',
    notes: '0-1 BFS with Deque (cost 0 for matching arrow direction, 1 for change).',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-882',
    slug: 'reachable-nodes-in-subdivided-graph',
    leetcodeNumber: 882,
    title: 'Reachable Nodes In Subdivided Graph',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 48,
    xp: 200,
    acceptanceRate: 35.0,
    isPremium: false,
    topics: ['Graph', 'Heap', 'Shortest Path'],
    companies: ['Atlassian', 'LinkedIn', 'Salesforce', 'Oracle'],
    url: 'https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/',
    notes: 'Dijkstra on base vertices then accumulate reachable subdivided edge nodes.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-1928',
    slug: 'minimum-cost-to-reach-destination-in-time',
    leetcodeNumber: 1928,
    title: 'Minimum Cost to Reach Destination in Time',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 22.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Graph', 'Heap'],
    companies: ['Salesforce', 'Oracle'],
    url: 'https://leetcode.com/problems/minimum-cost-to-reach-destination-in-time/',
    notes: 'Dijkstra state (timeSpent, cost) or 2D DP dp[time][city].',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-2045',
    slug: 'second-minimum-time-to-reach-destination',
    leetcodeNumber: 2045,
    title: 'Second Minimum Time to Reach Destination',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 52,
    xp: 200,
    acceptanceRate: 29.0,
    isPremium: false,
    topics: ['Breadth-First Search', 'Graph', 'Shortest Path'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/second-minimum-time-to-reach-destination/',
    notes: 'Track two shortest distance values dist1 and dist2 per vertex in BFS.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
  {
    id: 'lc-778',
    slug: 'swim-in-rising-water',
    leetcodeNumber: 778,
    title: 'Swim in Rising Water',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 54,
    xp: 200,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Heap', 'Matrix'],
    companies: ['Meta', 'Microsoft', 'Adobe', 'Uber'],
    url: 'https://leetcode.com/problems/swim-in-rising-water/',
    notes: 'Min-max path height Dijkstra or binary search + BFS.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path Algorithms',
    patternId: 'pattern.modified-dijkstra-variants',
    patternSlug: 'modified-dijkstra-variants',
    patternTitle: 'Modified Dijkstra Variants',
    questTitle: 'Quest: The Layered Toll',
    kingdomTitle: 'The Swift Roads',
  },
];
