import { ProblemModel } from '../../types';

export const SLIDING_WINDOW_PROBLEMS: ProblemModel[] = [
  // 1. Fixed Window
  {
    id: 'lc-643',
    slug: 'maximum-average-subarray-i',
    leetcodeNumber: 643,
    title: 'Maximum Average Subarray I',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 55.5,
    isPremium: false,
    topics: ['Array', 'Sliding Window'],
    companies: ['LinkedIn', 'Salesforce', 'Meta', 'Bloomberg'],
    url: 'https://leetcode.com/problems/maximum-average-subarray-i/',
    notes: 'Fixed window K sum update in O(1) time per element.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.fixed-window',
    patternSlug: 'fixed-window',
    patternTitle: 'Fixed Window',
    questTitle: 'Quest: The Steady Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1343',
    slug: 'number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold',
    leetcodeNumber: 1343,
    title: 'Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 47.3,
    isPremium: false,
    topics: ['Array', 'Sliding Window'],
    companies: ['Netflix', 'Uber'],
    url: 'https://leetcode.com/problems/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/',
    notes: 'Window sum target comparison targetSum = threshold * k.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.fixed-window',
    patternSlug: 'fixed-window',
    patternTitle: 'Fixed Window',
    questTitle: 'Quest: The Steady Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-2461',
    slug: 'maximum-sum-of-distinct-subarrays-with-length-k',
    leetcodeNumber: 2461,
    title: 'Maximum Sum of Distinct Subarrays With Length K',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 27,
    xp: 100,
    acceptanceRate: 50.4,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sliding Window'],
    companies: ['Oracle', 'Apple', 'Salesforce', 'LinkedIn'],
    url: 'https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/',
    notes: 'Fixed window K combined with HashSet uniqueness check.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.fixed-window',
    patternSlug: 'fixed-window',
    patternTitle: 'Fixed Window',
    questTitle: 'Quest: The Steady Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-239',
    slug: 'sliding-window-maximum',
    leetcodeNumber: 239,
    title: 'Sliding Window Maximum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 47,
    xp: 200,
    acceptanceRate: 19.5,
    isPremium: false,
    topics: ['Array', 'Queue', 'Sliding Window', 'Heap', 'Monotonic Queue'],
    companies: ['Salesforce', 'Netflix'],
    url: 'https://leetcode.com/problems/sliding-window-maximum/',
    notes: 'Monotonic decreasing deque holding candidate max indices.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.fixed-window',
    patternSlug: 'fixed-window',
    patternTitle: 'Fixed Window',
    questTitle: 'Quest: The Steady Frame',
    kingdomTitle: 'The Moving Horizon',
  },

  // 2. Variable Window
  {
    id: 'lc-219',
    slug: 'contains-duplicate-ii',
    leetcodeNumber: 219,
    title: 'Contains Duplicate II',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sliding Window'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/contains-duplicate-ii/',
    notes: 'HashSet window of size K duplicate lookup.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1493',
    slug: 'longest-subarray-of-1s-after-deleting-one-element',
    leetcodeNumber: 1493,
    title: "Longest Subarray of 1's After Deleting One Element",
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Sliding Window'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/',
    notes: 'Variable window allowing at most one zero count.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-3',
    slug: 'longest-substring-without-repeating-characters',
    leetcodeNumber: 3,
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 37.6,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Amazon', 'Bloomberg', 'Adobe'],
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    notes: 'Expand right pointer, contract left pointer on character duplicate.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-209',
    slug: 'minimum-size-subarray-sum',
    leetcodeNumber: 209,
    title: 'Minimum Size Subarray Sum',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 38.3,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Sliding Window', 'Prefix Sum'],
    companies: ['Meta', 'Apple'],
    url: 'https://leetcode.com/problems/minimum-size-subarray-sum/',
    notes: 'Expand right while sum < target, shrink left while sum >= target.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-904',
    slug: 'fruit-into-baskets',
    leetcodeNumber: 904,
    title: 'Fruit Into Baskets',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sliding Window'],
    companies: ['Netflix', 'Apple'],
    url: 'https://leetcode.com/problems/fruit-into-baskets/',
    notes: 'Longest subarray containing at most 2 distinct integers.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-76',
    slug: 'minimum-window-substring',
    leetcodeNumber: 76,
    title: 'Minimum Window Substring',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 61,
    xp: 200,
    acceptanceRate: 27.5,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Netflix', 'LinkedIn'],
    url: 'https://leetcode.com/problems/minimum-window-substring/',
    notes: 'Match count tracking frequency map inside variable sliding window.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-992',
    slug: 'subarrays-with-k-different-integers',
    leetcodeNumber: 992,
    title: 'Subarrays with K Different Integers',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sliding Window', 'Counting'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/subarrays-with-k-different-integers/',
    notes: 'Exact K distinct = atMost(K) - atMost(K-1) sliding window count.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1425',
    slug: 'constrained-subsequence-sum',
    leetcodeNumber: 1425,
    title: 'Constrained Subsequence Sum',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Queue', 'Sliding Window', 'Monotonic Queue', 'Heap'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/constrained-subsequence-sum/',
    notes: 'DP + monotonic deque sliding window max dp[i-k..i-1].',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.variable-window',
    patternSlug: 'variable-window',
    patternTitle: 'Variable Window',
    questTitle: 'Quest: The Elastic Frame',
    kingdomTitle: 'The Moving Horizon',
  },

  // 3. Sliding Window + HashMap
  {
    id: 'lc-1004',
    slug: 'max-consecutive-ones-iii',
    leetcodeNumber: 1004,
    title: 'Max Consecutive Ones III',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Sliding Window', 'Prefix Sum'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/max-consecutive-ones-iii/',
    notes: 'Sliding window tracking count of flipped zeroes <= K.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.sliding-window-hashmap',
    patternSlug: 'sliding-window-hashmap',
    patternTitle: 'Sliding Window + HashMap',
    questTitle: 'Quest: The Marked Frontier',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-567',
    slug: 'permutation-in-string',
    leetcodeNumber: 567,
    title: 'Permutation in String',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Hash Table', 'Two Pointers', 'String', 'Sliding Window'],
    companies: ['Meta', 'Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/permutation-in-string/',
    notes: 'Fixed window of len(s1) checking 26-char frequency match.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.sliding-window-hashmap',
    patternSlug: 'sliding-window-hashmap',
    patternTitle: 'Sliding Window + HashMap',
    questTitle: 'Quest: The Marked Frontier',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-30',
    slug: 'substring-with-concatenation-of-all-words',
    leetcodeNumber: 30,
    title: 'Substring with Concatenation of All Words',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Amazon', 'Apple'],
    url: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/',
    notes: 'Multi-pass sliding window with word length step size and word HashMap.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.sliding-window-hashmap',
    patternSlug: 'sliding-window-hashmap',
    patternTitle: 'Sliding Window + HashMap',
    questTitle: 'Quest: The Marked Frontier',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-438',
    slug: 'find-all-anagrams-in-a-string',
    leetcodeNumber: 438,
    title: 'Find All Anagrams in a String',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Meta', 'Amazon', 'Bloomberg'],
    url: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/',
    notes: 'Fixed size window sliding over string comparing character frequency map.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.sliding-window-hashmap',
    patternSlug: 'sliding-window-hashmap',
    patternTitle: 'Sliding Window + HashMap',
    questTitle: 'Quest: The Marked Frontier',
    kingdomTitle: 'The Moving Horizon',
  },

  // 4. Monotonic Window
  {
    id: 'lc-1052',
    slug: 'grumpy-bookstore-owner',
    leetcodeNumber: 1052,
    title: 'Grumpy Bookstore Owner',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Sliding Window'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/grumpy-bookstore-owner/',
    notes: 'Fixed window size minutes maximizing extra satisfied customers.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.monotonic-window',
    patternSlug: 'monotonic-window',
    patternTitle: 'Monotonic Window',
    questTitle: 'Quest: The Watchtower Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1438',
    slug: 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit',
    leetcodeNumber: 1438,
    title: 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Array', 'Queue', 'Sliding Window', 'Heap', 'Monotonic Queue'],
    companies: ['Google', 'Uber'],
    url: 'https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/',
    notes: 'Two monotonic deques (maxDeque & minDeque) inside variable window.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.monotonic-window',
    patternSlug: 'monotonic-window',
    patternTitle: 'Monotonic Window',
    questTitle: 'Quest: The Watchtower Frame',
    kingdomTitle: 'The Moving Horizon',
  },

  // 5. Longest/Shortest Substring Patterns
  {
    id: 'lc-1876',
    slug: 'substrings-of-size-three-with-distinct-characters',
    leetcodeNumber: 1876,
    title: 'Substrings of Size Three with Distinct Characters',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window', 'Counting'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/substrings-of-size-three-with-distinct-characters/',
    notes: 'Fixed window of size 3 checking distinct character count.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1176',
    slug: 'diet-plan-performance',
    leetcodeNumber: 1176,
    title: 'Diet Plan Performance',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Low',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 54.0,
    isPremium: true,
    topics: ['Array', 'Sliding Window'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/diet-plan-performance/',
    notes: 'Fixed window K score comparison lower vs upper bounds.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-424',
    slug: 'longest-repeating-character-replacement',
    leetcodeNumber: 424,
    title: 'Longest Repeating Character Replacement',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 54.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
    notes: 'Window length - maxCharFreq <= k variable window optimization.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1156',
    slug: 'swap-for-longest-repeated-character-substring',
    leetcodeNumber: 1156,
    title: 'Swap For Longest Repeated Character Substring',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 36,
    xp: 100,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['String', 'Sliding Window'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/swap-for-longest-repeated-character-substring/',
    notes: 'Group contiguous character blocks and evaluate single swap extensions.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1888',
    slug: 'minimum-number-of-flips-to-make-the-binary-string-alternating',
    leetcodeNumber: 1888,
    title: 'Minimum Number of Flips to Make the Binary String Alternating',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 38,
    xp: 100,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['String', 'Dynamic Programming', 'Sliding Window', 'Greedy'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/minimum-number-of-flips-to-make-the-binary-string-alternating/',
    notes: 'Double string concatenation s+s with fixed window size N matching 0101 and 1010 targets.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1839',
    slug: 'longest-substring-of-all-vowels-in-order',
    leetcodeNumber: 1839,
    title: 'Longest Substring Of All Vowels in Order',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 49.0,
    isPremium: false,
    topics: ['String', 'Sliding Window'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/longest-substring-of-all-vowels-in-order/',
    notes: 'Two pointer scan ensuring vowels appear in non-decreasing a-e-i-o-u order.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1358',
    slug: 'number-of-substrings-containing-all-three-characters',
    leetcodeNumber: 1358,
    title: 'Number of Substrings Containing All Three Characters',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/',
    notes: 'Track min last seen positions of a, b, c. Add min(lastPos) + 1 to answer.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-727',
    slug: 'minimum-window-subsequence',
    leetcodeNumber: 727,
    title: 'Minimum Window Subsequence',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 43.0,
    isPremium: true,
    topics: ['String', 'Dynamic Programming', 'Sliding Window'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/minimum-window-subsequence/',
    notes: 'Two-pointer forward match and backward contraction for shortest subsequence window.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
  {
    id: 'lc-1044',
    slug: 'longest-duplicate-substring',
    leetcodeNumber: 1044,
    title: 'Longest Duplicate Substring',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 30.0,
    isPremium: false,
    topics: ['String', 'Binary Search', 'Suffix Array', 'Rolling Hash', 'Hash Function'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/longest-duplicate-substring/',
    notes: 'Binary search length L combined with Rabin-Karp rolling hash.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    patternId: 'pattern.bounded-frame-substrings',
    patternSlug: 'bounded-frame-substrings',
    patternTitle: 'Longest/Shortest Substring Patterns',
    questTitle: 'Quest: The Bounded Frame',
    kingdomTitle: 'The Moving Horizon',
  },
];
