import { ProblemModel } from '../../types';

export const SORTING_PROBLEMS: ProblemModel[] = [
  // 1. Comparison & Custom Sorting
  {
    id: 'lc-912',
    slug: 'sort-an-array',
    leetcodeNumber: 912,
    title: 'Sort an Array',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Sorting', 'Heap', 'Merge Sort', 'Bucket Sort', 'Radix Sort', 'Counting Sort'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/sort-an-array/',
    notes: 'Implement Merge Sort / Heap Sort for guaranteed O(N log N).',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.comparison-sorting',
    patternSlug: 'comparison-sorting',
    patternTitle: 'Comparison & Custom Sorting',
    questTitle: 'Quest: The Ordered Array',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-179',
    slug: 'largest-number',
    leetcodeNumber: 179,
    title: 'Largest Number',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 35.0,
    isPremium: false,
    topics: ['Array', 'String', 'Greedy', 'Sorting'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/largest-number/',
    notes: 'Custom comparator sorting strings (a + b) vs (b + a).',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.comparison-sorting',
    patternSlug: 'comparison-sorting',
    patternTitle: 'Comparison & Custom Sorting',
    questTitle: 'Quest: The Ordered Array',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-973',
    slug: 'k-closest-points-to-origin',
    leetcodeNumber: 973,
    title: 'K Closest Points to Origin',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Divide and Conquer', 'Geometry', 'Sorting', 'Heap', 'Quickselect'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/k-closest-points-to-origin/',
    notes: 'Sort by Euclidean distance squared x^2 + y^2 or Quickselect.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.comparison-sorting',
    patternSlug: 'comparison-sorting',
    patternTitle: 'Comparison & Custom Sorting',
    questTitle: 'Quest: The Ordered Array',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-148',
    slug: 'sort-list',
    leetcodeNumber: 148,
    title: 'Sort List',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers', 'Divide and Conquer', 'Sorting', 'Merge Sort'],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/sort-list/',
    notes: 'Bottom-up or Top-down Merge Sort on Linked List.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.comparison-sorting',
    patternSlug: 'comparison-sorting',
    patternTitle: 'Comparison & Custom Sorting',
    questTitle: 'Quest: The Ordered Array',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-215',
    slug: 'kth-largest-element-in-an-array',
    leetcodeNumber: 215,
    title: 'Kth Largest Element in an Array',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Array', 'Divide and Conquer', 'Sorting', 'Heap', 'Quickselect'],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
    notes: 'Quickselect algorithm for average O(N) time complexity.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.comparison-sorting',
    patternSlug: 'comparison-sorting',
    patternTitle: 'Comparison & Custom Sorting',
    questTitle: 'Quest: The Ordered Array',
    kingdomTitle: 'The Ordered Realms',
  },

  // 2. Custom Comparators & Sorting Criteria
  {
    id: 'lc-1122',
    slug: 'relative-sort-array',
    leetcodeNumber: 1122,
    title: 'Relative Sort Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sorting', 'Counting Sort'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/relative-sort-array/',
    notes: 'Counting sort using fixed rank map derived from arr2.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.custom-comparators',
    patternSlug: 'custom-comparators',
    patternTitle: 'Custom Comparators & Sorting Criteria',
    questTitle: 'Quest: The Tailored Rank',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-1356',
    slug: 'sort-integers-by-the-number-of-1-bits',
    leetcodeNumber: 1356,
    title: 'Sort Integers by The Number of 1 Bits',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 77.0,
    isPremium: false,
    topics: ['Array', 'Bit Manipulation', 'Sorting', 'Counting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/sort-integers-by-the-number-of-1-bits/',
    notes: 'Sort by bit count primary key then numeric value secondary key.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.custom-comparators',
    patternSlug: 'custom-comparators',
    patternTitle: 'Custom Comparators & Sorting Criteria',
    questTitle: 'Quest: The Tailored Rank',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-1636',
    slug: 'sort-array-by-increasing-frequency',
    leetcodeNumber: 1636,
    title: 'Sort Array by Increasing Frequency',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sorting'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/sort-array-by-increasing-frequency/',
    notes: 'Sort by frequency ascending then element value descending.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.custom-comparators',
    patternSlug: 'custom-comparators',
    patternTitle: 'Custom Comparators & Sorting Criteria',
    questTitle: 'Quest: The Tailored Rank',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-451',
    slug: 'sort-characters-by-frequency',
    leetcodeNumber: 451,
    title: 'Sort Characters By Frequency',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sorting', 'Heap', 'Bucket Sort', 'Counting'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/sort-characters-by-frequency/',
    notes: 'Bucket sort or Max-Heap based on character counts.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.custom-comparators',
    patternSlug: 'custom-comparators',
    patternTitle: 'Custom Comparators & Sorting Criteria',
    questTitle: 'Quest: The Tailored Rank',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-56',
    slug: 'merge-intervals',
    leetcodeNumber: 56,
    title: 'Merge Intervals',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 47.0,
    isPremium: false,
    topics: ['Array', 'Sorting'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/merge-intervals/',
    notes: 'Sort intervals by start time then merge overlapping boundaries.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.custom-comparators',
    patternSlug: 'custom-comparators',
    patternTitle: 'Custom Comparators & Sorting Criteria',
    questTitle: 'Quest: The Tailored Rank',
    kingdomTitle: 'The Ordered Realms',
  },

  // 3. Cyclic Sort
  {
    id: 'lc-268',
    slug: 'missing-number',
    leetcodeNumber: 268,
    title: 'Missing Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Math', 'Bit Manipulation', 'Sorting'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/missing-number/',
    notes: 'Place each number at index equal to its value in O(N) time and O(1) space.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.cyclic-sort',
    patternSlug: 'cyclic-sort',
    patternTitle: 'Cyclic Sort',
    questTitle: 'Quest: The Cyclic Orbit',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-448-s',
    slug: 'find-all-numbers-disappeared-in-an-array-sorting',
    leetcodeNumber: 448,
    title: 'Find All Numbers Disappeared in an Array (Cyclic Sort)',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/',
    notes: 'Swap elements until nums[i] == nums[nums[i]-1] to identify missing numbers.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.cyclic-sort',
    patternSlug: 'cyclic-sort',
    patternTitle: 'Cyclic Sort',
    questTitle: 'Quest: The Cyclic Orbit',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-287-s',
    slug: 'find-the-duplicate-number-cyclic-sort',
    leetcodeNumber: 287,
    title: 'Find the Duplicate Number (Cyclic Sort)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/find-the-duplicate-number/',
    notes: 'Place elements at index nums[i]-1 until duplicate is detected.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.cyclic-sort',
    patternSlug: 'cyclic-sort',
    patternTitle: 'Cyclic Sort',
    questTitle: 'Quest: The Cyclic Orbit',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-442-s',
    slug: 'find-all-duplicates-in-an-array-cyclic-sort',
    leetcodeNumber: 442,
    title: 'Find All Duplicates in an Array (Cyclic Sort)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 73.0,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/find-all-duplicates-in-an-array/',
    notes: 'Cyclic sort pass to put numbers 1..N in place, then find mismatched indices.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.cyclic-sort',
    patternSlug: 'cyclic-sort',
    patternTitle: 'Cyclic Sort',
    questTitle: 'Quest: The Cyclic Orbit',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-41-s',
    slug: 'first-missing-positive-cyclic-sort',
    leetcodeNumber: 41,
    title: 'First Missing Positive (Cyclic Sort)',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 200,
    acceptanceRate: 37.0,
    isPremium: false,
    topics: ['Array', 'Hash Table'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/first-missing-positive/',
    notes: 'Swap numbers in range 1..N to their 0-indexed positions.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.cyclic-sort',
    patternSlug: 'cyclic-sort',
    patternTitle: 'Cyclic Sort',
    questTitle: 'Quest: The Cyclic Orbit',
    kingdomTitle: 'The Ordered Realms',
  },

  // 4. Non-Comparison & Bucket Sort
  {
    id: 'lc-1051',
    slug: 'height-checker',
    leetcodeNumber: 1051,
    title: 'Height Checker',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 78.0,
    isPremium: false,
    topics: ['Array', 'Sorting', 'Counting Sort'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/height-checker/',
    notes: 'Counting sort frequency array comparison.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-1365',
    slug: 'how-many-numbers-are-smaller-than-the-current-number',
    leetcodeNumber: 1365,
    title: 'How Many Numbers Are Smaller Than the Current Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 86.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Sorting', 'Counting Sort'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/',
    notes: 'Frequency count prefix sum array mapping values 0..100.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-274',
    slug: 'h-index',
    leetcodeNumber: 274,
    title: 'H-Index',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'Sorting', 'Counting Sort'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/h-index/',
    notes: 'Bucket sort citations count array O(N).',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-539',
    slug: 'minimum-time-difference',
    leetcodeNumber: 539,
    title: 'Minimum Time Difference',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Math', 'String', 'Sorting'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/minimum-time-difference/',
    notes: 'Convert to minutes 0..1439 and bucket sort (boolean array of 1440 mins).',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-164',
    slug: 'maximum-gap',
    leetcodeNumber: 164,
    title: 'Maximum Gap',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Array', 'Sorting', 'Bucket Sort', 'Radix Sort'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-gap/',
    notes: 'Pigeonhole principle bucket sort dividing range into N-1 buckets.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-220',
    slug: 'contains-duplicate-iii',
    leetcodeNumber: 220,
    title: 'Contains Duplicate III',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 52,
    xp: 200,
    acceptanceRate: 22.0,
    isPremium: false,
    topics: ['Array', 'Sliding Window', 'Sorting', 'Bucket Sort', 'Ordered Set'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/contains-duplicate-iii/',
    notes: 'Bucket sorting elements of size t+1 with sliding window size k.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-969',
    slug: 'pancake-sorting',
    leetcodeNumber: 969,
    title: 'Pancake Sorting',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Greedy', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/pancake-sorting/',
    notes: 'Find max element, flip to index 0, flip to target position.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
  {
    id: 'lc-493',
    slug: 'reverse-pairs',
    leetcodeNumber: 493,
    title: 'Reverse Pairs',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 30.0,
    isPremium: false,
    topics: ['Array', 'Binary Search', 'Divide and Conquer', 'Binary Indexed Tree', 'Segment Tree', 'Merge Sort', 'Ordered Set'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/reverse-pairs/',
    notes: 'Modified Merge Sort counting pairs nums[i] > 2 * nums[j].',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    patternId: 'pattern.sorting-applications',
    patternSlug: 'sorting-applications',
    patternTitle: 'Non-Comparison & Bucket Sort',
    questTitle: 'Quest: The Linear Buckets',
    kingdomTitle: 'The Ordered Realms',
  },
];
