import { ProblemModel } from '../../types';

export const STACK_PROBLEMS: ProblemModel[] = [
  // 1. Monotonic Stack
  {
    id: 'lc-496',
    slug: 'next-greater-element-i',
    leetcodeNumber: 496,
    title: 'Next Greater Element I',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/next-greater-element-i/',
    notes: 'Monotonic decreasing stack with HashMap index lookup.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.monotonic-stack',
    patternSlug: 'monotonic-stack',
    patternTitle: 'Monotonic Stack',
    questTitle: 'Quest: The Rising Crest',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-739',
    slug: 'daily-temperatures',
    leetcodeNumber: 739,
    title: 'Daily Temperatures',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 26,
    xp: 100,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Monotonic Stack'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/daily-temperatures/',
    notes: 'Monotonic decreasing stack holding indices waiting for warmer day.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.monotonic-stack',
    patternSlug: 'monotonic-stack',
    patternTitle: 'Monotonic Stack',
    questTitle: 'Quest: The Rising Crest',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-503',
    slug: 'next-greater-element-ii',
    leetcodeNumber: 503,
    title: 'Next Greater Element II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/next-greater-element-ii/',
    notes: 'Monotonic stack over 2N circular array iteration index i % N.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.monotonic-stack',
    patternSlug: 'monotonic-stack',
    patternTitle: 'Monotonic Stack',
    questTitle: 'Quest: The Rising Crest',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-901',
    slug: 'online-stock-span',
    leetcodeNumber: 901,
    title: 'Online Stock Span',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: false,
    topics: ['Stack', 'Design', 'Monotonic Stack', 'Data Stream'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/online-stock-span/',
    notes: 'Monotonic decreasing stack storing (price, span) pairs.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.monotonic-stack',
    patternSlug: 'monotonic-stack',
    patternTitle: 'Monotonic Stack',
    questTitle: 'Quest: The Rising Crest',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-85',
    slug: 'maximal-rectangle',
    leetcodeNumber: 85,
    title: 'Maximal Rectangle',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Stack', 'Matrix', 'Monotonic Stack'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/maximal-rectangle/',
    notes: 'Apply Largest Rectangle in Histogram monotonic stack row by row.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.monotonic-stack',
    patternSlug: 'monotonic-stack',
    patternTitle: 'Monotonic Stack',
    questTitle: 'Quest: The Rising Crest',
    kingdomTitle: 'The Tower of Stacks',
  },

  // 2. Expression Evaluation
  {
    id: 'lc-150',
    slug: 'evaluate-reverse-polish-notation',
    leetcodeNumber: 150,
    title: 'Evaluate Reverse Polish Notation',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['Array', 'Math', 'Stack'],
    companies: ['Amazon', 'LinkedIn', 'Meta'],
    url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
    notes: 'Stack operand evaluation on operators +, -, *, /.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.expression-evaluation',
    patternSlug: 'expression-evaluation',
    patternTitle: 'Expression Evaluation',
    questTitle: 'Quest: The Evaluator',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-227',
    slug: 'basic-calculator-ii',
    leetcodeNumber: 227,
    title: 'Basic Calculator II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Math', 'String', 'Stack'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/basic-calculator-ii/',
    notes: 'Operator precedence handling using stack for * and / before sum.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.expression-evaluation',
    patternSlug: 'expression-evaluation',
    patternTitle: 'Expression Evaluation',
    questTitle: 'Quest: The Evaluator',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-224',
    slug: 'basic-calculator',
    leetcodeNumber: 224,
    title: 'Basic Calculator',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 55,
    xp: 200,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['Math', 'String', 'Stack', 'Recursion'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/basic-calculator/',
    notes: 'Stack operator and sign pushing on open parenthesis (.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.expression-evaluation',
    patternSlug: 'expression-evaluation',
    patternTitle: 'Expression Evaluation',
    questTitle: 'Quest: The Evaluator',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-772',
    slug: 'basic-calculator-iii',
    leetcodeNumber: 772,
    title: 'Basic Calculator III',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 49.0,
    isPremium: true,
    topics: ['Math', 'String', 'Stack', 'Recursion'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/basic-calculator-iii/',
    notes: 'Full calculator supporting +, -, *, /, and parentheses via recursive descent / stack.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.expression-evaluation',
    patternSlug: 'expression-evaluation',
    patternTitle: 'Expression Evaluation',
    questTitle: 'Quest: The Evaluator',
    kingdomTitle: 'The Tower of Stacks',
  },

  // 3. Stack Simulation & Min Stack
  {
    id: 'lc-20',
    slug: 'valid-parentheses',
    leetcodeNumber: 20,
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/valid-parentheses/',
    notes: 'Match open brackets (, {, [ with corresponding close brackets.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-simulation',
    patternSlug: 'stack-simulation',
    patternTitle: 'Stack Simulation & Min Stack',
    questTitle: 'Quest: The Balanced Vessel',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-155',
    slug: 'min-stack',
    leetcodeNumber: 155,
    title: 'Min Stack',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Stack', 'Design'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/min-stack/',
    notes: 'Auxiliary minStack tracking current minimum at each push.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-simulation',
    patternSlug: 'stack-simulation',
    patternTitle: 'Stack Simulation & Min Stack',
    questTitle: 'Quest: The Balanced Vessel',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-71',
    slug: 'simplify-path',
    leetcodeNumber: 71,
    title: 'Simplify Path',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/simplify-path/',
    notes: 'Unix directory path resolution using stack pop on ..',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-simulation',
    patternSlug: 'stack-simulation',
    patternTitle: 'Stack Simulation & Min Stack',
    questTitle: 'Quest: The Balanced Vessel',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-946',
    slug: 'validate-stack-sequences',
    leetcodeNumber: 946,
    title: 'Validate Stack Sequences',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Simulation'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/validate-stack-sequences/',
    notes: 'Simulate push operations and pop while stack top matches popped[j].',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-simulation',
    patternSlug: 'stack-simulation',
    patternTitle: 'Stack Simulation & Min Stack',
    questTitle: 'Quest: The Balanced Vessel',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-895',
    slug: 'maximum-frequency-stack',
    leetcodeNumber: 895,
    title: 'Maximum Frequency Stack',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 66.0,
    isPremium: false,
    topics: ['Hash Table', 'Stack', 'Design', 'Ordered Set'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/maximum-frequency-stack/',
    notes: 'FreqMap key -> count + StackMap freq -> Stack of values.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-simulation',
    patternSlug: 'stack-simulation',
    patternTitle: 'Stack Simulation & Min Stack',
    questTitle: 'Quest: The Balanced Vessel',
    kingdomTitle: 'The Tower of Stacks',
  },

  // 4. Stack String Processing
  {
    id: 'lc-1047',
    slug: 'remove-all-adjacent-duplicates-in-string',
    leetcodeNumber: 1047,
    title: 'Remove All Adjacent Duplicates In String',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/',
    notes: 'Stack cancellation pop when character matches stack top.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-1021',
    slug: 'remove-outermost-parentheses',
    leetcodeNumber: 1021,
    title: 'Remove Outermost Parentheses',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 16,
    xp: 50,
    acceptanceRate: 80.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/remove-outermost-parentheses/',
    notes: 'Track open parenthesis count > 0 to filter primitive outer parentheses.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-1544',
    slug: 'make-the-string-great',
    leetcodeNumber: 1544,
    title: 'Make The String Great',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 64.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/make-the-string-great/',
    notes: 'Pop from stack if abs(top - curr) == 32 (same letter opposite case).',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-394',
    slug: 'decode-string',
    leetcodeNumber: 394,
    title: 'Decode String',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['String', 'Stack', 'Recursion'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/decode-string/',
    notes: 'Dual stack (countStack and stringStack) for nested k[string] decoding.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-1209',
    slug: 'remove-all-adjacent-duplicates-in-string-ii',
    leetcodeNumber: 1209,
    title: 'Remove All Adjacent Duplicates in String II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/',
    notes: 'Stack of (char, count) pairs popping when count == k.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-636',
    slug: 'exclusive-time-of-functions',
    leetcodeNumber: 636,
    title: 'Exclusive Time of Functions',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 61.0,
    isPremium: false,
    topics: ['Array', 'Stack'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/exclusive-time-of-functions/',
    notes: 'Function execution call stack tracking prevTimestamp.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-1190',
    slug: 'reverse-substrings-between-each-pair-of-parentheses',
    leetcodeNumber: 1190,
    title: 'Reverse Substrings Between Each Pair of Parentheses',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 68.0,
    isPremium: false,
    topics: ['String', 'Stack'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/reverse-substrings-between-each-pair-of-parentheses/',
    notes: 'Wormhole teleporter pattern or stack reversal on closing bracket ).',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-1778',
    slug: 'shortest-path-in-a-hidden-grid',
    leetcodeNumber: 1778,
    title: 'Shortest Path in a Hidden Grid',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Low',
    estimatedTimeMin: 45,
    xp: 100,
    acceptanceRate: 42.0,
    isPremium: true,
    topics: ['Depth-First Search', 'Breadth-First Search', 'Graph', 'Interactive'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/shortest-path-in-a-hidden-grid/',
    notes: 'DFS grid exploration via backtracking stack + BFS shortest path.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-316',
    slug: 'remove-duplicate-letters',
    leetcodeNumber: 316,
    title: 'Remove Duplicate Letters',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['String', 'Stack', 'Greedy', 'Monotonic Stack'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/remove-duplicate-letters/',
    notes: 'Monotonic stack lexically smallest string with last occurrence frequency check.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-1081',
    slug: 'smallest-subsequence-of-distinct-characters',
    leetcodeNumber: 1081,
    title: 'Smallest Subsequence of Distinct Characters',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 59.0,
    isPremium: false,
    topics: ['String', 'Stack', 'Greedy', 'Monotonic Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/smallest-subsequence-of-distinct-characters/',
    notes: 'Identical logic to 316 using monotonic stack and character presence set.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-907',
    slug: 'sum-of-subarray-minimums',
    leetcodeNumber: 907,
    title: 'Sum of Subarray Minimums',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 45,
    xp: 100,
    acceptanceRate: 35.0,
    isPremium: false,
    topics: ['Array', 'Dynamic Programming', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/sum-of-subarray-minimums/',
    notes: 'Monotonic stack finding Previous Smaller and Next Smaller indices.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-2104',
    slug: 'sum-of-subarray-ranges',
    leetcodeNumber: 2104,
    title: 'Sum of Subarray Ranges',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 40,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Stack', 'Monotonic Stack'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/sum-of-subarray-ranges/',
    notes: 'Sum of subarray maximums - sum of subarray minimums via monotonic stack.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-402',
    slug: 'remove-k-digits',
    leetcodeNumber: 402,
    title: 'Remove K Digits',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 31.0,
    isPremium: false,
    topics: ['String', 'Stack', 'Greedy', 'Monotonic Stack'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/remove-k-digits/',
    notes: 'Monotonic increasing stack popping larger digits to make number smaller.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
  {
    id: 'lc-321',
    slug: 'create-maximum-number',
    leetcodeNumber: 321,
    title: 'Create Maximum Number',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 60,
    xp: 200,
    acceptanceRate: 29.0,
    isPremium: false,
    topics: ['Stack', 'Greedy', 'Monotonic Stack'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/create-maximum-number/',
    notes: 'Monotonic stack max subsequence selection + merge max sub-arrays.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    patternId: 'pattern.stack-string-processing',
    patternSlug: 'stack-string-processing',
    patternTitle: 'Stack String Processing',
    questTitle: 'Quest: The Scriptorium Stack',
    kingdomTitle: 'The Tower of Stacks',
  },
];
