import { ProblemModel } from '../../types';

export const STRINGS_PROBLEMS: ProblemModel[] = [
  // 1. String Fundamentals & Manipulation
  {
    id: 'lc-14',
    slug: 'longest-common-prefix',
    leetcodeNumber: 14,
    title: 'Longest Common Prefix',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 42.0,
    isPremium: false,
    topics: ['String', 'Trie'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/longest-common-prefix/',
    notes: 'Vertical character scan or horizontal prefix reduction.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-58',
    slug: 'length-of-last-word',
    leetcodeNumber: 58,
    title: 'Length of Last Word',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/length-of-last-word/',
    notes: 'Scan right-to-left skipping trailing whitespace.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-151',
    slug: 'reverse-words-in-a-string',
    leetcodeNumber: 151,
    title: 'Reverse Words in a String',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Two Pointers', 'String'],
    companies: ['Amazon', 'Microsoft', 'Meta'],
    url: 'https://leetcode.com/problems/reverse-words-in-a-string/',
    notes: 'Split words by space, reverse array of words, and join with space.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-8',
    slug: 'string-to-integer-atoi',
    leetcodeNumber: 8,
    title: 'String to Integer (atoi)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 17.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Meta', 'Amazon', 'Microsoft', 'Google'],
    url: 'https://leetcode.com/problems/string-to-integer-atoi/',
    notes: 'Whitespace trimming, sign parsing, overflow check (32-bit INT bounds).',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },

  // 2. Pattern Matching & Substrings
  {
    id: 'lc-28-s',
    slug: 'find-the-index-of-the-first-occurrence-in-a-string-kmp',
    leetcodeNumber: 28,
    title: 'Find First Occurrence in a String (KMP Algorithm)',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 50,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Two Pointers', 'String', 'String Matching'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',
    notes: 'KMP prefix table (LPS array) matching in O(N+M) time.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.pattern-matching',
    patternSlug: 'pattern-matching',
    patternTitle: 'Pattern Matching & Substrings',
    questTitle: 'Quest: The Pattern Finder',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-459',
    slug: 'repeated-substring-pattern',
    leetcodeNumber: 459,
    title: 'Repeated Substring Pattern',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['String', 'String Matching'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/repeated-substring-pattern/',
    notes: '(s + s).substring(1, 2*len - 1).contains(s) or LPS table check.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.pattern-matching',
    patternSlug: 'pattern-matching',
    patternTitle: 'Pattern Matching & Substrings',
    questTitle: 'Quest: The Pattern Finder',
    kingdomTitle: 'The Scriptorium',
  },

  // 3. Palindromes & String Expansion
  {
    id: 'lc-5-s',
    slug: 'longest-palindromic-substring-strings',
    leetcodeNumber: 5,
    title: 'Longest Palindromic Substring (Center Expansion)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 43.9,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/longest-palindromic-substring/',
    notes: 'Expand around 2N-1 centers (odd and even palindromes).',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.palindromes',
    patternSlug: 'palindromic-strings',
    patternTitle: 'Palindromes & String Expansion',
    questTitle: 'Quest: The Mirror Words',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-647-s',
    slug: 'palindromic-substrings-center-expansion',
    leetcodeNumber: 647,
    title: 'Palindromic Substrings (Center Expansion)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 55.4,
    isPremium: false,
    topics: ['String', 'Dynamic Programming'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/palindromic-substrings/',
    notes: 'Count valid expansions around each single character and character pair.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.palindromes',
    patternSlug: 'palindromic-strings',
    patternTitle: 'Palindromes & String Expansion',
    questTitle: 'Quest: The Mirror Words',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-214',
    slug: 'shortest-palindrome',
    leetcodeNumber: 214,
    title: 'Shortest Palindrome',
    difficulty: 'Hard',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 50,
    xp: 200,
    acceptanceRate: 33.0,
    isPremium: false,
    topics: ['String', 'Rolling Hash', 'String Matching', 'Hash Function'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/shortest-palindrome/',
    notes: 'KMP LPS table on s + "#" + reverse(s) to find longest palindromic prefix.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.palindromes',
    patternSlug: 'palindromic-strings',
    patternTitle: 'Palindromes & String Expansion',
    questTitle: 'Quest: The Mirror Words',
    kingdomTitle: 'The Scriptorium',
  },

  // 4. Anagrams & Frequency Matching
  {
    id: 'lc-242-s',
    slug: 'valid-anagram-strings',
    leetcodeNumber: 242,
    title: 'Valid Anagram (Frequency Vector)',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sorting'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/valid-anagram/',
    notes: '26-element integer frequency array character count delta.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.anagrams-frequency-strings',
    patternSlug: 'anagrams-frequency-strings',
    patternTitle: 'Anagrams & Frequency Matching',
    questTitle: 'Quest: The Anagram Vault',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-49-s',
    slug: 'group-anagrams-strings',
    leetcodeNumber: 49,
    title: 'Group Anagrams (String Hashing)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 56.1,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Sorting'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/group-anagrams/',
    notes: 'Construct frequency key string #1#0#2... and map to word lists.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.anagrams-frequency-strings',
    patternSlug: 'anagrams-frequency-strings',
    patternTitle: 'Anagrams & Frequency Matching',
    questTitle: 'Quest: The Anagram Vault',
    kingdomTitle: 'The Scriptorium',
  },

  // 5. Trie-Based Strings
  {
    id: 'lc-208',
    slug: 'implement-trie-prefix-tree',
    leetcodeNumber: 208,
    title: 'Implement Trie (Prefix Tree)',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 62.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Design', 'Trie'],
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    url: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    notes: 'TrieNode structure with children array of size 26 and isEnd boolean flag.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.trie-based-strings',
    patternSlug: 'trie-based-strings',
    patternTitle: 'Trie-Based Strings',
    questTitle: 'Quest: The Prefix Tree',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-211',
    slug: 'design-add-and-search-words-data-structure',
    leetcodeNumber: 211,
    title: 'Design Add and Search Words Data Structure',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 43.0,
    isPremium: false,
    topics: ['String', 'Depth-First Search', 'Design', 'Trie'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
    notes: 'Trie DFS handling wildcard "." matching all 26 child branches.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.trie-based-strings',
    patternSlug: 'trie-based-strings',
    patternTitle: 'Trie-Based Strings',
    questTitle: 'Quest: The Prefix Tree',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-648',
    slug: 'replace-words',
    leetcodeNumber: 648,
    title: 'Replace Words',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 63.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String', 'Trie'],
    companies: ['Uber'],
    url: 'https://leetcode.com/problems/replace-words/',
    notes: 'Insert dictionary roots into Trie and search shortest prefix for each sentence word.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.trie-based-strings',
    patternSlug: 'trie-based-strings',
    patternTitle: 'Trie-Based Strings',
    questTitle: 'Quest: The Prefix Tree',
    kingdomTitle: 'The Scriptorium',
  },

  // 6. String Parsing & Simulation
  {
    id: 'lc-6',
    slug: 'zigzag-conversion',
    leetcodeNumber: 6,
    title: 'Zigzag Conversion',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 46.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/zigzag-conversion/',
    notes: 'Row-by-row string builder bouncing direction at row 0 and row numRows-1.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-38',
    slug: 'count-and-say',
    leetcodeNumber: 38,
    title: 'Count and Say',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 53.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/count-and-say/',
    notes: 'Run length encoding simulation (count + digit character).',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },

  {
    id: 'lc-415',
    slug: 'add-strings',
    leetcodeNumber: 415,
    title: 'Add Strings',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Math', 'String', 'Simulation'],
    companies: ['Meta', 'Amazon'],
    url: 'https://leetcode.com/problems/add-strings/',
    notes: 'Digit by digit right-to-left string addition with carry.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-434',
    slug: 'number-of-segments-in-a-string',
    leetcodeNumber: 434,
    title: 'Number of Segments in a String',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/number-of-segments-in-a-string/',
    notes: 'Count transitions where s[i] != " " and (i == 0 || s[i-1] == " ").',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-520',
    slug: 'detect-capital',
    leetcodeNumber: 520,
    title: 'Detect Capital',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/detect-capital/',
    notes: 'Check all uppercase, all lowercase, or title case conditions.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-557',
    slug: 'reverse-words-in-a-string-iii',
    leetcodeNumber: 557,
    title: 'Reverse Words in a String III',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 82.0,
    isPremium: false,
    topics: ['Two Pointers', 'String'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/reverse-words-in-a-string-iii/',
    notes: 'In-place two pointer swap for each space-separated word.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-657',
    slug: 'robot-return-to-origin',
    leetcodeNumber: 657,
    title: 'Robot Return to Origin',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 75.0,
    isPremium: false,
    topics: ['String', 'Simulation'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/robot-return-to-origin/',
    notes: 'Track (x, y) displacement for U/D/L/R moves checking (0,0) final position.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-859',
    slug: 'buddy-strings',
    leetcodeNumber: 859,
    title: 'Buddy Strings',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 32.0,
    isPremium: false,
    topics: ['Hash Table', 'String'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/buddy-strings/',
    notes: 'Check exact 2 mismatched character positions swap or duplicate char presence when s == goal.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-165',
    slug: 'compare-version-numbers',
    leetcodeNumber: 165,
    title: 'Compare Version Numbers',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Two Pointers', 'String'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/compare-version-numbers/',
    notes: 'Split dot-separated revision integers and compare numerical values.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-468',
    slug: 'validate-ip-address',
    leetcodeNumber: 468,
    title: 'Validate IP Address',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 26.0,
    isPremium: false,
    topics: ['String'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/validate-ip-address/',
    notes: 'Parse IPv4 4-dot decimal blocks and IPv6 8-colon hex blocks.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-539-s',
    slug: 'minimum-time-difference-strings',
    leetcodeNumber: 539,
    title: 'Minimum Time Difference (String Time Parsing)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 56.0,
    isPremium: false,
    topics: ['Array', 'Math', 'String', 'Sorting'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/minimum-time-difference/',
    notes: 'Parse "HH:MM" strings into total minutes and compute minimum difference.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-556-s',
    slug: 'next-greater-element-iii-strings',
    leetcodeNumber: 556,
    title: 'Next Greater Element III (String Digit Rearrangement)',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 44.0,
    isPremium: false,
    topics: ['Math', 'Two Pointers', 'String'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/next-greater-element-iii/',
    notes: 'Next permutation on digit char array checking 32-bit int bounds.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-722',
    slug: 'remove-comments',
    leetcodeNumber: 722,
    title: 'Remove Comments',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 38.0,
    isPremium: false,
    topics: ['Array', 'String'],
    companies: ['Microsoft'],
    url: 'https://leetcode.com/problems/remove-comments/',
    notes: 'State machine parser handling // single line and /* block comments */.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-791',
    slug: 'custom-sort-string',
    leetcodeNumber: 791,
    title: 'Custom Sort String',
    difficulty: 'Medium',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 100,
    acceptanceRate: 70.0,
    isPremium: false,
    topics: ['Hash Table', 'String', 'Sorting'],
    companies: ['Meta'],
    url: 'https://leetcode.com/problems/custom-sort-string/',
    notes: 'Frequency map count + string builder ordering by order string priority.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.anagrams-frequency-strings',
    patternSlug: 'anagrams-frequency-strings',
    patternTitle: 'Anagrams & Frequency Matching',
    questTitle: 'Quest: The Anagram Vault',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-848',
    slug: 'shifting-letters',
    leetcodeNumber: 848,
    title: 'Shifting Letters',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'String', 'Prefix Sum'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/shifting-letters/',
    notes: 'Suffix sum of shift values modulo 26 applied to character codes.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-890',
    slug: 'find-and-replace-pattern',
    leetcodeNumber: 890,
    title: 'Find and Replace Pattern',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 76.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/find-and-replace-pattern/',
    notes: 'Bi-directional bijection HashMap matching word against pattern.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.anagrams-frequency-strings',
    patternSlug: 'anagrams-frequency-strings',
    patternTitle: 'Anagrams & Frequency Matching',
    questTitle: 'Quest: The Anagram Vault',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-929',
    slug: 'unique-email-addresses',
    leetcodeNumber: 929,
    title: 'Unique Email Addresses',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 67.0,
    isPremium: false,
    topics: ['Array', 'Hash Table', 'String'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/unique-email-addresses/',
    notes: 'Parse local name removing dots and ignoring text after plus + sign.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-1071',
    slug: 'greatest-common-divisor-of-strings',
    leetcodeNumber: 1071,
    title: 'Greatest Common Divisor of Strings',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 52.0,
    isPremium: false,
    topics: ['Math', 'String'],
    companies: ['Apple', 'Amazon'],
    url: 'https://leetcode.com/problems/greatest-common-divisor-of-strings/',
    notes: 'If s1 + s2 == s2 + s1, answer is prefix of length gcd(len1, len2).',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-1668',
    slug: 'maximum-repeating-substring',
    leetcodeNumber: 1668,
    title: 'Maximum Repeating Substring',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 39.0,
    isPremium: false,
    topics: ['String', 'String Matching'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/maximum-repeating-substring/',
    notes: 'Increment K while sequence.repeat(k) is contained inside word.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.pattern-matching',
    patternSlug: 'pattern-matching',
    patternTitle: 'Pattern Matching & Substrings',
    questTitle: 'Quest: The Pattern Finder',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-1768',
    slug: 'merge-strings-alternately',
    leetcodeNumber: 1768,
    title: 'Merge Strings Alternately',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 12,
    xp: 50,
    acceptanceRate: 79.0,
    isPremium: false,
    topics: ['Two Pointers', 'String'],
    companies: ['Apple', 'Uber'],
    url: 'https://leetcode.com/problems/merge-strings-alternately/',
    notes: 'Interleave characters from word1 and word2 using two pointers.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-basics',
    patternSlug: 'string-basics',
    patternTitle: 'String Fundamentals & Manipulation',
    questTitle: 'Quest: The Woven Text',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-1813',
    slug: 'sentence-similarity-iii',
    leetcodeNumber: 1813,
    title: 'Sentence Similarity III',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'String'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/sentence-similarity-iii/',
    notes: 'Two pointer prefix and suffix word matching from both ends.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-1910',
    slug: 'remove-all-occurrences-of-a-substring',
    leetcodeNumber: 1910,
    title: 'Remove All Occurrences of a Substring',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 22,
    xp: 100,
    acceptanceRate: 77.0,
    isPremium: false,
    topics: ['String', 'Stack', 'Simulation'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/remove-all-occurrences-of-a-substring/',
    notes: 'Stack character pushing and matching top part of stack against part string.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
  {
    id: 'lc-2269',
    slug: 'find-the-k-beauty-of-a-number',
    leetcodeNumber: 2269,
    title: 'Find the K-Beauty of a Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 58.0,
    isPremium: false,
    topics: ['Math', 'String', 'Sliding Window'],
    companies: ['Amazon'],
    url: 'https://leetcode.com/problems/find-the-k-beauty-of-a-number/',
    notes: 'Convert num to string, sliding window of size K checking num % val == 0.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'Strings',
    patternId: 'pattern.string-parsing-simulation',
    patternSlug: 'string-parsing-simulation',
    patternTitle: 'String Parsing & Simulation',
    questTitle: 'Quest: The Scriptorium Parser',
    kingdomTitle: 'The Scriptorium',
  },
];
