import { ProblemModel } from '../../types';

export const TWO_POINTERS_PROBLEMS: ProblemModel[] = [
  // 1. Opposite Direction Pointers
  {
    id: 'lc-125',
    slug: 'valid-palindrome',
    leetcodeNumber: 125,
    title: 'Valid Palindrome',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 19,
    xp: 50,
    acceptanceRate: 72.7,
    isPremium: false,
    topics: ['Two Pointers', 'String'],
    companies: ['LinkedIn', 'Atlassian'],
    url: 'https://leetcode.com/problems/valid-palindrome/',
    notes: 'Inward pointer movement skipping alphanumeric non-matching characters.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-167',
    slug: 'two-sum-ii-input-array-is-sorted',
    leetcodeNumber: 167,
    title: 'Two Sum II - Input Array Is Sorted',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 57.6,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search'],
    companies: ['Oracle', 'Apple', 'Goldman Sachs', 'Amazon'],
    url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
    notes: 'Shrink search space inward based on sum comparison with target.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-680',
    slug: 'valid-palindrome-ii',
    leetcodeNumber: 680,
    title: 'Valid Palindrome II',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 21,
    xp: 50,
    acceptanceRate: 58.6,
    isPremium: false,
    topics: ['Two Pointers', 'String', 'Greedy'],
    companies: ['LinkedIn', 'Netflix', 'Oracle'],
    url: 'https://leetcode.com/problems/valid-palindrome-ii/',
    notes: 'Allow at most one character deletion fallback check.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-15',
    slug: '3sum',
    leetcodeNumber: 15,
    title: '3Sum',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 56.8,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Sorting'],
    companies: ['Salesforce', 'Goldman Sachs', 'Microsoft'],
    url: 'https://leetcode.com/problems/3sum/',
    notes: 'Sort array and apply opposite direction two pointers for fixed target -nums[i].',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-11',
    slug: 'container-with-most-water',
    leetcodeNumber: 11,
    title: 'Container With Most Water',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 45.2,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Greedy'],
    companies: ['Netflix', 'Adobe'],
    url: 'https://leetcode.com/problems/container-with-most-water/',
    notes: 'Move shorter line pointer inward to maximize area.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-16',
    slug: '3sum-closest',
    leetcodeNumber: 16,
    title: '3Sum Closest',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 53.9,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Sorting'],
    companies: ['Apple', 'Netflix'],
    url: 'https://leetcode.com/problems/3sum-closest/',
    notes: 'Track minimum diff while shrinking opposite pointers.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-881',
    slug: 'boats-to-save-people',
    leetcodeNumber: 881,
    title: 'Boats to Save People',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 29,
    xp: 100,
    acceptanceRate: 41.7,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Greedy', 'Sorting'],
    companies: ['Goldman Sachs', 'LinkedIn'],
    url: 'https://leetcode.com/problems/boats-to-save-people/',
    notes: 'Greedy pair heaviest with lightest person if sum <= limit.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-18',
    slug: '4sum',
    leetcodeNumber: 18,
    title: '4Sum',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Sorting'],
    companies: ['Amazon', 'Microsoft', 'Meta'],
    url: 'https://leetcode.com/problems/4sum/',
    notes: 'General K-Sum recursion down to 2Sum opposite pointers.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-259',
    slug: '3sum-smaller',
    leetcodeNumber: 259,
    title: '3Sum Smaller',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: true,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Sorting'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/3sum-smaller/',
    notes: 'Count valid pairs right - left when sum < target.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.opposite-pointers',
    patternSlug: 'opposite-pointers',
    patternTitle: 'Opposite Direction Pointers',
    questTitle: 'Quest: The Meeting Streams',
    kingdomTitle: 'Twin Rivers Kingdom',
  },

  // 2. Fast & Slow Pointers
  {
    id: 'lc-141',
    slug: 'linked-list-cycle',
    leetcodeNumber: 141,
    title: 'Linked List Cycle',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 18,
    xp: 50,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    url: 'https://leetcode.com/problems/linked-list-cycle/',
    notes: 'Floyds tortoise and hare collision check.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.fast-slow-pointers',
    patternSlug: 'fast-slow-pointers',
    patternTitle: 'Fast & Slow Pointers',
    questTitle: 'Quest: The Race of Two',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-202',
    slug: 'happy-number',
    leetcodeNumber: 202,
    title: 'Happy Number',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 19,
    xp: 50,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Hash Table', 'Math', 'Two Pointers'],
    companies: ['Google', 'Uber', 'Amazon'],
    url: 'https://leetcode.com/problems/happy-number/',
    notes: 'Detect cycle in sum of squared digits using fast/slow pointers.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.fast-slow-pointers',
    patternSlug: 'fast-slow-pointers',
    patternTitle: 'Fast & Slow Pointers',
    questTitle: 'Quest: The Race of Two',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-876',
    slug: 'middle-of-the-linked-list',
    leetcodeNumber: 876,
    title: 'Middle of the Linked List',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 76.0,
    isPremium: false,
    topics: ['Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Apple', 'Meta'],
    url: 'https://leetcode.com/problems/middle-of-the-linked-list/',
    notes: 'Fast pointer moves at 2x speed; slow stops at midpoint.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.fast-slow-pointers',
    patternSlug: 'fast-slow-pointers',
    patternTitle: 'Fast & Slow Pointers',
    questTitle: 'Quest: The Race of Two',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-142',
    slug: 'linked-list-cycle-ii',
    leetcodeNumber: 142,
    title: 'Linked List Cycle II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 50.0,
    isPremium: false,
    topics: ['Hash Table', 'Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/linked-list-cycle-ii/',
    notes: 'Reset pointer to head after collision to find cycle entry node.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.fast-slow-pointers',
    patternSlug: 'fast-slow-pointers',
    patternTitle: 'Fast & Slow Pointers',
    questTitle: 'Quest: The Race of Two',
    kingdomTitle: 'Twin Rivers Kingdom',
  },

  // 3. Same Direction / Partitioning
  {
    id: 'lc-392',
    slug: 'is-subsequence',
    leetcodeNumber: 392,
    title: 'Is Subsequence',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 15,
    xp: 50,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Two Pointers', 'String', 'Dynamic Programming'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/is-subsequence/',
    notes: 'Two pointer matching on characters of string s and t.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.same-direction-pointers',
    patternSlug: 'same-direction-pointers',
    patternTitle: 'Same Direction / Partitioning',
    questTitle: 'Quest: The Parallel Path',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-80',
    slug: 'remove-duplicates-from-sorted-array-ii',
    leetcodeNumber: 80,
    title: 'Remove Duplicates from Sorted Array II',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 25,
    xp: 100,
    acceptanceRate: 55.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Meta', 'Amazon', 'Microsoft'],
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/',
    notes: 'Allow at most 2 duplicates via slow write pointer comparison nums[slow-2].',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.same-direction-pointers',
    patternSlug: 'same-direction-pointers',
    patternTitle: 'Same Direction / Partitioning',
    questTitle: 'Quest: The Parallel Path',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-75',
    slug: 'sort-colors',
    leetcodeNumber: 75,
    title: 'Sort Colors',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 60.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Sorting'],
    companies: ['Netflix', 'Adobe', 'Salesforce'],
    url: 'https://leetcode.com/problems/sort-colors/',
    notes: 'Dutch National Flag 3-way partitioning algorithm.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.same-direction-pointers',
    patternSlug: 'same-direction-pointers',
    patternTitle: 'Same Direction / Partitioning',
    questTitle: 'Quest: The Parallel Path',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-340',
    slug: 'longest-substring-with-at-most-k-distinct-characters',
    leetcodeNumber: 340,
    title: 'Longest Substring with At Most K Distinct Characters',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'High',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 48.0,
    isPremium: true,
    topics: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/',
    notes: 'Two pointer sliding window with HashMap frequency counts.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.same-direction-pointers',
    patternSlug: 'same-direction-pointers',
    patternTitle: 'Same Direction / Partitioning',
    questTitle: 'Quest: The Parallel Path',
    kingdomTitle: 'Twin Rivers Kingdom',
  },

  // 4. Merge & Partition via Two Pointers
  {
    id: 'lc-977',
    slug: 'squares-of-a-sorted-array',
    leetcodeNumber: 977,
    title: 'Squares of a Sorted Array',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 72.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Sorting'],
    companies: ['Amazon', 'Meta', 'Google'],
    url: 'https://leetcode.com/problems/squares-of-a-sorted-array/',
    notes: 'Fill result array backwards comparing abs(nums[left]) vs abs(nums[right]).',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-925',
    slug: 'long-pressed-name',
    leetcodeNumber: 925,
    title: 'Long Pressed Name',
    difficulty: 'Easy',
    level: 'Learn',
    frequency: 'Medium',
    estimatedTimeMin: 22,
    xp: 50,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Two Pointers', 'String'],
    companies: ['Google', 'Amazon'],
    url: 'https://leetcode.com/problems/long-pressed-name/',
    notes: 'Compare characters and skip repeated long-pressed chars in typed.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-844',
    slug: 'backspace-string-compare',
    leetcodeNumber: 844,
    title: 'Backspace String Compare',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 24,
    xp: 50,
    acceptanceRate: 48.0,
    isPremium: false,
    topics: ['Two Pointers', 'String', 'Stack', 'Simulation'],
    companies: ['Google', 'Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/backspace-string-compare/',
    notes: 'Reverse two-pointer scan skipping backspaced # characters.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-28',
    slug: 'find-the-index-of-the-first-occurrence-in-a-string',
    leetcodeNumber: 28,
    title: 'Find the Index of the First Occurrence in a String',
    difficulty: 'Easy',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 20,
    xp: 50,
    acceptanceRate: 40.0,
    isPremium: false,
    topics: ['Two Pointers', 'String', 'String Matching'],
    companies: ['Amazon', 'Google', 'Meta'],
    url: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',
    notes: 'Sliding window / two pointer needle matching in haystack.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-986',
    slug: 'interval-list-intersections',
    leetcodeNumber: 986,
    title: 'Interval List Intersections',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 32,
    xp: 100,
    acceptanceRate: 71.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers'],
    companies: ['Meta', 'Amazon', 'Google'],
    url: 'https://leetcode.com/problems/interval-list-intersections/',
    notes: 'Two pointer intersection max(A.start, B.start) <= min(A.end, B.end).',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-763',
    slug: 'partition-labels',
    leetcodeNumber: 763,
    title: 'Partition Labels',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'High',
    estimatedTimeMin: 30,
    xp: 100,
    acceptanceRate: 79.0,
    isPremium: false,
    topics: ['Hash Table', 'Two Pointers', 'String', 'Greedy'],
    companies: ['Amazon', 'Meta'],
    url: 'https://leetcode.com/problems/partition-labels/',
    notes: 'Track last occurrences of characters and partition when index == maxLastPos.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-2422',
    slug: 'merge-operations-to-turn-array-into-a-palindrome',
    leetcodeNumber: 2422,
    title: 'Merge Operations to Turn Array Into a Palindrome',
    difficulty: 'Medium',
    level: 'Practice',
    frequency: 'Low',
    estimatedTimeMin: 28,
    xp: 100,
    acceptanceRate: 65.0,
    isPremium: true,
    topics: ['Array', 'Two Pointers', 'Greedy'],
    companies: ['Google'],
    url: 'https://leetcode.com/problems/merge-operations-to-turn-array-into-a-palindrome/',
    notes: 'Greedy left and right pointer sum merge when values differ.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-475',
    slug: 'heaters',
    leetcodeNumber: 475,
    title: 'Heaters',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 35,
    xp: 100,
    acceptanceRate: 36.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Sorting'],
    companies: ['Google', 'Meta'],
    url: 'https://leetcode.com/problems/heaters/',
    notes: 'Sort houses & heaters and compute min distance to nearest heater using two pointers.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
  {
    id: 'lc-826',
    slug: 'most-profit-assigning-work',
    leetcodeNumber: 826,
    title: 'Most Profit Assigning Work',
    difficulty: 'Medium',
    level: 'Master',
    frequency: 'Medium',
    estimatedTimeMin: 34,
    xp: 100,
    acceptanceRate: 45.0,
    isPremium: false,
    topics: ['Array', 'Two Pointers', 'Binary Search', 'Greedy', 'Sorting'],
    companies: ['Amazon', 'Google'],
    url: 'https://leetcode.com/problems/most-profit-assigning-work/',
    notes: 'Sort jobs by difficulty and worker ability, tracking max profit available.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    patternId: 'pattern.merge-partition-pointers',
    patternSlug: 'merge-partition-pointers',
    patternTitle: 'Merge & Partition via Two Pointers',
    questTitle: 'Quest: The Confluence',
    kingdomTitle: 'Twin Rivers Kingdom',
  },
];
