import { SubtopicModel } from '../types';

export const ALL_SUBTOPICS: SubtopicModel[] = [
  // 1. Basic Arrays (cat-1)
  {
    id: 'subtopic.basic-arrays.traversal-manipulation',
    slug: 'array-traversal',
    title: 'Array Traversal & Operations',
    description: 'Fundamental sequential scanning, contiguous indexing, and element updates.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Array',
    order: 1,
    patternIds: ['pattern.array-fundamentals'],
  },
  {
    id: 'subtopic.basic-arrays.subarray-dynamics',
    slug: 'subarray-dynamics',
    title: 'Subarray Dynamics & Kadane',
    description: 'Dynamic contiguous subsegment evaluation and linear maximum sum optimizations.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Array',
    order: 2,
    patternIds: ['pattern.kadanes-algorithm'],
  },
  {
    id: 'subtopic.basic-arrays.rearrangement-partition',
    slug: 'array-rearrangement',
    title: 'In-Place Rearrangement & Partitioning',
    description: 'Permutations, rotations, and in-place element shuffles.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Array',
    order: 3,
    patternIds: ['pattern.array-rearrangement'],
  },
  {
    id: 'subtopic.basic-arrays.simulation-design',
    slug: 'array-simulation',
    title: 'Simulation & Grid Design',
    description: 'Array state machines and deterministic stepwise rules execution.',
    categoryId: 'cat-1',
    categorySlug: 'basic-arrays',
    categoryTitle: 'Array',
    order: 4,
    patternIds: ['pattern.array-simulation-design'],
  },

  // 2. Prefix Sum (cat-2)
  {
    id: 'subtopic.prefix-sum.core-ranges',
    slug: 'prefix-sum-core',
    title: '1D & 2D Cumulative Sums',
    description: 'Static subarray and submatrix range sum queries in O(1) time.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    order: 1,
    patternIds: ['pattern.prefix-sum-basics', 'pattern.2d-prefix-sum'],
  },
  {
    id: 'subtopic.prefix-sum.difference-arrays-xor',
    slug: 'difference-arrays-xor',
    title: 'Prefix XOR & Difference Arrays',
    description: 'Bitwise cumulative XOR queries and range additions via difference arrays.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    order: 2,
    patternIds: ['pattern.prefix-xor'],
  },
  {
    id: 'subtopic.prefix-sum.prefix-hashing',
    slug: 'prefix-hashing',
    title: 'Prefix Sum with Hashing',
    description: 'Finding exact target subsegments and modulo divisibility using hash map histories.',
    categoryId: 'cat-2',
    categorySlug: 'prefix-sum',
    categoryTitle: 'Prefix Sum',
    order: 3,
    patternIds: ['pattern.prefix-sum-hashing'],
  },

  // 3. Two Pointers (cat-3)
  {
    id: 'subtopic.two-pointers.opposite-direction',
    slug: 'opposite-direction',
    title: 'Opposite Direction Pointers',
    description: 'Inward convergent boundaries on sorted sequences and palindromic checks.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    order: 1,
    patternIds: ['pattern.opposite-pointers'],
  },
  {
    id: 'subtopic.two-pointers.fast-slow',
    slug: 'fast-slow-pointers',
    title: 'Fast & Slow Pointers',
    description: 'Floyd cycle detection and mid-point discovery on linear structures.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    order: 2,
    patternIds: ['pattern.fast-slow-pointers'],
  },
  {
    id: 'subtopic.two-pointers.partition-merge',
    slug: 'partition-merge',
    title: 'Same Direction & Partitioning',
    description: 'In-place write filtering, array merging, and Dutch national flag partitions.',
    categoryId: 'cat-3',
    categorySlug: 'two-pointers',
    categoryTitle: 'Two Pointers',
    order: 3,
    patternIds: ['pattern.same-direction-pointers', 'pattern.merge-partition-pointers'],
  },

  // 4. Sliding Window (cat-4)
  {
    id: 'subtopic.sliding-window.window-frames',
    slug: 'window-frames',
    title: 'Fixed & Variable Window Frames',
    description: 'Sliding contiguous subsegment bounds to maximize or minimize window criteria.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    order: 1,
    patternIds: ['pattern.fixed-window', 'pattern.variable-window'],
  },
  {
    id: 'subtopic.sliding-window.frequency-matching',
    slug: 'frequency-matching',
    title: 'Sliding Window + Frequency Tracking',
    description: 'Dynamic character frequency maps and bounded substring searches.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    order: 2,
    patternIds: ['pattern.sliding-window-hashmap', 'pattern.bounded-frame-substrings'],
  },
  {
    id: 'subtopic.sliding-window.monotonic-window',
    slug: 'monotonic-window',
    title: 'Monotonic Window Deque',
    description: 'Maintaining extreme elements inside sliding frames in amortized O(1) time.',
    categoryId: 'cat-4',
    categorySlug: 'sliding-window',
    categoryTitle: 'Sliding Window',
    order: 3,
    patternIds: ['pattern.monotonic-window'],
  },

  // 5. Hashing (cat-5)
  {
    id: 'subtopic.hashing.frequency-lookups',
    slug: 'frequency-lookups',
    title: 'Frequency Counting & Set Membership',
    description: 'Instant O(1) element lookups, set uniqueness, and frequency distributions.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    order: 1,
    patternIds: ['pattern.hashmap-frequency', 'pattern.set-lookup'],
  },
  {
    id: 'subtopic.hashing.cache-design',
    slug: 'cache-design',
    title: 'Cache & Custom Hashing Design',
    description: 'Designing LRU/LFU cache policies and customized composite key lookups.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    order: 2,
    patternIds: ['pattern.hashing-design'],
  },
  {
    id: 'subtopic.hashing.ledger-mappings',
    slug: 'ledger-mappings',
    title: 'String & Array Ledger Mappings',
    description: 'Isomorphic string validations and bijective symbol relationships.',
    categoryId: 'cat-5',
    categorySlug: 'hashing',
    categoryTitle: 'Hashing',
    order: 3,
    patternIds: ['pattern.marked-ledger-hashing'],
  },

  // 6. Binary Search (cat-6)
  {
    id: 'subtopic.binary-search.classic-rotated',
    slug: 'classic-rotated-search',
    title: 'Classic & Rotated Array Search',
    description: 'Logarithmic division of monotonic arrays and pivoted sorted ranges.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    order: 1,
    patternIds: ['pattern.classic-binary-search', 'pattern.rotated-binary-search'],
  },
  {
    id: 'subtopic.binary-search.search-on-answer',
    slug: 'search-on-answer',
    title: 'Search on Answer & Feasibility',
    description: 'Optimizing bounded monotonic criteria via custom predicate test functions.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    order: 2,
    patternIds: ['pattern.search-on-answer'],
  },
  {
    id: 'subtopic.binary-search.2d-advanced',
    slug: '2d-advanced-search',
    title: '2D Matrices & Multi-Dimensional Search',
    description: 'Row-column staircase traversals and distance pair ranking.',
    categoryId: 'cat-6',
    categorySlug: 'binary-search',
    categoryTitle: 'Binary Search',
    order: 3,
    patternIds: ['pattern.2d-binary-search'],
  },

  // 7. Sorting (cat-7)
  {
    id: 'subtopic.sorting.comparisons-comparators',
    slug: 'comparisons-comparators',
    title: 'Comparison Sorting & Custom Comparators',
    description: 'Stable ordering algorithms and multi-key comparative sorting functions.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    order: 1,
    patternIds: ['pattern.comparison-sorting', 'pattern.custom-comparators'],
  },
  {
    id: 'subtopic.sorting.cyclic-linear-sort',
    slug: 'cyclic-linear-sort',
    title: 'Cyclic & Non-Comparison Sort',
    description: 'O(N) index placement for 1-to-N ranges and bucket distributions.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    order: 2,
    patternIds: ['pattern.cyclic-sort'],
  },
  {
    id: 'subtopic.sorting.presorting-applications',
    slug: 'presorting-applications',
    title: 'Pre-Sorting Transformations',
    description: 'Structuring unordered data to unlock greedy and two-pointer heuristics.',
    categoryId: 'cat-7',
    categorySlug: 'sorting',
    categoryTitle: 'Sorting',
    order: 3,
    patternIds: ['pattern.sorting-applications'],
  },

  // 8. Stack (cat-8)
  {
    id: 'subtopic.stack.monotonic',
    slug: 'monotonic-stack',
    title: 'Monotonic Stack',
    description: 'Finding next greater or smaller elements in linear amortized time.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    order: 1,
    patternIds: ['pattern.monotonic-stack'],
  },
  {
    id: 'subtopic.stack.parsing-expressions',
    slug: 'parsing-expressions',
    title: 'Expression Evaluation & Delimiters',
    description: 'Nested parenthesis matching, operator precedence, and path simplifications.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    order: 2,
    patternIds: ['pattern.expression-evaluation', 'pattern.stack-string-processing'],
  },
  {
    id: 'subtopic.stack.design-simulation',
    slug: 'stack-design-simulation',
    title: 'Stack Design & Simulation',
    description: 'Min-stack auxiliary design, frequency stacks, and LIFO sequence validation.',
    categoryId: 'cat-8',
    categorySlug: 'stack',
    categoryTitle: 'Stack',
    order: 3,
    patternIds: ['pattern.stack-simulation'],
  },

  // 9. Queue & Deque (cat-9)
  {
    id: 'subtopic.queue-deque.queue-fundamentals-bfs',
    slug: 'queue-fundamentals-bfs',
    title: 'FIFO Queues & Breadth-First Search',
    description: 'Sequential stream buffering and level-order graph and tree explorations.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue / Deque',
    order: 1,
    patternIds: ['pattern.queue-fundamentals', 'pattern.bfs-queue'],
  },
  {
    id: 'subtopic.queue-deque.monotonic-deque',
    slug: 'monotonic-deque',
    title: 'Monotonic Deque',
    description: 'Double-ended queues maintaining sorted sliding extrema in O(1) time.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue / Deque',
    order: 2,
    patternIds: ['pattern.monotonic-deque'],
  },
  {
    id: 'subtopic.queue-deque.buffer-design',
    slug: 'buffer-design',
    title: 'Circular Buffer & Deque Design',
    description: 'Ring buffer data structures and multi-ended queue implementations.',
    categoryId: 'cat-9',
    categorySlug: 'queue-deque',
    categoryTitle: 'Queue / Deque',
    order: 3,
    patternIds: ['pattern.circular-queue-design'],
  },

  // 10. Intervals (cat-10)
  {
    id: 'subtopic.intervals.merge-schedule',
    slug: 'interval-merge-schedule',
    title: 'Interval Merging & Scheduling',
    description: 'Overlapping range unification and greedy resource allocation.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    order: 1,
    patternIds: ['pattern.merge-intervals', 'pattern.interval-scheduling'],
  },
  {
    id: 'subtopic.intervals.sweep-line',
    slug: 'sweep-line-intervals',
    title: 'Sweep Line & Interval Design',
    description: 'Event-driven timeline sweeps, meeting room occupancy, and calendar trees.',
    categoryId: 'cat-10',
    categorySlug: 'intervals',
    categoryTitle: 'Intervals',
    order: 2,
    patternIds: ['pattern.sweep-line', 'pattern.interval-design-advanced'],
  },

  // 11. Linked List (cat-11)
  {
    id: 'subtopic.linked-list.manipulation-pointers',
    slug: 'list-manipulation-pointers',
    title: 'Pointer Rewiring & Cycle Detection',
    description: 'In-place pointer reversal, dummy nodes, and two-pointer cycle detection.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    order: 1,
    patternIds: ['pattern.basic-linked-list', 'pattern.fast-slow-linked-list'],
  },
  {
    id: 'subtopic.linked-list.advanced-design',
    slug: 'list-advanced-design',
    title: 'Doubly-Linked Lists & Specialized Structures',
    description: 'Skip lists, copy with random pointers, and compound cache nodes.',
    categoryId: 'cat-11',
    categorySlug: 'linked-list',
    categoryTitle: 'Linked List',
    order: 2,
    patternIds: ['pattern.advanced-linked-list-structures', 'pattern.linked-list-design'],
  },

  // 12. Binary Trees (cat-12)
  {
    id: 'subtopic.binary-trees.traversals-properties',
    slug: 'tree-traversals-properties',
    title: 'Tree Traversals & Structural Properties',
    description: 'Pre, in, post, and level-order scans alongside recursive depth and symmetry checks.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Tree',
    order: 1,
    patternIds: ['pattern.tree-traversal', 'pattern.recursive-tree-properties'],
  },
  {
    id: 'subtopic.binary-trees.construction-paths-views',
    slug: 'tree-construction-paths-views',
    title: 'Construction, Paths & Boundary Views',
    description: 'Serialization, reconstruction from orders, and root-to-leaf path collections.',
    categoryId: 'cat-12',
    categorySlug: 'binary-trees',
    categoryTitle: 'Binary Tree',
    order: 2,
    patternIds: ['pattern.tree-construction', 'pattern.root-to-leaf-paths', 'pattern.tree-views-levels'],
  },

  // 13. Binary Search Trees (cat-13)
  {
    id: 'subtopic.bst.fundamentals-order-statistics',
    slug: 'bst-fundamentals-order',
    title: 'BST Fundamentals & Order Statistics',
    description: 'BST property validation, in-order rank queries, and successor searches.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Tree',
    order: 1,
    patternIds: ['pattern.bst-fundamentals', 'pattern.bst-traversal-order'],
  },
  {
    id: 'subtopic.bst.structural-mutations',
    slug: 'bst-structural-mutations',
    title: 'LCA & Structural Mutations',
    description: 'Lowest common ancestor queries and node insertions/deletions maintaining invariant.',
    categoryId: 'cat-13',
    categorySlug: 'binary-search-trees',
    categoryTitle: 'Binary Search Tree',
    order: 2,
    patternIds: ['pattern.lca-structural-bst', 'pattern.bst-modification'],
  },

  // 14. Graphs (cat-14)
  {
    id: 'subtopic.graphs.traversals-dsu',
    slug: 'graph-traversals-dsu',
    title: 'DFS, BFS & Disjoint Set Union',
    description: 'Connected components, graph cycle detection, and union-find connectivity.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graph',
    order: 1,
    patternIds: ['pattern.graph-traversal', 'pattern.union-find'],
  },
  {
    id: 'subtopic.graphs.topological-bipartite',
    slug: 'topological-bipartite',
    title: 'Topological Sort & Bipartite Graphs',
    description: "Kahn's in-degree algorithms, DAG ordering, and 2-colorability checks.",
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graph',
    order: 2,
    patternIds: ['pattern.topological-sort', 'pattern.bipartite-coloring'],
  },
  {
    id: 'subtopic.graphs.advanced-construction',
    slug: 'advanced-graph-construction',
    title: 'Multi-Source BFS & Graph Modeling',
    description: 'Word ladders, implicit state space graphs, and multi-origin wavefronts.',
    categoryId: 'cat-14',
    categorySlug: 'graphs',
    categoryTitle: 'Graph',
    order: 3,
    patternIds: ['pattern.advanced-graph-traversal', 'pattern.graph-construction-multi-bfs'],
  },

  // 15. Shortest Path Algorithms (cat-15)
  {
    id: 'subtopic.shortest-path.bfs-dijkstra',
    slug: 'bfs-dijkstra',
    title: 'BFS & Dijkstra Algorithms',
    description: 'Unweighted shortest paths and non-negative edge weight priority queue relaxations.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path',
    order: 1,
    patternIds: ['pattern.bfs-shortest-path', 'pattern.dijkstras-algorithm'],
  },
  {
    id: 'subtopic.shortest-path.negative-weights-heuristics',
    slug: 'negative-weights-heuristics',
    title: 'Bellman-Ford, 0-1 BFS & State Graphs',
    description: 'Negative cycle detection, deque relaxations, and multi-state path matrices.',
    categoryId: 'cat-15',
    categorySlug: 'shortest-path',
    categoryTitle: 'Shortest Path',
    order: 2,
    patternIds: ['pattern.bellman-ford', 'pattern.a-star-01-bfs', 'pattern.modified-dijkstra-variants'],
  },

  // 16. Minimum Spanning Tree (cat-16)
  {
    id: 'subtopic.mst.algorithms-applications',
    slug: 'mst-algorithms-applications',
    title: 'MST Algorithms & Applications',
    description: "Kruskal's edge-sorting, Prim's growing vertex cuts, and min-cost network designs.",
    categoryId: 'cat-16',
    categorySlug: 'minimum-spanning-tree',
    categoryTitle: 'Minimum Spanning Tree',
    order: 1,
    patternIds: ['pattern.kruskals-algorithm', 'pattern.prims-algorithm', 'pattern.mst-applications'],
  },

  // 17. Backtracking (cat-17)
  {
    id: 'subtopic.backtracking.subsets-permutations',
    slug: 'subsets-permutations',
    title: 'Subsets, Combinations & Permutations',
    description: 'Decision trees exploring power sets, combination sums, and element orderings.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    order: 1,
    patternIds: ['pattern.subsets-combinations', 'pattern.permutations'],
  },
  {
    id: 'subtopic.backtracking.constraints-puzzles',
    slug: 'constraints-puzzles',
    title: 'Grid Constraints & Advanced Puzzles',
    description: 'N-Queens, Sudoku solvers, word searches, and string partition backtracking.',
    categoryId: 'cat-17',
    categorySlug: 'backtracking',
    categoryTitle: 'Backtracking',
    order: 2,
    patternIds: ['pattern.constraint-satisfaction', 'pattern.partitioning-path-backtracking', 'pattern.advanced-backtracking-puzzles'],
  },

  // 18. Greedy (cat-18)
  {
    id: 'subtopic.greedy.intervals-arrays',
    slug: 'greedy-intervals-arrays',
    title: 'Intervals & Array Greedy Choices',
    description: 'Locally optimal choices proving global optimality on intervals and arrays.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    order: 1,
    patternIds: ['pattern.interval-greedy', 'pattern.array-greedy'],
  },
  {
    id: 'subtopic.greedy.sorting-scheduling',
    slug: 'greedy-sorting-scheduling',
    title: 'Sorting & Advanced Task Scheduling',
    description: 'Greedy priority scheduling, fractional knapsack, and gas station simulations.',
    categoryId: 'cat-18',
    categorySlug: 'greedy',
    categoryTitle: 'Greedy',
    order: 2,
    patternIds: ['pattern.greedy-sorting', 'pattern.greedy-graph-scheduling'],
  },

  // 19. Heap (cat-19)
  {
    id: 'subtopic.heap.top-k-two-heap',
    slug: 'top-k-two-heap',
    title: 'Top-K Elements & Two-Heap Streams',
    description: 'Priority queue rankings and dual-heap dynamic median tracking.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap / Priority Queue',
    order: 1,
    patternIds: ['pattern.top-k-elements', 'pattern.two-heap'],
  },
  {
    id: 'subtopic.heap.scheduling-design',
    slug: 'heap-scheduling-design',
    title: 'Task Scheduling & Heap Design',
    description: 'Event timelines, CPU process scheduling, and custom heap data structures.',
    categoryId: 'cat-19',
    categorySlug: 'heap',
    categoryTitle: 'Heap / Priority Queue',
    order: 2,
    patternIds: ['pattern.heap-scheduling', 'pattern.heap-design-simulation'],
  },

  // 20. Dynamic Programming (cat-20)
  {
    id: 'subtopic.dp.linear-grid',
    slug: 'linear-grid-dp',
    title: '1D & 2D Grid DP',
    description: 'Optimal substructure over linear sequences and 2D grid matrix walks.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    order: 1,
    patternIds: ['pattern.1d-dp', 'pattern.2d-grid-dp'],
  },
  {
    id: 'subtopic.dp.knapsack-strings',
    slug: 'knapsack-strings-dp',
    title: 'Knapsack & String Subsequence DP',
    description: 'Bounded/unbounded item selection and edit distance / LCS table evaluations.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    order: 2,
    patternIds: ['pattern.knapsack-dp', 'pattern.string-dp'],
  },
  {
    id: 'subtopic.dp.intervals-trees-states',
    slug: 'intervals-trees-states-dp',
    title: 'Interval, Tree & State-Machine DP',
    description: 'Sub-range merges, post-order tree DP, and finite automaton state transitions.',
    categoryId: 'cat-20',
    categorySlug: 'dynamic-programming',
    categoryTitle: 'Dynamic Programming',
    order: 3,
    patternIds: ['pattern.interval-dp', 'pattern.tree-state-machine-dp', 'pattern.advanced-state-dp'],
  },

  // 21. Bit Manipulation (cat-21)
  {
    id: 'subtopic.bit-manipulation.tricks-xor',
    slug: 'bit-tricks-xor',
    title: 'Bitwise Fundamentals & XOR Properties',
    description: 'Bit shifts, masks, sign manipulation, and XOR self-cancellation identities.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    order: 1,
    patternIds: ['pattern.basic-bit-tricks', 'pattern.xor-applications'],
  },
  {
    id: 'subtopic.bit-manipulation.bitmasking-subsets',
    slug: 'bitmasking-subsets',
    title: 'Bitmask DP & Subset Counting',
    description: 'Representing small power sets as integer bit vectors for state compression.',
    categoryId: 'cat-21',
    categorySlug: 'bit-manipulation',
    categoryTitle: 'Bit Manipulation',
    order: 2,
    patternIds: ['pattern.bitmask-dp', 'pattern.bitmask-subsets-counting'],
  },

  // 22. Strings (cat-22)
  {
    id: 'subtopic.strings.fundamentals-anagrams-palindromes',
    slug: 'string-fundamentals',
    title: 'Fundamentals, Palindromes & Anagrams',
    description: 'String mutability, character arrays, frequency equality, and center expansion.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'String',
    order: 1,
    patternIds: ['pattern.string-basics', 'pattern.palindromic-strings', 'pattern.anagrams-frequency-strings'],
  },
  {
    id: 'subtopic.strings.matching-tries-parsing',
    slug: 'matching-tries-parsing',
    title: 'Pattern Matching, Tries & Parsing',
    description: 'Rolling hashes, prefix trees (Trie), and programmatic string tokenization.',
    categoryId: 'cat-22',
    categorySlug: 'strings',
    categoryTitle: 'String',
    order: 2,
    patternIds: ['pattern.pattern-matching', 'pattern.trie-based-strings', 'pattern.string-parsing-simulation'],
  },

  // 23. Matrix (cat-23)
  {
    id: 'subtopic.matrix.traversal-search',
    slug: 'matrix-traversal-search',
    title: 'Matrix Traversal & Search',
    description: 'Spiral orders, diagonal scans, and staircase binary searches on sorted grids.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    order: 1,
    patternIds: ['pattern.matrix-traversal', 'pattern.matrix-search'],
  },
  {
    id: 'subtopic.matrix.graph-transformations',
    slug: 'matrix-graph-transforms',
    title: 'Matrix as Graph & In-Place Transforms',
    description: 'Flood fill DFS/BFS, topological grid ordering, and 90-degree in-place rotations.',
    categoryId: 'cat-23',
    categorySlug: 'matrix',
    categoryTitle: 'Matrix',
    order: 2,
    patternIds: ['pattern.matrix-as-graph', 'pattern.in-place-matrix-manipulation', 'pattern.matrix-construction-rotation'],
  },

  // 24. Math & Number Theory (cat-24)
  {
    id: 'subtopic.math.primes-modular-arithmetic',
    slug: 'primes-modular-arithmetic',
    title: 'Primes, GCD & Modular Arithmetic',
    description: 'Sieve of Eratosthenes, Euclidean GCD, modular inverses, and prime factorizations.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    order: 1,
    patternIds: ['pattern.number-properties', 'pattern.gcd-lcm-modular-arithmetic'],
  },
  {
    id: 'subtopic.math.combinatorics-geometry',
    slug: 'combinatorics-geometry',
    title: 'Combinatorics, Probability & Geometry',
    description: 'Binomial coefficients, Pascal triangles, point geometry, and convex hulls.',
    categoryId: 'cat-24',
    categorySlug: 'math-number-theory',
    categoryTitle: 'Math & Number Theory',
    order: 2,
    patternIds: ['pattern.combinatorics-probability', 'pattern.geometry-simulation', 'pattern.number-theory-applications'],
  },

  // 25. Advanced Algorithms (cat-25)
  {
    id: 'subtopic.advanced.trees-fenwick-segment',
    slug: 'segment-fenwick-trees',
    title: 'Segment Trees, Fenwick & Advanced Trees',
    description: 'Dynamic range minimum/sum updates and Heavy-Light tree path queries.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    order: 1,
    patternIds: ['pattern.segment-fenwick-trees', 'pattern.heavy-light-advanced-trees'],
  },
  {
    id: 'subtopic.advanced.strings-flows-geometry',
    slug: 'strings-flows-geometry',
    title: 'KMP, Network Flow & Line Sweep',
    description: 'Linear string matching automata, max-flow min-cut, and 2D computational geometry.',
    categoryId: 'cat-25',
    categorySlug: 'advanced-algorithms',
    categoryTitle: 'Advanced Algorithms',
    order: 2,
    patternIds: ['pattern.advanced-string-matching', 'pattern.network-flow-matching', 'pattern.line-sweep-geometry'],
  },
];

const PATTERN_TO_SUBTOPIC_MAP = new Map<string, SubtopicModel>();

ALL_SUBTOPICS.forEach((subtopic) => {
  subtopic.patternIds.forEach((patId) => {
    PATTERN_TO_SUBTOPIC_MAP.set(patId, subtopic);
    const bareSlug = patId.replace(/^pattern\./, '');
    PATTERN_TO_SUBTOPIC_MAP.set(bareSlug, subtopic);
  });
});

export function getSubtopicForPattern(patternSlugOrId: string): SubtopicModel | undefined {
  return PATTERN_TO_SUBTOPIC_MAP.get(patternSlugOrId);
}

export function getSubtopicsForCategory(categorySlugOrId: string): SubtopicModel[] {
  return ALL_SUBTOPICS.filter(
    (s) => s.categorySlug === categorySlugOrId || s.categoryId === categorySlugOrId
  ).sort((a, b) => a.order - b.order);
}
